[info]
name = "unknown"
nb_wildcards = 0

[[continents]]
id = 1
name = "Stadtmitte"
bonus = 8
color = "white"

[[continents]]
id = 2
name = "Nord"
bonus = 6
color = "white"

[[continents]]
id = 3
name = "Ost"
bonus = 4
color = "white"

[[continents]]
id = 4
name = "Süd-Ost"
bonus = 3
color = "white"

[[continents]]
id = 5
name = "Süd"
bonus = 6
color = "white"

[[continents]]
id = 6
name = "West"
bonus = 5
color = "white"

[[countries]]
id = 1
name = "Wedding"
continent = 1
x = 208
y = 161
cardtype = "Cavalry"
connections = [9, 38, 10, 11, 2, 6, 5]

[[countries]]
id = 2
name = "Prenzlauer_Berg"
continent = 1
x = 258
y = 171
cardtype = "Infantry"
connections = [1, 11, 13, 15, 20, 3, 6]

[[countries]]
id = 3
name = "Friedrichshain"
continent = 1
x = 273
y = 200
cardtype = "Cannon"
connections = [2, 20, 28, 4, 6]

[[countries]]
id = 4
name = "Kreuzberg"
continent = 1
x = 238
y = 224
cardtype = "Cavalry"
connections = [3, 28, 27, 31, 30, 5, 6]

[[countries]]
id = 5
name = "Tiergarten"
continent = 1
x = 200
y = 192
cardtype = "Infantry"
connections = [1, 4, 30, 38, 6]

[[countries]]
id = 6
name = "Mitte"
continent = 1
x = 234
y = 193
cardtype = "Cannon"
connections = [1, 2, 3, 4, 5]

[[countries]]
id = 7
name = "Henningsdorf"
continent = 2
x = 147
y = 72
cardtype = "Cavalry"
connections = [8]

[[countries]]
id = 8
name = "Reinickendorf"
continent = 2
x = 123
y = 95
cardtype = "Infantry"
connections = [7, 40, 9, 10, 11]

[[countries]]
id = 9
name = "Tegel"
continent = 2
x = 139
y = 141
cardtype = "Cannon"
connections = [1, 8, 39, 40, 38, 10]

[[countries]]
id = 10
name = "Wittenau"
continent = 2
x = 186
y = 131
cardtype = "Cavalry"
connections = [1, 8, 9, 11]

[[countries]]
id = 11
name = "Pankow"
continent = 2
x = 239
y = 98
cardtype = "Infantry"
connections = [1, 2, 8, 10, 12, 14, 13]

[[countries]]
id = 12
name = "Buch"
continent = 2
x = 290
y = 48
cardtype = "Cannon"
connections = [11, 14]

[[countries]]
id = 13
name = "Weißensee"
continent = 2
x = 275
y = 138
cardtype = "Cavalry"
connections = [2, 11, 14, 15]

[[countries]]
id = 14
name = "Wartenberg"
continent = 2
x = 287
y = 94
cardtype = "Infantry"
connections = [11, 12, 13, 15]

[[countries]]
id = 15
name = "Hohenschönhausen"
continent = 3
x = 317
y = 151
cardtype = "Cannon"
connections = [2, 13, 14, 16, 20]

[[countries]]
id = 16
name = "Marzahn"
continent = 3
x = 351
y = 161
cardtype = "Cavalry"
connections = [15, 17, 19, 20, 18]

[[countries]]
id = 17
name = "Hönow"
continent = 3
x = 388
y = 176
cardtype = "Infantry"
connections = [16, 18]

[[countries]]
id = 18
name = "Hellersdorf"
continent = 3
x = 379
y = 227
cardtype = "Cannon"
connections = [16, 17, 19, 21]

[[countries]]
id = 19
name = "Wuhletal"
continent = 3
x = 349
y = 211
cardtype = "Cavalry"
connections = [16, 18, 21, 20]

[[countries]]
id = 20
name = "Lichtenberg"
continent = 3
x = 317
y = 216
cardtype = "Infantry"
connections = [2, 3, 15, 16, 19, 21, 28]

[[countries]]
id = 21
name = "Schöneweide"
continent = 4
x = 368
y = 263
cardtype = "Cannon"
connections = [18, 19, 20, 22, 23, 29, 28]

[[countries]]
id = 22
name = "Straußberg"
continent = 4
x = 437
y = 266
cardtype = "Cavalry"
connections = [21, 23]

[[countries]]
id = 23
name = "Köpenick"
continent = 4
x = 429
y = 326
cardtype = "Infantry"
connections = [21, 22, 24, 25, 29]

[[countries]]
id = 24
name = "Schönefeld"
continent = 4
x = 437
y = 367
cardtype = "Cannon"
connections = [23, 25]

[[countries]]
id = 25
name = "Rudow"
continent = 4
x = 344
y = 320
cardtype = "Cavalry"
connections = [23, 24, 26, 29]

[[countries]]
id = 26
name = "Britz"
continent = 4
x = 310
y = 320
cardtype = "Infantry"
connections = [25, 27, 29]

[[countries]]
id = 27
name = "Neukölln"
continent = 4
x = 268
y = 257
cardtype = "Cannon"
connections = [4, 26, 28, 29, 31, 32]

[[countries]]
id = 28
name = "Köllnische_Heide"
continent = 4
x = 296
y = 241
cardtype = "Cavalry"
connections = [3, 4, 20, 21, 27, 29]

[[countries]]
id = 29
name = "Treptow"
continent = 4
x = 319
y = 284
cardtype = "Infantry"
connections = [21, 23, 25, 26, 27, 28]

[[countries]]
id = 30
name = "Schöneberg"
continent = 5
x = 205
y = 247
cardtype = "Cannon"
connections = [4, 5, 31, 33, 37]

[[countries]]
id = 31
name = "Tempelhof"
continent = 5
x = 231
y = 266
cardtype = "Cavalry"
connections = [4, 27, 30, 32, 33]

[[countries]]
id = 32
name = "Marienfelde"
continent = 5
x = 230
y = 323
cardtype = "Infantry"
connections = [27, 31, 33]

[[countries]]
id = 33
name = "Steglitz"
continent = 5
x = 186
y = 293
cardtype = "Cannon"
connections = [30, 31, 32, 34, 37]

[[countries]]
id = 34
name = "Zehlendorf"
continent = 5
x = 132
y = 285
cardtype = "Cavalry"
connections = [33, 35, 37, 36]

[[countries]]
id = 35
name = "Wannsee"
continent = 5
x = 52
y = 322
cardtype = "Infantry"
connections = [34, 36]

[[countries]]
id = 36
name = "Kladow"
continent = 6
x = 67
y = 251
cardtype = "Cannon"
connections = [34, 35, 37, 39]

[[countries]]
id = 37
name = "Wilmersdorf"
continent = 6
x = 156
y = 239
cardtype = "Cavalry"
connections = [30, 33, 34, 36, 38, 39]

[[countries]]
id = 38
name = "Charlottenburg"
continent = 6
x = 161
y = 197
cardtype = "Infantry"
connections = [1, 5, 9, 37, 39]

[[countries]]
id = 39
name = "Spandau"
continent = 6
x = 82
y = 186
cardtype = "Cannon"
connections = [9, 36, 37, 38, 40]

[[countries]]
id = 40
name = "Staaken"
continent = 6
x = 73
y = 134
cardtype = "Cavalry"
connections = [8, 9, 39]
