[info]
name = "unknown"
nb_wildcards = 3

[[continents]]
id = 1
name = "Head"
bonus = 7
color = "red"

[[continents]]
id = 2
name = "Chuck"
bonus = 4
color = "red"

[[continents]]
id = 3
name = "Brisket"
bonus = 2
color = "yellow"

[[continents]]
id = 4
name = "FrontShank"
bonus = 4
color = "yellow"

[[continents]]
id = 5
name = "Rib"
bonus = 4
color = "red"

[[continents]]
id = 6
name = "Plate"
bonus = 2
color = "yellow"

[[continents]]
id = 7
name = "ShortLoin"
bonus = 3
color = "green"

[[continents]]
id = 8
name = "Flank"
bonus = 2
color = "green"

[[continents]]
id = 9
name = "Sirloin"
bonus = 5
color = "green"

[[continents]]
id = 10
name = "Round"
bonus = 4
color = "blue"

[[continents]]
id = 11
name = "BackShank"
bonus = 4
color = "blue"

[[continents]]
id = 12
name = "Tail"
bonus = 4
color = "blue"

[[countries]]
id = 1
name = "Neck"
continent = 1
x = 91
y = 27
cardtype = "Infantry"
connections = [2, 5, 6, 8]

[[countries]]
id = 2
name = "Poll"
continent = 1
x = 64
y = 12
cardtype = "Cannon"
connections = [1, 3, 4]

[[countries]]
id = 3
name = "Ear"
continent = 1
x = 41
y = 26
cardtype = "Cavalry"
connections = [2, 4]

[[countries]]
id = 4
name = "Bridge"
continent = 1
x = 40
y = 46
cardtype = "Infantry"
connections = [2, 3, 5]

[[countries]]
id = 5
name = "Muzzle"
continent = 1
x = 49
y = 62
cardtype = "Cannon"
connections = [1, 4, 6]

[[countries]]
id = 6
name = "Jaw"
continent = 1
x = 96
y = 68
cardtype = "Cavalry"
connections = [1, 5, 7, 8]

[[countries]]
id = 7
name = "Throat"
continent = 1
x = 102
y = 91
cardtype = "Infantry"
connections = [6, 8, 10]

[[countries]]
id = 8
name = "GroundBeef"
continent = 2
x = 128
y = 50
cardtype = "Cannon"
connections = [1, 6, 7, 9, 10]

[[countries]]
id = 9
name = "ChuckRoast"
continent = 2
x = 170
y = 55
cardtype = "Cavalry"
connections = [8, 10, 11, 18]

[[countries]]
id = 10
name = "ShoulderRoast"
continent = 2
x = 142
y = 109
cardtype = "Infantry"
connections = [7, 8, 9, 11, 12]

[[countries]]
id = 11
name = "ArmRoast"
continent = 2
x = 186
y = 113
cardtype = "Cannon"
connections = [9, 10, 12, 18, 21]

[[countries]]
id = 12
name = "Stew"
continent = 3
x = 163
y = 148
cardtype = "Cavalry"
connections = [10, 11, 13, 22]

[[countries]]
id = 13
name = "Brisket"
continent = 3
x = 168
y = 172
cardtype = "Infantry"
connections = [12, 14, 23]

[[countries]]
id = 14
name = "FrontShank"
continent = 4
x = 179
y = 206
cardtype = "Cannon"
connections = [13, 15]

[[countries]]
id = 15
name = "FrontHock"
continent = 4
x = 180
y = 242
cardtype = "Cavalry"
connections = [14, 16]

[[countries]]
id = 16
name = "FrontPastern"
continent = 4
x = 188
y = 263
cardtype = "Infantry"
connections = [15, 17]

[[countries]]
id = 17
name = "FrontHoof"
continent = 4
x = 178
y = 281
cardtype = "Cannon"
connections = [16]

[[countries]]
id = 18
name = "RibRoasts"
continent = 5
x = 216
y = 75
cardtype = "Cavalry"
connections = [9, 11, 19, 21]

[[countries]]
id = 19
name = "RibSteaks"
continent = 5
x = 246
y = 75
cardtype = ""
connections = [18, 20, 21]

[[countries]]
id = 20
name = "RibEye"
continent = 5
x = 283
y = 75
cardtype = ""
connections = [19, 21, 24]

[[countries]]
id = 21
name = "SpareRibs"
continent = 5
x = 249
y = 123
cardtype = ""
connections = [11, 18, 19, 20, 22, 24]

[[countries]]
id = 22
name = "ShortRibs"
continent = 6
x = 250
y = 148
cardtype = ""
connections = [12, 21, 23, 27]

[[countries]]
id = 23
name = "SkirtSteak"
continent = 6
x = 249
y = 171
cardtype = ""
connections = [13, 22, 28]

[[countries]]
id = 24
name = "Club"
continent = 7
x = 325
y = 51
cardtype = ""
connections = [20, 21, 25, 27, 29, 30]

[[countries]]
id = 25
name = "TBone"
continent = 7
x = 335
y = 106
cardtype = ""
connections = [24, 26, 27, 30]

[[countries]]
id = 26
name = "Porterhouse"
continent = 7
x = 357
y = 104
cardtype = ""
connections = [25, 27, 30, 31, 32]

[[countries]]
id = 27
name = "FlankSteak"
continent = 8
x = 333
y = 150
cardtype = ""
connections = [22, 24, 25, 26, 28, 32, 33]

[[countries]]
id = 28
name = "LondonBroil"
continent = 8
x = 323
y = 179
cardtype = ""
connections = [23, 27]

[[countries]]
id = 29
name = "Sirloin"
continent = 9
x = 384
y = 43
cardtype = ""
connections = [24, 30, 34]

[[countries]]
id = 30
name = "Tenderloin"
continent = 9
x = 376
y = 65
cardtype = ""
connections = [24, 25, 26, 29, 31, 34, 35]

[[countries]]
id = 31
name = "Toploin"
continent = 9
x = 394
y = 78
cardtype = ""
connections = [26, 30, 33, 35]

[[countries]]
id = 32
name = "Bottomloin"
continent = 9
x = 395
y = 111
cardtype = ""
connections = [26, 27, 31, 33, 36]

[[countries]]
id = 33
name = "Tip"
continent = 9
x = 410
y = 142
cardtype = ""
connections = [27, 32, 36]

[[countries]]
id = 34
name = "RumpRoast"
continent = 10
x = 431
y = 40
cardtype = ""
connections = [29, 30, 35, 42]

[[countries]]
id = 35
name = "TopRound"
continent = 10
x = 452
y = 69
cardtype = ""
connections = [30, 31, 34, 36, 37]

[[countries]]
id = 36
name = "BottomRound"
continent = 10
x = 443
y = 129
cardtype = ""
connections = [32, 33, 35, 37, 38]

[[countries]]
id = 37
name = "Heel"
continent = 10
x = 469
y = 109
cardtype = ""
connections = [35, 36]

[[countries]]
id = 38
name = "BackShank"
continent = 11
x = 449
y = 182
cardtype = ""
connections = [36, 39]

[[countries]]
id = 39
name = "BackHock"
continent = 11
x = 460
y = 226
cardtype = ""
connections = [38, 40]

[[countries]]
id = 40
name = "BackPastern"
continent = 11
x = 464
y = 253
cardtype = ""
connections = [39, 41]

[[countries]]
id = 41
name = "BackHoof"
continent = 11
x = 455
y = 272
cardtype = ""
connections = [40]

[[countries]]
id = 42
name = "Tailhead"
continent = 12
x = 468
y = 26
cardtype = ""
connections = [34, 43]

[[countries]]
id = 43
name = "UpperTail"
continent = 12
x = 492
y = 64
cardtype = ""
connections = [42, 44]

[[countries]]
id = 44
name = "LowerTail"
continent = 12
x = 494
y = 112
cardtype = ""
connections = [43, 45]

[[countries]]
id = 45
name = "Switch"
continent = 12
x = 489
y = 167
cardtype = ""
connections = [44]
