[info]
name = "unknown"
nb_wildcards = 4

[[continents]]
id = 1
name = "Oberstufenpavillon"
bonus = 5
color = "white"

[[continents]]
id = 2
name = "Sporthalle/Mensa/Froum"
bonus = 5
color = "white"

[[continents]]
id = 3
name = "Erdkunde/Musik/Kunst/Technik/5erund6er_-_Pavillon"
bonus = 5
color = "white"

[[continents]]
id = 4
name = "Miteelstufenpavillon"
bonus = 5
color = "white"

[[continents]]
id = 5
name = "Naturwisschaftspavillon"
bonus = 5
color = "white"

[[continents]]
id = 6
name = "Lehrerpavillon"
bonus = 5
color = "white"

[[countries]]
id = 1
name = "Oberstufenraum"
continent = 1
x = 209
y = 144
cardtype = "Cavalry"
connections = [2, 16]

[[countries]]
id = 2
name = "Toilette"
continent = 1
x = 237
y = 142
cardtype = "Infantry"
connections = [3, 1, 16, 14, 12, 9]

[[countries]]
id = 3
name = "Computerraum"
continent = 1
x = 290
y = 134
cardtype = "Cannon"
connections = [2]

[[countries]]
id = 4
name = "Sporthalle"
continent = 2
x = 429
y = 151
cardtype = "Cavalry"
connections = [5]

[[countries]]
id = 5
name = "Mensa"
continent = 2
x = 410
y = 206
cardtype = "Infantry"
connections = [16, 14, 12, 9, 6, 4]

[[countries]]
id = 6
name = "Forum"
continent = 2
x = 317
y = 205
cardtype = "Cannon"
connections = [5]

[[countries]]
id = 7
name = "Erdkunde/Kunst"
continent = 3
x = 458
y = 260
cardtype = "Cavalry"
connections = [9]

[[countries]]
id = 8
name = "Musik"
continent = 3
x = 545
y = 225
cardtype = "Infantry"
connections = [9]

[[countries]]
id = 9
name = "Toilette"
continent = 3
x = 521
y = 248
cardtype = "Cannon"
connections = [16, 14, 12, 5, 2, 8, 7]

[[countries]]
id = 10
name = "6"
continent = 4
x = 288
y = 308
cardtype = "Cavalry"
connections = [12]

[[countries]]
id = 11
name = "7"
continent = 4
x = 388
y = 278
cardtype = "Infantry"
connections = [12]

[[countries]]
id = 12
name = "Toillette_"
continent = 4
x = 334
y = 291
cardtype = "Cannon"
connections = [16, 14, 5, 2, 9, 11, 10]

[[countries]]
id = 13
name = "Chemie/Bio"
continent = 5
x = 173
y = 336
cardtype = "Cavalry"
connections = [14]

[[countries]]
id = 14
name = "Physik/Computerraum(Neu)"
continent = 5
x = 131
y = 275
cardtype = "Infantry"
connections = [16, 12, 13, 5, 2, 9]

[[countries]]
id = 15
name = "Bibliothek"
continent = 6
x = 104
y = 223
cardtype = "Cannon"
connections = [16]

[[countries]]
id = 16
name = "Lehrerzimmer/Sekreteriat"
continent = 6
x = 174
y = 195
cardtype = "Cavalry"
connections = [2, 15, 14, 12, 5, 9, 1]
