[info]
name = "unknown"
nb_wildcards = 4

[[continents]]
id = 1
name = "Lugor"
bonus = 6
color = "blue"

[[continents]]
id = 2
name = "Jakohl"
bonus = 6
color = "red"

[[continents]]
id = 3
name = "Jidoor"
bonus = 7
color = "green"

[[continents]]
id = 4
name = "Veldt"
bonus = 5
color = "magenta"

[[continents]]
id = 5
name = "Burmecia"
bonus = 4
color = "orange"

[[continents]]
id = 6
name = "Daliras"
bonus = 4
color = "white"

[[countries]]
id = 1
name = "Atlacia"
continent = 1
x = 47
y = 95
cardtype = "Infantry"
connections = [2, 43]

[[countries]]
id = 2
name = "Grador"
continent = 1
x = 108
y = 107
cardtype = "Cavalry"
connections = [1, 3, 5, 6]

[[countries]]
id = 3
name = "Malvar"
continent = 1
x = 88
y = 157
cardtype = "Cannon"
connections = [2, 4, 5, 41]

[[countries]]
id = 4
name = "Deomar"
continent = 1
x = 130
y = 178
cardtype = "Infantry"
connections = [3, 5, 10, 11]

[[countries]]
id = 5
name = "Iltzar"
continent = 1
x = 169
y = 128
cardtype = "Cavalry"
connections = [2, 3, 4, 6, 8, 9, 10]

[[countries]]
id = 6
name = "North_Iltzar"
continent = 1
x = 147
y = 87
cardtype = "Cannon"
connections = [2, 5, 7, 8]

[[countries]]
id = 7
name = "Reogar"
continent = 1
x = 230
y = 63
cardtype = "Infantry"
connections = [6, 8, 30]

[[countries]]
id = 8
name = "Cerobi"
continent = 1
x = 220
y = 109
cardtype = "Cavalry"
connections = [5, 7, 9, 6]

[[countries]]
id = 9
name = "Korces"
continent = 1
x = 240
y = 179
cardtype = "Cannon"
connections = [5, 8, 10, 23, 24]

[[countries]]
id = 10
name = "Decimus"
continent = 1
x = 194
y = 180
cardtype = "Infantry"
connections = [4, 5, 9, 12]

[[countries]]
id = 11
name = "Carmen"
continent = 5
x = 109
y = 261
cardtype = "Cavalry"
connections = [4, 12, 14]

[[countries]]
id = 12
name = "Cergon"
continent = 5
x = 155
y = 260
cardtype = "Cannon"
connections = [10, 11, 16]

[[countries]]
id = 13
name = "Ceste"
continent = 5
x = 73
y = 343
cardtype = "Infantry"
connections = [14]

[[countries]]
id = 14
name = "Reems"
continent = 5
x = 133
y = 323
cardtype = "Cavalry"
connections = [11, 13, 15, 16]

[[countries]]
id = 15
name = "Festgon"
continent = 5
x = 153
y = 363
cardtype = "Cannon"
connections = [14, 16, 17]

[[countries]]
id = 16
name = "Westerra"
continent = 5
x = 183
y = 324
cardtype = "Infantry"
connections = [12, 14, 15, 17]

[[countries]]
id = 17
name = "Infiras"
continent = 6
x = 264
y = 388
cardtype = "Cavalry"
connections = [15, 16, 18]

[[countries]]
id = 18
name = "Sectiras"
continent = 6
x = 367
y = 388
cardtype = "Cannon"
connections = [17, 19, 20]

[[countries]]
id = 19
name = "Derfiras"
continent = 6
x = 452
y = 388
cardtype = "Infantry"
connections = [18, 20]

[[countries]]
id = 20
name = "Beofiras"
continent = 6
x = 402
y = 356
cardtype = "Cavalry"
connections = [18, 19, 21]

[[countries]]
id = 21
name = "Managar"
continent = 3
x = 387
y = 291
cardtype = "Cannon"
connections = [20, 22, 26]

[[countries]]
id = 22
name = "Eobar"
continent = 3
x = 364
y = 237
cardtype = "Infantry"
connections = [21, 23, 24, 25, 26]

[[countries]]
id = 23
name = "Eastoria"
continent = 3
x = 300
y = 241
cardtype = "Cavalry"
connections = [9, 22, 24]

[[countries]]
id = 24
name = "Miniria"
continent = 3
x = 340
y = 199
cardtype = "Cannon"
connections = [9, 22, 23, 25]

[[countries]]
id = 25
name = "Lepterra"
continent = 3
x = 403
y = 191
cardtype = "Infantry"
connections = [22, 24, 26, 27, 28, 29]

[[countries]]
id = 26
name = "Leomar"
continent = 3
x = 414
y = 264
cardtype = "Cavalry"
connections = [21, 22, 25, 27]

[[countries]]
id = 27
name = "Elmar"
continent = 3
x = 426
y = 228
cardtype = "Cannon"
connections = [25, 26, 28]

[[countries]]
id = 28
name = "Centralia"
continent = 3
x = 468
y = 230
cardtype = "Infantry"
connections = [25, 27, 29]

[[countries]]
id = 29
name = "Ilmaria"
continent = 3
x = 491
y = 183
cardtype = "Cavalry"
connections = [25, 28, 34, 39, 40]

[[countries]]
id = 30
name = "Distonia"
continent = 4
x = 338
y = 51
cardtype = "Cannon"
connections = [7, 31, 32]

[[countries]]
id = 31
name = "Fernatia"
continent = 4
x = 369
y = 73
cardtype = "Infantry"
connections = [30, 32, 33]

[[countries]]
id = 32
name = "Betonia"
continent = 4
x = 387
y = 30
cardtype = "Cavalry"
connections = [30, 31, 33, 34]

[[countries]]
id = 33
name = "Geomar"
continent = 4
x = 413
y = 72
cardtype = "Cannon"
connections = [31, 32, 34]

[[countries]]
id = 34
name = "Eltagea"
continent = 4
x = 450
y = 52
cardtype = "Infantry"
connections = [29, 32, 33, 35, 36]

[[countries]]
id = 35
name = "Menagea"
continent = 4
x = 488
y = 30
cardtype = "Cavalry"
connections = [34, 36]

[[countries]]
id = 36
name = "Sormagea"
continent = 4
x = 499
y = 74
cardtype = "Cannon"
connections = [34, 35, 37, 38]

[[countries]]
id = 37
name = "Nortmas"
continent = 2
x = 594
y = 58
cardtype = "Infantry"
connections = [36, 38, 43]

[[countries]]
id = 38
name = "Eastmas"
continent = 2
x = 584
y = 120
cardtype = "Cavalry"
connections = [36, 37, 39, 42, 43]

[[countries]]
id = 39
name = "Miromar"
continent = 2
x = 556
y = 166
cardtype = "Cannon"
connections = [29, 38, 40, 42]

[[countries]]
id = 40
name = "Gorisar"
continent = 2
x = 593
y = 214
cardtype = "Infantry"
connections = [29, 39, 41, 42]

[[countries]]
id = 41
name = "Venucar"
continent = 2
x = 643
y = 214
cardtype = "Cavalry"
connections = [3, 40, 42, 43]

[[countries]]
id = 42
name = "Eolitar"
continent = 2
x = 604
y = 163
cardtype = "Cannon"
connections = [38, 39, 40, 41, 43]

[[countries]]
id = 43
name = "Sinorias"
continent = 2
x = 627
y = 122
cardtype = "Infantry"
connections = [1, 37, 38, 41, 42]
