[info]
name = "unknown"

[files]
pic = "austria_map.png"
map = "austria_map.gif"
crd = "austria_map.cards"

[[continents]]
id = 1
name = "Vorarlberg"
bonus = 1
color = "blue"

[[continents]]
id = 2
name = "Tirol"
bonus = 3
color = "blue"

[[continents]]
id = 3
name = "Salzburg"
bonus = 3
color = "yellow"

[[continents]]
id = 4
name = "Upper-Austria"
bonus = 5
color = "blue"

[[continents]]
id = 5
name = "Lower-Austria"
bonus = 4
color = "green"

[[continents]]
id = 6
name = "Vienna"
bonus = 2
color = "red"

[[continents]]
id = 7
name = "Burgenland"
bonus = 1
color = "red"

[[continents]]
id = 8
name = "Styria"
bonus = 7
color = "green"

[[continents]]
id = 9
name = "Carinthia"
bonus = 4
color = "yellow"

[[countries]]
id = 1
name = "Bregenz"
continent = 1
x = 38
y = 284
connections = [2, 3]

[[countries]]
id = 2
name = "Feldkirch"
continent = 1
x = 14
y = 295
connections = [1, 3]

[[countries]]
id = 3
name = "Bludenz"
continent = 1
x = 33
y = 318
connections = [1, 2, 4, 5]

[[countries]]
id = 4
name = "Reutte"
continent = 2
x = 99
y = 279
connections = [3, 5, 6, 7]

[[countries]]
id = 5
name = "Landeck"
continent = 2
x = 89
y = 334
connections = [3, 4, 6]

[[countries]]
id = 6
name = "Imst"
continent = 2
x = 115
y = 312
connections = [4, 5, 7]

[[countries]]
id = 7
name = "Innsbruck"
continent = 2
x = 161
y = 318
connections = [4, 6, 8]

[[countries]]
id = 8
name = "Schwaz"
continent = 2
x = 206
y = 324
connections = [7, 9, 11]

[[countries]]
id = 9
name = "Kitzbühel"
continent = 2
x = 234
y = 277
connections = [8, 11]

[[countries]]
id = 10
name = "Osttirol"
continent = 2
x = 260
y = 351
connections = [11, 51]

[[countries]]
id = 11
name = "Pinzgau"
continent = 3
x = 284
y = 302
connections = [8, 9, 10, 12, 51]

[[countries]]
id = 12
name = "Pongau"
continent = 3
x = 332
y = 295
connections = [11, 13, 14, 18, 42, 51]

[[countries]]
id = 13
name = "Lungau"
continent = 3
x = 367
y = 323
connections = [12, 42, 43, 51]

[[countries]]
id = 14
name = "Tennengau"
continent = 3
x = 326
y = 259
connections = [12, 15, 18]

[[countries]]
id = 15
name = "Salzburg"
continent = 3
x = 318
y = 225
connections = [14, 16, 17, 18]

[[countries]]
id = 16
name = "Braunau"
continent = 4
x = 320
y = 192
connections = [15, 17, 19]

[[countries]]
id = 17
name = "Vöcklabruck"
continent = 4
x = 354
y = 214
connections = [15, 16, 18, 19, 52]

[[countries]]
id = 18
name = "Gmunden"
continent = 4
x = 382
y = 232
connections = [12, 14, 15, 17, 22, 42, 52]

[[countries]]
id = 19
name = "Innviertel"
continent = 4
x = 352
y = 162
connections = [16, 17, 21, 52]

[[countries]]
id = 20
name = "Linz"
continent = 4
x = 421
y = 183
connections = [21, 22, 25, 52]

[[countries]]
id = 21
name = "Mühlviertel"
continent = 4
x = 451
y = 161
connections = [19, 20, 23, 24, 25, 52]

[[countries]]
id = 22
name = "Traunviertel"
continent = 4
x = 424
y = 226
connections = [18, 20, 25, 42, 52]

[[countries]]
id = 23
name = "Waldviertel"
continent = 5
x = 500
y = 100
connections = [21, 24, 26, 27]

[[countries]]
id = 24
name = "Zwettl"
continent = 5
x = 492
y = 137
connections = [21, 23, 25, 26]

[[countries]]
id = 25
name = "Mostviertel"
continent = 5
x = 479
y = 206
connections = [20, 21, 22, 24, 26, 28, 41, 42]

[[countries]]
id = 26
name = "St._Pölten"
continent = 5
x = 549
y = 175
connections = [23, 24, 25, 27, 28, 32]

[[countries]]
id = 27
name = "Weinviertel"
continent = 5
x = 610
y = 136
connections = [23, 26, 28, 30, 32, 33]

[[countries]]
id = 28
name = "Industrieviertel"
continent = 5
x = 573
y = 233
connections = [25, 26, 27, 30, 31, 32, 34, 35, 37, 40, 41]

[[countries]]
id = 29
name = "Innere_Stadt"
continent = 6
x = 134
y = 168
connections = [30, 31, 32, 33]

[[countries]]
id = 30
name = "Donaustadt"
continent = 6
x = 182
y = 146
connections = [27, 28, 29, 31, 33]

[[countries]]
id = 31
name = "Favoriten"
continent = 6
x = 137
y = 215
connections = [28, 29, 30, 32]

[[countries]]
id = 32
name = "Hietzing"
continent = 6
x = 68
y = 190
connections = [26, 27, 28, 29, 31, 33]

[[countries]]
id = 33
name = "Döbling"
continent = 6
x = 104
y = 141
connections = [27, 29, 30, 32]

[[countries]]
id = 34
name = "Eisenstadt"
continent = 7
x = 645
y = 222
connections = [28, 35]

[[countries]]
id = 35
name = "Südburgenland"
continent = 7
x = 598
y = 304
connections = [28, 34, 36, 37]

[[countries]]
id = 36
name = "Radkersburg"
continent = 8
x = 563
y = 361
connections = [35, 37, 38, 40]

[[countries]]
id = 37
name = "Fürstenfeld"
continent = 8
x = 568
y = 304
connections = [28, 35, 36, 40]

[[countries]]
id = 38
name = "Leibnitz"
continent = 8
x = 533
y = 372
connections = [36, 39, 40]

[[countries]]
id = 39
name = "Deutschlandsberg"
continent = 8
x = 504
y = 369
connections = [38, 40, 44, 46]

[[countries]]
id = 40
name = "Graz"
continent = 8
x = 530
y = 320
connections = [28, 36, 37, 38, 39, 41, 44, 45]

[[countries]]
id = 41
name = "Bruck_an_der_Mur"
continent = 8
x = 518
y = 268
connections = [25, 28, 40, 42, 45]

[[countries]]
id = 42
name = "Liezen"
continent = 8
x = 397
y = 283
connections = [12, 13, 18, 22, 25, 41, 43, 44, 45]

[[countries]]
id = 43
name = "Murau"
continent = 8
x = 412
y = 321
connections = [13, 42, 44, 47, 50, 51]

[[countries]]
id = 44
name = "Judenburg"
continent = 8
x = 458
y = 327
connections = [39, 40, 42, 43, 45, 46, 47]

[[countries]]
id = 45
name = "Leoben"
continent = 8
x = 474
y = 296
connections = [40, 41, 42, 44]

[[countries]]
id = 46
name = "Wolfsberg"
continent = 9
x = 473
y = 360
connections = [39, 44, 47, 48]

[[countries]]
id = 47
name = "St._Veit"
continent = 9
x = 428
y = 360
connections = [43, 44, 46, 48, 49, 50]

[[countries]]
id = 48
name = "Völkermarkt"
continent = 9
x = 457
y = 397
connections = [46, 47, 49]

[[countries]]
id = 49
name = "Klagenfurt"
continent = 9
x = 423
y = 400
connections = [47, 48, 50]

[[countries]]
id = 50
name = "Villach"
continent = 9
x = 380
y = 390
connections = [43, 47, 49, 51]

[[countries]]
id = 51
name = "Spittal"
continent = 9
x = 323
y = 368
connections = [10, 11, 12, 13, 43, 50]

[[countries]]
id = 52
name = "Hausruckviertel"
continent = 4
x = 382
y = 181
connections = [17, 18, 19, 20, 21, 22]
