[info]
name = "unknown"
nb_wildcards = 4

[[continents]]
id = 1
name = "Lääne_Eesti"
bonus = 5
color = "green"

[[continents]]
id = 2
name = "Kesk_Eesti"
bonus = 3
color = "yellow"

[[continents]]
id = 3
name = "Ida_Eesti"
bonus = 3
color = "blue"

[[continents]]
id = 4
name = "Lõuna_Eesti"
bonus = 4
color = "red"

[[countries]]
id = 1
name = "Hiiumaa"
continent = 1
x = 167
y = 172
cardtype = "Infantry"
connections = [2, 3]

[[countries]]
id = 2
name = "Saaremaa"
continent = 1
x = 155
y = 247
cardtype = "Cannon"
connections = [1, 3, 4]

[[countries]]
id = 3
name = "Läänemaa"
continent = 1
x = 250
y = 170
cardtype = "Infantry"
connections = [2, 1, 4, 5, 7]

[[countries]]
id = 4
name = "Pärnumaa"
continent = 1
x = 316
y = 234
cardtype = "Infantry"
connections = [2, 3, 5, 6, 11]

[[countries]]
id = 5
name = "Raplamaa"
continent = 2
x = 332
y = 137
cardtype = "Cavalry"
connections = [3, 4, 6, 7]

[[countries]]
id = 6
name = "Järvamaa"
continent = 2
x = 404
y = 142
cardtype = "Cavalry"
connections = [5, 4, 7, 8, 10, 11]

[[countries]]
id = 7
name = "Harjumaa"
continent = 2
x = 349
y = 79
cardtype = "Cavalry"
connections = [3, 5, 6, 8]

[[countries]]
id = 8
name = "Lääne_Virumaa"
continent = 3
x = 463
y = 128
cardtype = "Cannon"
connections = [6, 7, 9, 10]

[[countries]]
id = 9
name = "Ida_virumaa"
continent = 3
x = 536
y = 117
cardtype = "Cannon"
connections = [8, 10]

[[countries]]
id = 10
name = "Jõgevamaa"
continent = 3
x = 469
y = 175
cardtype = "Cannon"
connections = [6, 8, 9, 11, 12]

[[countries]]
id = 11
name = "Viljandimaa"
continent = 1
x = 395
y = 252
cardtype = "Cavalry"
connections = [4, 6, 10, 12, 13]

[[countries]]
id = 12
name = "Tartumaa"
continent = 4
x = 484
y = 252
cardtype = "Cannon"
connections = [10, 11, 13, 14]

[[countries]]
id = 13
name = "Valgamaa"
continent = 4
x = 445
y = 313
cardtype = "Infantry"
connections = [11, 12, 14, 15]

[[countries]]
id = 14
name = "Põlvamaa"
continent = 4
x = 527
y = 271
cardtype = "Infantry"
connections = [12, 13, 15]

[[countries]]
id = 15
name = "Võrumaa"
continent = 4
x = 515
y = 348
cardtype = "Cannon"
connections = [13, 14]
