[info]
name = "unknown"
nb_wildcards = 10

[[continents]]
id = 1
name = "Rear_Section"
bonus = 2
color = "#bf889f"

[[continents]]
id = 2
name = "Engineering"
bonus = 5
color = "#f39438"

[[continents]]
id = 3
name = "Tactical"
bonus = 3
color = "#9f5576"

[[continents]]
id = 4
name = "Shuttle_Bay"
bonus = 4
color = "#3333ff"

[[continents]]
id = 5
name = "Bridge"
bonus = 4
color = "#fd7c2e"

[[continents]]
id = 6
name = "Quarters"
bonus = 4
color = "#ffcbb5"

[[countries]]
id = 1
name = "Shuttle_Bay"
continent = 4
x = 360
y = 152
cardtype = "Cavalry"
connections = [2, 4, 5, 23, 24, 30, 39, 32]

[[countries]]
id = 2
name = "Shuttle_1"
continent = 4
x = 205
y = 144
cardtype = "Infantry"
connections = [1, 3, 4]

[[countries]]
id = 3
name = "Shuttle_2"
continent = 4
x = 133
y = 340
cardtype = "Cannon"
connections = [5, 2, 4]

[[countries]]
id = 4
name = "Shuttle_3"
continent = 4
x = 503
y = 70
cardtype = "Cavalry"
connections = [1, 2, 3]

[[countries]]
id = 5
name = "Shuttle_4"
continent = 4
x = 471
y = 339
cardtype = "Infantry"
connections = [1, 3, 38]

[[countries]]
id = 6
name = "R1"
continent = 1
x = 38
y = 204
cardtype = "Cannon"
connections = [7, 10]

[[countries]]
id = 7
name = "R2"
continent = 1
x = 72
y = 185
cardtype = "Cavalry"
connections = [6, 10, 8]

[[countries]]
id = 8
name = "R3"
continent = 1
x = 138
y = 184
cardtype = "Infantry"
connections = [11, 7, 9]

[[countries]]
id = 9
name = "R4"
continent = 1
x = 163
y = 205
cardtype = "Cannon"
connections = [11, 14, 8]

[[countries]]
id = 10
name = "R5"
continent = 1
x = 81
y = 220
cardtype = "Cavalry"
connections = [6, 7, 12, 11, 13]

[[countries]]
id = 11
name = "R6"
continent = 1
x = 138
y = 221
cardtype = "Infantry"
connections = [10, 9, 8, 13, 12]

[[countries]]
id = 12
name = "R7"
continent = 1
x = 64
y = 253
cardtype = "Cannon"
connections = [10, 13, 11]

[[countries]]
id = 13
name = "R8"
continent = 1
x = 88
y = 259
cardtype = "Cavalry"
connections = [12, 10, 19, 11, 15]

[[countries]]
id = 14
name = "R9"
continent = 1
x = 219
y = 205
cardtype = "Infantry"
connections = [9]

[[countries]]
id = 15
name = "R10"
continent = 1
x = 175
y = 259
cardtype = "Cannon"
connections = [17, 19, 18, 13]

[[countries]]
id = 16
name = "E1"
continent = 2
x = 250
y = 274
cardtype = "Cavalry"
connections = [17, 18, 21, 20]

[[countries]]
id = 17
name = "E2"
continent = 2
x = 232
y = 250
cardtype = "Infantry"
connections = [15, 19, 18, 16, 20, 23]

[[countries]]
id = 18
name = "E3"
continent = 2
x = 194
y = 276
cardtype = "Cannon"
connections = [17, 15, 16]

[[countries]]
id = 19
name = "E4"
continent = 2
x = 190
y = 234
cardtype = "Cavalry"
connections = [13, 17, 15]

[[countries]]
id = 20
name = "E5"
continent = 2
x = 261
y = 249
cardtype = "Infantry"
connections = [17, 16, 22, 21, 23, 27]

[[countries]]
id = 21
name = "E6"
continent = 2
x = 286
y = 273
cardtype = "Cannon"
connections = [16, 22, 20]

[[countries]]
id = 22
name = "E7"
continent = 2
x = 307
y = 260
cardtype = "Cavalry"
connections = [20, 21]

[[countries]]
id = 23
name = "E8"
continent = 2
x = 284
y = 189
cardtype = "Infantry"
connections = [17, 20, 26, 1]

[[countries]]
id = 24
name = "T1"
continent = 3
x = 343
y = 191
cardtype = "Cannon"
connections = [25, 1, 30]

[[countries]]
id = 25
name = "T2"
continent = 3
x = 336
y = 212
cardtype = "Cavalry"
connections = [27, 26, 24]

[[countries]]
id = 26
name = "T3"
continent = 3
x = 314
y = 212
cardtype = "Infantry"
connections = [27, 25, 23]

[[countries]]
id = 27
name = "T4"
continent = 3
x = 319
y = 232
cardtype = "Cannon"
connections = [20, 26, 25]

[[countries]]
id = 28
name = "B1"
continent = 5
x = 575
y = 148
cardtype = "Cavalry"
connections = [34, 40, 33]

[[countries]]
id = 29
name = "B2"
continent = 5
x = 445
y = 169
cardtype = "Infantry"
connections = [33, 37, 32, 30, 31]

[[countries]]
id = 30
name = "B3"
continent = 5
x = 414
y = 167
cardtype = "Cannon"
connections = [39, 38, 31, 32, 1, 24, 29]

[[countries]]
id = 31
name = "B4"
continent = 5
x = 444
y = 131
cardtype = "Cavalry"
connections = [33, 30, 32, 29]

[[countries]]
id = 32
name = "B5"
continent = 5
x = 417
y = 140
cardtype = "Infantry"
connections = [30, 31, 29, 1]

[[countries]]
id = 33
name = "B6"
continent = 5
x = 469
y = 135
cardtype = "Cannon"
connections = [28, 31, 29]

[[countries]]
id = 34
name = "Q1"
continent = 6
x = 567
y = 178
cardtype = "Cavalry"
connections = [35, 28, 40]

[[countries]]
id = 35
name = "Q2"
continent = 6
x = 542
y = 181
cardtype = "Infantry"
connections = [34, 37, 36]

[[countries]]
id = 36
name = "Q3"
continent = 6
x = 502
y = 190
cardtype = "Cannon"
connections = [37, 35]

[[countries]]
id = 37
name = "Q4"
continent = 6
x = 488
y = 167
cardtype = "Cavalry"
connections = [29, 38, 36, 35]

[[countries]]
id = 38
name = "Q5"
continent = 6
x = 451
y = 196
cardtype = "Infantry"
connections = [37, 30, 5]

[[countries]]
id = 39
name = "Q6"
continent = 6
x = 405
y = 187
cardtype = "Cannon"
connections = [30, 1, 18, 14]

[[countries]]
id = 40
name = "Q7"
continent = 6
x = 640
y = 169
cardtype = "Cavalry"
connections = [34, 28]
