[info]
name = "unknown"

[files]
pic = "europass_pic.png"
map = "europass_map.gif"
crd = "europass.cards"

[[continents]]
id = 1
name = "Skandinavien"
bonus = 4
color = "yellow"

[[continents]]
id = 2
name = "Westeuropa"
bonus = 5
color = "red"

[[continents]]
id = 3
name = "Mittelmeer"
bonus = 3
color = "blue"

[[continents]]
id = 4
name = "Mitteleuropa"
bonus = 4
color = "orange"

[[continents]]
id = 5
name = "Balkan"
bonus = 3
color = "green"

[[continents]]
id = 6
name = "Kleinasien"
bonus = 3
color = "magenta"

[[continents]]
id = 7
name = "Russland"
bonus = 7
color = "red"

[[countries]]
id = 1
name = "Reykjavik"
continent = 1
x = 27
y = 30
connections = [2]

[[countries]]
id = 2
name = "Ostisland"
continent = 1
x = 76
y = 41
connections = [1, 51, 3]

[[countries]]
id = 3
name = "Aberdeen"
continent = 2
x = 121
y = 143
connections = [2, 4, 49]

[[countries]]
id = 4
name = "Glasgow"
continent = 2
x = 121
y = 172
connections = [3, 8, 5]

[[countries]]
id = 5
name = "Nordirland"
continent = 2
x = 98
y = 179
connections = [4, 6]

[[countries]]
id = 6
name = "Dublin"
continent = 2
x = 72
y = 184
connections = [5, 7]

[[countries]]
id = 7
name = "Suedirland"
continent = 2
x = 69
y = 206
connections = [6, 14]

[[countries]]
id = 8
name = "Leeds"
continent = 2
x = 136
y = 190
connections = [4, 9, 10]

[[countries]]
id = 9
name = "Wales"
continent = 2
x = 115
y = 209
connections = [8, 10, 11]

[[countries]]
id = 10
name = "England"
continent = 2
x = 154
y = 213
connections = [8, 9, 11]

[[countries]]
id = 11
name = "London"
continent = 2
x = 126
y = 230
connections = [9, 10, 27, 25]

[[countries]]
id = 12
name = "Lisabon"
continent = 3
x = 14
y = 360
connections = [13, 16, 18]

[[countries]]
id = 13
name = "Porto"
continent = 3
x = 41
y = 338
connections = [12, 14, 16]

[[countries]]
id = 14
name = "Baskenland"
continent = 3
x = 67
y = 313
connections = [7, 25, 21, 15, 16, 13]

[[countries]]
id = 15
name = "Barcelona"
continent = 3
x = 142
y = 342
connections = [14, 21, 17, 16]

[[countries]]
id = 16
name = "Madrid"
continent = 3
x = 81
y = 352
connections = [12, 13, 14, 15, 18]

[[countries]]
id = 17
name = "Ballearen"
continent = 3
x = 154
y = 380
connections = [18, 15, 19]

[[countries]]
id = 18
name = "Suedspanien"
continent = 3
x = 56
y = 391
connections = [12, 16, 17]

[[countries]]
id = 19
name = "Sardinien"
continent = 3
x = 216
y = 382
connections = [17, 20, 31]

[[countries]]
id = 20
name = "Korsika"
continent = 2
x = 212
y = 346
connections = [22, 34, 19]

[[countries]]
id = 21
name = "Suedfrankreich"
continent = 2
x = 147
y = 320
connections = [14, 15, 22, 23]

[[countries]]
id = 22
name = "Marseille"
continent = 2
x = 188
y = 325
connections = [20, 21, 23, 24, 26, 36]

[[countries]]
id = 23
name = "Zentral-Frankreich"
continent = 2
x = 146
y = 294
connections = [21, 22, 26, 25]

[[countries]]
id = 24
name = "Turin"
continent = 3
x = 219
y = 311
connections = [22, 36, 35, 34]

[[countries]]
id = 25
name = "Normandie"
continent = 2
x = 103
y = 258
connections = [11, 14, 23, 26, 27]

[[countries]]
id = 26
name = "Paris"
continent = 2
x = 168
y = 269
connections = [25, 27, 28, 36, 22, 23]

[[countries]]
id = 27
name = "Nordfrankreich"
continent = 2
x = 156
y = 242
connections = [25, 26, 28, 29, 11]

[[countries]]
id = 28
name = "Elsaß-Lothringen"
continent = 2
x = 199
y = 268
connections = [26, 27, 29, 39, 38, 36]

[[countries]]
id = 29
name = "Belgien"
continent = 2
x = 183
y = 238
connections = [27, 28, 30, 39]

[[countries]]
id = 30
name = "Niederlande"
continent = 2
x = 189
y = 213
connections = [29, 39, 41]

[[countries]]
id = 31
name = "Sizilien"
continent = 3
x = 266
y = 397
connections = [19, 32, 77]

[[countries]]
id = 32
name = "Sueditalien"
continent = 3
x = 306
y = 370
connections = [31, 33, 74]

[[countries]]
id = 33
name = "Rom"
continent = 3
x = 272
y = 345
connections = [32, 34]

[[countries]]
id = 34
name = "Vatikan"
continent = 3
x = 248
y = 328
connections = [33, 20, 24, 35]

[[countries]]
id = 35
name = "Venedig"
continent = 3
x = 251
y = 301
connections = [24, 36, 37, 68, 34]

[[countries]]
id = 36
name = "Schweiz"
continent = 4
x = 214
y = 287
connections = [22, 24, 26, 28, 37, 38, 35]

[[countries]]
id = 37
name = "Oesterreich"
continent = 4
x = 277
y = 279
connections = [35, 36, 38, 65, 66, 67, 68]

[[countries]]
id = 38
name = "Bayern"
continent = 4
x = 247
y = 264
connections = [28, 39, 40, 65, 37, 36]

[[countries]]
id = 39
name = "Nordrhein-Westfalen"
continent = 4
x = 215
y = 243
connections = [28, 29, 30, 41, 40, 38]

[[countries]]
id = 40
name = "Sachsen"
continent = 4
x = 253
y = 235
connections = [38, 39, 41, 42, 62, 63, 65]

[[countries]]
id = 41
name = "Niedersachsen"
continent = 4
x = 226
y = 215
connections = [30, 39, 40, 42]

[[countries]]
id = 42
name = "Berlin"
continent = 4
x = 260
y = 209
connections = [40, 41, 43, 44, 61, 62]

[[countries]]
id = 43
name = "Dänemark"
continent = 1
x = 225
y = 172
connections = [49, 44, 42]

[[countries]]
id = 44
name = "Kopenhagen"
continent = 1
x = 251
y = 176
connections = [42, 43, 45]

[[countries]]
id = 45
name = "Malmoe"
continent = 1
x = 277
y = 167
connections = [44, 46, 57]

[[countries]]
id = 46
name = "Stockholm"
continent = 1
x = 288
y = 125
connections = [45, 49, 50, 47, 55]

[[countries]]
id = 47
name = "Zentralschweden"
continent = 1
x = 277
y = 91
connections = [46, 50, 48]

[[countries]]
id = 48
name = "Nordschweden"
continent = 1
x = 305
y = 54
connections = [47, 50, 51, 53]

[[countries]]
id = 49
name = "Oslo"
continent = 1
x = 207
y = 131
connections = [3, 50, 46, 43]

[[countries]]
id = 50
name = "Trondheim"
continent = 1
x = 242
y = 78
connections = [49, 46, 47, 48, 51]

[[countries]]
id = 51
name = "Tromsoe"
continent = 1
x = 265
y = 32
connections = [50, 48, 52, 53, 2]

[[countries]]
id = 52
name = "Hammerfest"
continent = 1
x = 311
y = 11
connections = [51, 53, 91]

[[countries]]
id = 53
name = "Nordfinnland"
continent = 1
x = 341
y = 37
connections = [48, 51, 52, 91, 90, 54]

[[countries]]
id = 54
name = "Zentralfinnland"
continent = 1
x = 356
y = 77
connections = [53, 90, 89, 55]

[[countries]]
id = 55
name = "Helsinki"
continent = 1
x = 331
y = 109
connections = [54, 89, 56, 46]

[[countries]]
id = 56
name = "Estland"
continent = 7
x = 351
y = 132
connections = [55, 89, 88, 57]

[[countries]]
id = 57
name = "Lettland"
continent = 7
x = 338
y = 155
connections = [56, 88, 87, 58, 45]

[[countries]]
id = 58
name = "Littauen"
continent = 7
x = 353
y = 177
connections = [57, 87, 86, 60, 59]

[[countries]]
id = 59
name = "Ostpreussen"
continent = 4
x = 324
y = 186
connections = [58, 60, 61]

[[countries]]
id = 60
name = "Warschau"
continent = 4
x = 336
y = 213
connections = [59, 58, 86, 64, 63, 62, 61]

[[countries]]
id = 61
name = "Pommern"
continent = 4
x = 298
y = 192
connections = [59, 60, 62, 42]

[[countries]]
id = 62
name = "Posen"
continent = 4
x = 298
y = 215
connections = [61, 60, 63, 40, 42]

[[countries]]
id = 63
name = "Schlesien"
continent = 4
x = 307
y = 235
connections = [62, 60, 64, 66, 65, 40]

[[countries]]
id = 64
name = "Krakau"
continent = 4
x = 345
y = 238
connections = [60, 85, 66, 63]

[[countries]]
id = 65
name = "Tschechien"
continent = 4
x = 280
y = 250
connections = [63, 66, 37, 38, 40]

[[countries]]
id = 66
name = "Slowakei"
continent = 4
x = 325
y = 261
connections = [63, 64, 85, 67, 37, 65]

[[countries]]
id = 67
name = "Ungarn"
continent = 4
x = 327
y = 280
connections = [66, 85, 84, 71, 69, 68, 37]

[[countries]]
id = 68
name = "Slowenien"
continent = 5
x = 284
y = 289
connections = [35, 37, 67, 69]

[[countries]]
id = 69
name = "Kroatien"
continent = 5
x = 287
y = 319
connections = [68, 67, 71, 70, 72]

[[countries]]
id = 70
name = "Bosnien"
continent = 5
x = 316
y = 315
connections = [69, 71, 72]

[[countries]]
id = 71
name = "Belgrad"
continent = 5
x = 341
y = 304
connections = [67, 84, 82, 81, 72, 70, 69]

[[countries]]
id = 72
name = "Serbien"
continent = 5
x = 342
y = 327
connections = [69, 70, 71, 81, 73, 74]

[[countries]]
id = 73
name = "Montenegro"
continent = 5
x = 365
y = 339
connections = [72, 81, 75, 74]

[[countries]]
id = 74
name = "Albanien"
continent = 6
x = 333
y = 358
connections = [72, 73, 75, 76, 32]

[[countries]]
id = 75
name = "Thesaloniki"
continent = 6
x = 387
y = 353
connections = [74, 73, 81, 80, 76]

[[countries]]
id = 76
name = "Athen"
continent = 6
x = 363
y = 396
connections = [74, 75, 77]

[[countries]]
id = 77
name = "Kreta"
continent = 6
x = 427
y = 415
connections = [31, 76, 78]

[[countries]]
id = 78
name = "Izmir"
continent = 6
x = 467
y = 385
connections = [77, 79, 110, 109]

[[countries]]
id = 79
name = "Bosporus"
continent = 6
x = 440
y = 355
connections = [80, 110, 78]

[[countries]]
id = 80
name = "Istanbul"
continent = 6
x = 433
y = 339
connections = [75, 81, 79]

[[countries]]
id = 81
name = "Bulgarien"
continent = 5
x = 398
y = 326
connections = [82, 80, 75, 73, 72, 71]

[[countries]]
id = 82
name = "Bukarest"
continent = 5
x = 385
y = 307
connections = [81, 71, 84, 83]

[[countries]]
id = 83
name = "Bessarabien"
continent = 5
x = 400
y = 287
connections = [82, 84, 85, 102, 103]

[[countries]]
id = 84
name = "Siebenbuergen"
continent = 5
x = 363
y = 284
connections = [67, 85, 83, 82, 71]

[[countries]]
id = 85
name = "West-Ukraine"
continent = 7
x = 381
y = 240
connections = [86, 97, 102, 103, 83, 84, 67, 66, 64]

[[countries]]
id = 86
name = "Brest"
continent = 7
x = 377
y = 205
connections = [58, 60, 85, 97, 87]

[[countries]]
id = 87
name = "Minsk"
continent = 7
x = 399
y = 181
connections = [57, 58, 86, 97, 96, 88]

[[countries]]
id = 88
name = "Moskau"
continent = 7
x = 440
y = 146
connections = [56, 57, 87, 89, 90, 93, 94, 95, 96]

[[countries]]
id = 89
name = "Petersburg"
continent = 7
x = 394
y = 114
connections = [54, 55, 56, 88, 90]

[[countries]]
id = 90
name = "Onega"
continent = 7
x = 414
y = 72
connections = [53, 54, 88, 89, 91, 93]

[[countries]]
id = 91
name = "Murmansk"
continent = 7
x = 406
y = 19
connections = [52, 53, 90]

[[countries]]
id = 92
name = "Nordrussland"
continent = 7
x = 534
y = 15
connections = [93]

[[countries]]
id = 93
name = "Archangelsk"
continent = 7
x = 506
y = 66
connections = [88, 90, 92, 94]

[[countries]]
id = 94
name = "Saratov"
continent = 7
x = 561
y = 96
connections = [88, 93, 95]

[[countries]]
id = 95
name = "Kasachstan"
continent = 7
x = 606
y = 137
connections = [88, 94, 96]

[[countries]]
id = 96
name = "Voronez"
continent = 7
x = 521
y = 174
connections = [87, 88, 95, 97, 98]

[[countries]]
id = 97
name = "Kiew"
continent = 7
x = 430
y = 229
connections = [85, 86, 87, 96, 98, 99, 100, 102]

[[countries]]
id = 98
name = "Wolgograd"
continent = 7
x = 569
y = 224
connections = [96, 97, 99, 100, 104]

[[countries]]
id = 99
name = "Ostukraine"
continent = 7
x = 496
y = 226
connections = [97, 98, 100]

[[countries]]
id = 100
name = "Sewastopol"
continent = 7
x = 483
y = 251
connections = [97, 98, 99, 101, 102]

[[countries]]
id = 101
name = "Krim"
continent = 7
x = 476
y = 295
connections = [100, 102, 104, 110]

[[countries]]
id = 102
name = "Odessa"
continent = 7
x = 441
y = 279
connections = [85, 97, 100, 101, 83, 103]

[[countries]]
id = 103
name = "Moldawien"
continent = 7
x = 415
y = 264
connections = [83, 85, 102]

[[countries]]
id = 104
name = "Kaukasus"
continent = 7
x = 576
y = 262
connections = [98, 101, 105, 106]

[[countries]]
id = 105
name = "Georgien"
continent = 7
x = 571
y = 288
connections = [104, 106, 107, 108]

[[countries]]
id = 106
name = "Aserbeischan"
continent = 7
x = 648
y = 291
connections = [104, 105, 107, 108]

[[countries]]
id = 107
name = "Armenien"
continent = 7
x = 614
y = 315
connections = [105, 106, 108]

[[countries]]
id = 108
name = "Kurdistan"
continent = 6
x = 573
y = 332
connections = [105, 106, 107, 109, 110]

[[countries]]
id = 109
name = "Konya"
continent = 6
x = 535
y = 364
connections = [78, 108, 110]

[[countries]]
id = 110
name = "Ankara"
continent = 6
x = 491
y = 329
connections = [78, 79, 101, 108, 109]
