[info]
name = "unknown"
nb_wildcards = 2

[[continents]]
id = 1
name = "Free_States"
bonus = 8
color = "blue"

[[continents]]
id = 2
name = "Border_States"
bonus = 4
color = "green"

[[continents]]
id = 3
name = "Confederate_States"
bonus = 6
color = "red"

[[continents]]
id = 4
name = "Western_States_and_Territories"
bonus = 4
color = "yellow"

[[countries]]
id = 1
name = "Maine"
continent = 1
x = 602
y = 60
cardtype = "Infantry"
connections = [2]

[[countries]]
id = 2
name = "New_Hampshire"
continent = 1
x = 595
y = 95
cardtype = "Cannon"
connections = [1, 3, 4]

[[countries]]
id = 3
name = "Vermont"
continent = 1
x = 569
y = 72
cardtype = "Infantry"
connections = [2, 7, 4]

[[countries]]
id = 4
name = "Massachusetts"
continent = 1
x = 608
y = 112
cardtype = "Infantry"
connections = [2, 3, 5, 6, 7]

[[countries]]
id = 5
name = "Rhode_Island"
continent = 1
x = 619
y = 133
cardtype = "Cavalry"
connections = [4, 6]

[[countries]]
id = 6
name = "Connecticut"
continent = 1
x = 584
y = 130
cardtype = "Cavalry"
connections = [4, 5, 7]

[[countries]]
id = 7
name = "New_York"
continent = 1
x = 551
y = 108
cardtype = "Cavalry"
connections = [3, 4, 6, 8, 9]

[[countries]]
id = 8
name = "New_Jersey"
continent = 1
x = 575
y = 152
cardtype = "Cannon"
connections = [7, 9, 21]

[[countries]]
id = 9
name = "Pennsylvania"
continent = 1
x = 531
y = 144
cardtype = "Cannon"
connections = [7, 8, 20, 21, 19, 10]

[[countries]]
id = 10
name = "Ohio"
continent = 1
x = 478
y = 162
cardtype = "Cannon"
connections = [9, 11, 18, 12, 19]

[[countries]]
id = 11
name = "Indiana"
continent = 1
x = 443
y = 168
cardtype = "Cavalry"
connections = [10, 18, 16, 12]

[[countries]]
id = 12
name = "Michigan"
continent = 1
x = 441
y = 89
cardtype = "Cannon"
connections = [10, 11, 13]

[[countries]]
id = 13
name = "Wisconsin"
continent = 1
x = 401
y = 111
cardtype = "Infantry"
connections = [12, 14, 15, 16]

[[countries]]
id = 14
name = "Minnesota"
continent = 1
x = 349
y = 92
cardtype = "Infantry"
connections = [13, 36, 15]

[[countries]]
id = 15
name = "Iowa"
continent = 1
x = 360
y = 145
cardtype = "Cannon"
connections = [13, 14, 35, 17, 16]

[[countries]]
id = 16
name = "Illinois"
continent = 1
x = 408
y = 173
cardtype = "Cannon"
connections = [11, 13, 15, 18, 17]

[[countries]]
id = 17
name = "Missouri"
continent = 2
x = 373
y = 196
cardtype = "Cavalry"
connections = [15, 16, 34, 35, 33, 30, 28, 18]

[[countries]]
id = 18
name = "Kentucky"
continent = 2
x = 464
y = 201
cardtype = "Cavalry"
connections = [10, 11, 16, 17, 28, 19, 22]

[[countries]]
id = 19
name = "West_Virginia"
continent = 2
x = 501
y = 181
cardtype = "Infantry"
connections = [9, 18, 22, 20, 10]

[[countries]]
id = 20
name = "Maryland"
continent = 2
x = 543
y = 171
cardtype = "Cavalry"
connections = [9, 19, 22, 21]

[[countries]]
id = 21
name = "Delaware"
continent = 2
x = 598
y = 173
cardtype = "Infantry"
connections = [8, 9, 20]

[[countries]]
id = 22
name = "Virginia"
continent = 3
x = 534
y = 193
cardtype = "Infantry"
connections = [18, 19, 20, 23, 28]

[[countries]]
id = 23
name = "North_Carolina"
continent = 3
x = 531
y = 221
cardtype = "Cavalry"
connections = [22, 24, 25, 28]

[[countries]]
id = 24
name = "South_Carolina"
continent = 3
x = 516
y = 250
cardtype = "Cannon"
connections = [23, 25]

[[countries]]
id = 25
name = "Georgia"
continent = 3
x = 487
y = 272
cardtype = "Cannon"
connections = [23, 24, 26, 27, 28]

[[countries]]
id = 26
name = "Florida"
continent = 3
x = 516
y = 327
cardtype = "Infantry"
connections = [25, 27]

[[countries]]
id = 27
name = "Alabama"
continent = 3
x = 447
y = 273
cardtype = "Cannon"
connections = [25, 26, 29, 28]

[[countries]]
id = 28
name = "Tennessee"
continent = 3
x = 444
y = 229
cardtype = "Cavalry"
connections = [17, 18, 22, 23, 25, 27, 29, 30]

[[countries]]
id = 29
name = "Mississippi"
continent = 3
x = 411
y = 275
cardtype = "Cavalry"
connections = [27, 28, 30, 31]

[[countries]]
id = 30
name = "Arkansas"
continent = 3
x = 375
y = 250
cardtype = "Infantry"
connections = [17, 28, 29, 31, 33, 32]

[[countries]]
id = 31
name = "Louisiana"
continent = 3
x = 378
y = 306
cardtype = "Cannon"
connections = [29, 30, 32]

[[countries]]
id = 32
name = "Texas"
continent = 3
x = 300
y = 301
cardtype = "Infantry"
connections = [30, 31, 45, 33]

[[countries]]
id = 33
name = "Unorganized_Territory"
continent = 4
x = 322
y = 241
cardtype = "Cannon"
connections = [17, 30, 32, 34, 46, 45]

[[countries]]
id = 34
name = "Kansas"
continent = 4
x = 310
y = 197
cardtype = "Cavalry"
connections = [17, 33, 46, 35]

[[countries]]
id = 35
name = "Nebraska_Territory"
continent = 4
x = 298
y = 154
cardtype = "Infantry"
connections = [15, 17, 34, 46, 36]

[[countries]]
id = 36
name = "Dakota_Territory"
continent = 4
x = 266
y = 112
cardtype = "Cannon"
connections = [14, 35, 37, 38, 43, 46]

[[countries]]
id = 37
name = "Montana_Territory"
continent = 4
x = 203
y = 68
cardtype = "Infantry"
connections = [36, 38]

[[countries]]
id = 38
name = "Idaho_Territory"
continent = 4
x = 152
y = 106
cardtype = "Cavalry"
connections = [36, 37, 39, 40, 42, 43]

[[countries]]
id = 39
name = "Washington_Territory"
continent = 4
x = 101
y = 41
cardtype = "Cavalry"
connections = [38, 40]

[[countries]]
id = 40
name = "Oregon"
continent = 4
x = 84
y = 89
cardtype = "Cavalry"
connections = [38, 39, 42, 41]

[[countries]]
id = 41
name = "California"
continent = 4
x = 71
y = 193
cardtype = "Cannon"
connections = [40, 42, 44]

[[countries]]
id = 42
name = "Nevada"
continent = 4
x = 104
y = 155
cardtype = "Infantry"
connections = [38, 40, 41, 43, 44]

[[countries]]
id = 43
name = "Utah_Territory"
continent = 4
x = 161
y = 169
cardtype = "Infantry"
connections = [36, 38, 42, 46, 44]

[[countries]]
id = 44
name = "Arizona_Territory"
continent = 4
x = 153
y = 241
cardtype = "Cavalry"
connections = [41, 42, 43, 45]

[[countries]]
id = 45
name = "New_Mexico_Territory"
continent = 4
x = 219
y = 248
cardtype = "Cannon"
connections = [32, 33, 44, 46]

[[countries]]
id = 46
name = "Colorado_Territory"
continent = 4
x = 230
y = 185
cardtype = "Infantry"
connections = [33, 34, 35, 36, 43, 45]
