[info]
name = "unknown"
nb_wildcards = 2

[[continents]]
id = 1
name = "Merzig"
bonus = 3
color = "yellow"

[[continents]]
id = 2
name = "Neunkirchen"
bonus = 4
color = "red"

[[continents]]
id = 3
name = "Saarbruecken"
bonus = 4
color = "blue"

[[continents]]
id = 4
name = "Saarlouis"
bonus = 6
color = "orange"

[[continents]]
id = 5
name = "Saarpfalz"
bonus = 3
color = "green"

[[continents]]
id = 6
name = "Sankt-Wendel"
bonus = 4
color = "magenta"

[[countries]]
id = 1
name = "Perl"
continent = 1
x = 77
y = 120
cardtype = "Infantry"
connections = [2]

[[countries]]
id = 2
name = "Mettlach"
continent = 1
x = 149
y = 121
cardtype = "Cannon"
connections = [1, 3, 4]

[[countries]]
id = 3
name = "Merzig"
continent = 1
x = 194
y = 160
cardtype = "Infantry"
connections = [4, 6, 5, 2]

[[countries]]
id = 4
name = "Losheim-am-See"
continent = 1
x = 255
y = 120
cardtype = "Infantry"
connections = [2, 3, 5, 14, 15, 16]

[[countries]]
id = 5
name = "Beckingen"
continent = 1
x = 262
y = 176
cardtype = "Cavalry"
connections = [3, 4, 6, 8, 13, 14]

[[countries]]
id = 6
name = "Rehlingen-Siersburg"
continent = 4
x = 203
y = 220
cardtype = "Cavalry"
connections = [3, 5, 7, 8]

[[countries]]
id = 7
name = "Wallerfangen"
continent = 4
x = 208
y = 258
cardtype = "Cavalry"
connections = [6, 8, 9, 10]

[[countries]]
id = 8
name = "Dillingen"
continent = 4
x = 256
y = 220
cardtype = "Cannon"
connections = [6, 5, 7, 10, 12, 13]

[[countries]]
id = 9
name = "Ueberherrn"
continent = 4
x = 240
y = 300
cardtype = "Cannon"
connections = [7, 10, 24]

[[countries]]
id = 10
name = "Saarlouis"
continent = 4
x = 260
y = 265
cardtype = "Cannon"
connections = [7, 8, 9, 11, 12, 22, 23, 24]

[[countries]]
id = 11
name = "Ensdorf"
continent = 4
x = 283
y = 270
cardtype = "Cavalry"
connections = [10, 22, 23]

[[countries]]
id = 12
name = "Saarwellingen"
continent = 4
x = 315
y = 228
cardtype = "Cannon"
connections = [8, 10, 13, 19, 20, 21, 22]

[[countries]]
id = 13
name = "Nalbach"
continent = 4
x = 290
y = 200
cardtype = "Infantry"
connections = [5, 8, 12, 14, 19]

[[countries]]
id = 14
name = "Schmelz"
continent = 4
x = 313
y = 166
cardtype = "Infantry"
connections = [4, 5, 13, 15, 18, 19]

[[countries]]
id = 15
name = "Wadern"
continent = 1
x = 342
y = 84
cardtype = "Cannon"
connections = [4, 14, 16, 17, 18]

[[countries]]
id = 16
name = "Weisskirchen"
continent = 1
x = 290
y = 80
cardtype = "Cannon"
connections = [4, 15]

[[countries]]
id = 17
name = "Nonnweiler"
continent = 6
x = 390
y = 46
cardtype = "Cavalry"
connections = [15, 18, 38]

[[countries]]
id = 18
name = "Tholey"
continent = 6
x = 405
y = 127
cardtype = "Cavalry"
connections = [14, 15, 19, 35, 36, 37, 38, 17]

[[countries]]
id = 19
name = "Lebach"
continent = 4
x = 355
y = 166
cardtype = "Infantry"
connections = [12, 13, 14, 18, 35, 20]

[[countries]]
id = 20
name = "Heusweiler"
continent = 3
x = 371
y = 234
cardtype = "Cavalry"
connections = [12, 19, 21, 27, 28, 29, 34, 35]

[[countries]]
id = 21
name = "Puettlingen"
continent = 3
x = 347
y = 277
cardtype = "Infantry"
connections = [12, 20, 22, 23, 25, 27, 28]

[[countries]]
id = 22
name = "Schwallbach"
continent = 4
x = 311
y = 265
cardtype = "Infantry"
connections = [10, 11, 12, 21, 23]

[[countries]]
id = 23
name = "Bous"
continent = 4
x = 300
y = 285
cardtype = "Cavalry"
connections = [10, 11, 21, 22, 24, 25]

[[countries]]
id = 24
name = "Wadgassen"
continent = 4
x = 283
y = 309
cardtype = "Cannon"
connections = [9, 23, 25, 10]

[[countries]]
id = 25
name = "Voelklingen"
continent = 3
x = 276
y = 343
cardtype = "Cannon"
connections = [21, 23, 24, 26, 27]

[[countries]]
id = 26
name = "Grossrosseln"
continent = 3
x = 310
y = 356
cardtype = "Infantry"
connections = [25]

[[countries]]
id = 27
name = "Saarbruecken"
continent = 3
x = 415
y = 323
cardtype = "Cannon"
connections = [20, 21, 25, 28, 29, 30, 45, 46, 47]

[[countries]]
id = 28
name = "Riegelsberg"
continent = 3
x = 376
y = 262
cardtype = "Cavalry"
connections = [20, 21, 27]

[[countries]]
id = 29
name = "Quierschied"
continent = 3
x = 420
y = 250
cardtype = "Cavalry"
connections = [20, 27, 30, 31, 32]

[[countries]]
id = 30
name = "Sulzbach"
continent = 3
x = 443
y = 267
cardtype = "Infantry"
connections = [27, 29, 31, 44, 45]

[[countries]]
id = 31
name = "Friedrichstal"
continent = 3
x = 455
y = 244
cardtype = "Cannon"
connections = [29, 30, 32, 33, 44, 43]

[[countries]]
id = 32
name = "Merchweiler"
continent = 2
x = 442
y = 224
cardtype = "Infantry"
connections = [29, 31, 33, 34]

[[countries]]
id = 33
name = "Schiffweiler"
continent = 2
x = 475
y = 217
cardtype = "Cannon"
connections = [31, 32, 42, 43, 34]

[[countries]]
id = 34
name = "Illingen"
continent = 2
x = 432
y = 193
cardtype = "Cavalry"
connections = [20, 32, 33, 35, 36, 42]

[[countries]]
id = 35
name = "Eppelborn"
continent = 2
x = 385
y = 188
cardtype = "Infantry"
connections = [19, 20, 34, 36, 18]

[[countries]]
id = 36
name = "Marpingen"
continent = 6
x = 438
y = 150
cardtype = "Cannon"
connections = [18, 34, 35, 37, 41, 42]

[[countries]]
id = 37
name = "Obertal"
continent = 6
x = 453
y = 98
cardtype = "Infantry"
connections = [18, 36, 38, 40, 41]

[[countries]]
id = 38
name = "Nohfelden"
continent = 6
x = 440
y = 56
cardtype = "Cavalry"
connections = [17, 18, 37, 39, 40]

[[countries]]
id = 39
name = "Freisen"
continent = 6
x = 533
y = 81
cardtype = "Cavalry"
connections = [38, 40, 41]

[[countries]]
id = 40
name = "Namborn"
continent = 6
x = 492
y = 101
cardtype = "Cavalry"
connections = [37, 38, 39, 41]

[[countries]]
id = 41
name = "Sankt-Wendel"
continent = 6
x = 502
y = 145
cardtype = "Cannon"
connections = [36, 37, 39, 40, 42]

[[countries]]
id = 42
name = "Ottweiler"
continent = 2
x = 514
y = 180
cardtype = "Infantry"
connections = [33, 34, 36, 41, 43, 52]

[[countries]]
id = 43
name = "Neunkirchen"
continent = 2
x = 510
y = 230
cardtype = "Infantry"
connections = [31, 33, 42, 44, 50, 52, 45]

[[countries]]
id = 44
name = "Spiessen-Elversberg"
continent = 2
x = 490
y = 256
cardtype = "Infantry"
connections = [30, 31, 43, 45]

[[countries]]
id = 45
name = "Sankt-Ingbert"
continent = 5
x = 480
y = 290
cardtype = "Cavalry"
connections = [27, 30, 44, 47, 49, 50, 43]

[[countries]]
id = 46
name = "Kleinblittersdorf"
continent = 3
x = 445
y = 380
cardtype = "Cavalry"
connections = [27, 47]

[[countries]]
id = 47
name = "Mandelbachtal"
continent = 5
x = 494
y = 345
cardtype = "Cannon"
connections = [27, 45, 46, 48, 49]

[[countries]]
id = 48
name = "Gersheim"
continent = 5
x = 533
y = 380
cardtype = "Cannon"
connections = [47, 49]

[[countries]]
id = 49
name = "Blieskastel"
continent = 5
x = 545
y = 310
cardtype = "Cavalry"
connections = [45, 47, 48, 50, 51]

[[countries]]
id = 50
name = "Kirkel"
continent = 5
x = 545
y = 268
cardtype = "Cavalry"
connections = [43, 45, 49, 51, 52]

[[countries]]
id = 51
name = "Homburg"
continent = 5
x = 598
y = 242
cardtype = "Infantry"
connections = [49, 50, 52]

[[countries]]
id = 52
name = "Bexbach"
continent = 5
x = 549
y = 217
cardtype = "Infantry"
connections = [42, 43, 50, 51]
