[info]
name = "Risk II Map"
nb_wildcards = 2

[[continents]]
id = 1
name = "North-America"
bonus = 6
color = "yellow"

[[continents]]
id = 2
name = "South-America"
bonus = 4
color = "red"

[[continents]]
id = 3
name = "Europe"
bonus = 6
color = "blue"

[[continents]]
id = 4
name = "Africa"
bonus = 5
color = "orange"

[[continents]]
id = 5
name = "Asia"
bonus = 8
color = "green"

[[continents]]
id = 6
name = "Australia"
bonus = 4
color = "magenta"

[[countries]]
id = 1
name = "Alaska"
continent = 1
x = 44
y = 83
cardtype = "Infantry"
connections = [2, 3, 38]

[[countries]]
id = 2
name = "North-West-Territory"
continent = 1
x = 134
y = 83
cardtype = "Cannon"
connections = [1, 3, 7, 44]

[[countries]]
id = 3
name = "Alberta"
continent = 1
x = 114
y = 105
cardtype = "Infantry"
connections = [1, 2, 7, 4]

[[countries]]
id = 4
name = "Western-United-States"
continent = 1
x = 125
y = 151
cardtype = "Infantry"
connections = [3, 7, 5, 9, 43]

[[countries]]
id = 5
name = "Central-America"
continent = 1
x = 127
y = 203
cardtype = "Cavalry"
connections = [4, 9, 10]

[[countries]]
id = 6
name = "Greenland"
continent = 1
x = 264
y = 42
cardtype = "Cavalry"
connections = [8, 14, 46, 44]

[[countries]]
id = 7
name = "Ontario"
continent = 1
x = 162
y = 109
cardtype = "Cavalry"
connections = [2, 3, 4, 8, 9, 44]

[[countries]]
id = 8
name = "Quebec"
continent = 1
x = 208
y = 109
cardtype = "Cannon"
connections = [6, 7, 9, 44]

[[countries]]
id = 9
name = "Eastern-United-States"
continent = 1
x = 156
y = 166
cardtype = "Cannon"
connections = [4, 5, 7, 8]

[[countries]]
id = 10
name = "Venezuela"
continent = 2
x = 142
y = 249
cardtype = "Cannon"
connections = [5, 11, 12]

[[countries]]
id = 11
name = "Peru"
continent = 2
x = 165
y = 308
cardtype = "Cavalry"
connections = [10, 12, 13]

[[countries]]
id = 12
name = "Brazil"
continent = 2
x = 202
y = 285
cardtype = "Cannon"
connections = [10, 11, 13, 21]

[[countries]]
id = 13
name = "Argentina"
continent = 2
x = 163
y = 366
cardtype = "Infantry"
connections = [11, 12, 45, 48]

[[countries]]
id = 14
name = "Iceland"
continent = 3
x = 280
y = 87
cardtype = "Infantry"
connections = [6, 17, 15]

[[countries]]
id = 15
name = "Scandinavia"
continent = 3
x = 332
y = 90
cardtype = "Cannon"
connections = [16, 18, 46, 14, 17]

[[countries]]
id = 16
name = "Ukraine"
continent = 3
x = 385
y = 109
cardtype = "Cannon"
connections = [15, 28, 30, 31, 18, 20]

[[countries]]
id = 17
name = "Great-Britain"
continent = 3
x = 286
y = 129
cardtype = "Cavalry"
connections = [14, 18, 19, 15]

[[countries]]
id = 18
name = "Northern-Europe"
continent = 3
x = 322
y = 127
cardtype = "Cavalry"
connections = [15, 16, 17, 19, 20]

[[countries]]
id = 19
name = "Western-Europe"
continent = 3
x = 288
y = 167
cardtype = "Infantry"
connections = [17, 18, 20, 21]

[[countries]]
id = 20
name = "Southern-Europe"
continent = 3
x = 333
y = 181
cardtype = "Cavalry"
connections = [16, 18, 19, 21, 22, 31]

[[countries]]
id = 21
name = "North-Africa"
continent = 4
x = 290
y = 235
cardtype = "Infantry"
connections = [12, 19, 20, 22, 23, 24]

[[countries]]
id = 22
name = "Egypt"
continent = 4
x = 341
y = 219
cardtype = "Infantry"
connections = [20, 21, 24, 31]

[[countries]]
id = 23
name = "Congo"
continent = 4
x = 334
y = 300
cardtype = "Cavalry"
connections = [21, 24, 25]

[[countries]]
id = 24
name = "East-Africa"
continent = 4
x = 360
y = 265
cardtype = "Cannon"
connections = [21, 22, 23, 25, 26, 31]

[[countries]]
id = 25
name = "South-Africa"
continent = 4
x = 335
y = 354
cardtype = "Cannon"
connections = [23, 24, 26, 45]

[[countries]]
id = 26
name = "Madagascar"
continent = 4
x = 404
y = 352
cardtype = "Infantry"
connections = [24, 25]

[[countries]]
id = 27
name = "Siberia"
continent = 5
x = 494
y = 87
cardtype = "Cannon"
connections = [28, 29, 34, 35, 36]

[[countries]]
id = 28
name = "Ural"
continent = 5
x = 449
y = 103
cardtype = "Cavalry"
connections = [16, 27, 29, 30]

[[countries]]
id = 29
name = "China"
continent = 5
x = 507
y = 181
cardtype = "Cavalry"
connections = [27, 28, 30, 32, 33, 36]

[[countries]]
id = 30
name = "Afghanistan"
continent = 5
x = 433
y = 169
cardtype = "Infantry"
connections = [16, 28, 29, 31, 32]

[[countries]]
id = 31
name = "Middle-East"
continent = 5
x = 388
y = 202
cardtype = "Cannon"
connections = [16, 22, 30, 32, 20, 24]

[[countries]]
id = 32
name = "India"
continent = 5
x = 462
y = 221
cardtype = "Infantry"
connections = [29, 30, 31, 33]

[[countries]]
id = 33
name = "Siam"
continent = 5
x = 514
y = 236
cardtype = "Cannon"
connections = [29, 32, 39]

[[countries]]
id = 34
name = "Yakutsk"
continent = 5
x = 562
y = 73
cardtype = "Cavalry"
connections = [27, 35, 38]

[[countries]]
id = 35
name = "Irkutsk"
continent = 5
x = 540
y = 116
cardtype = "Infantry"
connections = [27, 34, 36, 38]

[[countries]]
id = 36
name = "Mongolia"
continent = 5
x = 559
y = 144
cardtype = "Cannon"
connections = [29, 35, 37, 38, 27]

[[countries]]
id = 37
name = "Japan"
continent = 5
x = 620
y = 147
cardtype = "Infantry"
connections = [36, 38, 43, 47]

[[countries]]
id = 38
name = "Kamchatka"
continent = 5
x = 630
y = 82
cardtype = "Cavalry"
connections = [1, 34, 35, 36, 37]

[[countries]]
id = 39
name = "Indonesia"
continent = 6
x = 537
y = 280
cardtype = "Cavalry"
connections = [33, 41, 40, 47]

[[countries]]
id = 40
name = "New-Guinea"
continent = 6
x = 607
y = 290
cardtype = "Cavalry"
connections = [39, 41, 42]

[[countries]]
id = 41
name = "Western-Australia"
continent = 6
x = 532
y = 338
cardtype = "Cannon"
connections = [39, 40, 42]

[[countries]]
id = 42
name = "Eastern-Australia"
continent = 6
x = 593
y = 363
cardtype = "Infantry"
connections = [40, 41, 48]

[[countries]]
id = 43
name = "Hawaii"
continent = 1
x = 38
y = 168
cardtype = ""
connections = [4, 37]

[[countries]]
id = 44
name = "Oikiqtaluk"
continent = 1
x = 179
y = 49
cardtype = ""
connections = [6, 7, 8, 2]

[[countries]]
id = 45
name = "Falkland-Islands"
continent = 2
x = 188
y = 380
cardtype = ""
connections = [13, 25]

[[countries]]
id = 46
name = "Svalbard"
continent = 3
x = 373
y = 39
cardtype = ""
connections = [6, 15]

[[countries]]
id = 47
name = "Philippines"
continent = 6
x = 598
y = 215
cardtype = ""
connections = [37, 39]

[[countries]]
id = 48
name = "New-Zealand"
continent = 6
x = 640
y = 349
cardtype = ""
connections = [42, 13]
