[info]
name = "unknown"
nb_wildcards = 3

[[continents]]
id = 1
name = "Bühne"
bonus = 2
color = "white"

[[continents]]
id = 2
name = "Innenraum_Sued"
bonus = 5
color = "#ffff99"

[[continents]]
id = 3
name = "Innenraum_Nord"
bonus = 5
color = "#999900"

[[continents]]
id = 4
name = "Innenraum_Ost"
bonus = 2
color = "#ffff33"

[[continents]]
id = 5
name = "Loge_Sued"
bonus = 3
color = "#99ff99"

[[continents]]
id = 6
name = "Loge_Nord"
bonus = 3
color = "#009900"

[[continents]]
id = 7
name = "Rang_101-107"
bonus = 4
color = "#6699ff"

[[continents]]
id = 8
name = "Rang_111-117"
bonus = 4
color = "#0066cc"

[[continents]]
id = 9
name = "Rang_201-208"
bonus = 5
color = "#ff66ff"

[[continents]]
id = 10
name = "Rang_211-218"
bonus = 5
color = "#cc00cc"

[[continents]]
id = 11
name = "Rang_301-308"
bonus = 4
color = "#ff6666"

[[continents]]
id = 12
name = "Rang_311-318"
bonus = 4
color = "#cc0033"

[[continents]]
id = 13
name = "Rang_401-404"
bonus = 3
color = "#ff9966"

[[continents]]
id = 14
name = "Rang_405-408"
bonus = 3
color = "#ff9933"

[[continents]]
id = 15
name = "Rang_411-414"
bonus = 3
color = "#ff6633"

[[continents]]
id = 16
name = "Rang_415-418"
bonus = 3
color = "#cc6600"

[[continents]]
id = 17
name = "Haupteingang"
bonus = 2
color = "cyan"

[[continents]]
id = 18
name = "Westtribuenen"
bonus = 4
color = "#009999"

[[continents]]
id = 19
name = "Eingang_Nord"
bonus = 2
color = "#00ffcc"

[[continents]]
id = 20
name = "Gang_Suedost"
bonus = 6
color = "#cccccc"

[[continents]]
id = 21
name = "Gang_Suedwest"
bonus = 6
color = "#999999"

[[continents]]
id = 22
name = "Gang_Nordost"
bonus = 6
color = "#666666"

[[continents]]
id = 23
name = "Gang_Nordwest"
bonus = 6
color = "#333333"

[[continents]]
id = 24
name = "Osttribuenen"
bonus = 4
color = "red"

[[countries]]
id = 1
name = "Bühne"
continent = 1
x = 526
y = 195
cardtype = "Infantry"
connections = [7, 2, 95, 94]

[[countries]]
id = 2
name = "Parkett_Sued"
continent = 2
x = 441
y = 174
cardtype = "Infantry"
connections = [78, 7, 6, 5, 4, 3, 12, 1]

[[countries]]
id = 3
name = "Sued_1_rechts"
continent = 2
x = 488
y = 144
cardtype = "Infantry"
connections = [2, 4]

[[countries]]
id = 4
name = "Sued_1_links"
continent = 2
x = 455
y = 144
cardtype = "Cavalry"
connections = [2, 3, 5]

[[countries]]
id = 5
name = "Sued_2_rechts"
continent = 2
x = 426
y = 144
cardtype = "Cavalry"
connections = [2, 4, 6]

[[countries]]
id = 6
name = "Sued_2_links"
continent = 2
x = 396
y = 144
cardtype = "Cavalry"
connections = [2, 5]

[[countries]]
id = 7
name = "Parkett_Nord"
continent = 3
x = 441
y = 209
cardtype = "Cannon"
connections = [78, 1, 2, 10, 11, 8, 9, 13, 86]

[[countries]]
id = 8
name = "Nord_2_links"
continent = 3
x = 456
y = 242
cardtype = "Cannon"
connections = [7, 11, 10]

[[countries]]
id = 9
name = "Nord_1_links"
continent = 3
x = 395
y = 242
cardtype = "Cannon"
connections = [7, 10]

[[countries]]
id = 10
name = "Nord_2_rechts"
continent = 3
x = 426
y = 242
cardtype = "Infantry"
connections = [7, 8, 9]

[[countries]]
id = 11
name = "Nord_1_rechts"
continent = 3
x = 487
y = 242
cardtype = "Infantry"
connections = [7, 8]

[[countries]]
id = 12
name = "Ost_1"
continent = 4
x = 353
y = 167
cardtype = "Infantry"
connections = [2]

[[countries]]
id = 13
name = "Ost_2"
continent = 4
x = 354
y = 216
cardtype = "Cavalry"
connections = [7]

[[countries]]
id = 14
name = "4"
continent = 5
x = 434
y = 106
cardtype = "Cavalry"
connections = [15, 90]

[[countries]]
id = 15
name = "5"
continent = 5
x = 457
y = 106
cardtype = "Cavalry"
connections = [14, 91]

[[countries]]
id = 16
name = "14"
continent = 6
x = 457
y = 280
cardtype = "Cannon"
connections = [86, 17]

[[countries]]
id = 17
name = "15"
continent = 6
x = 434
y = 279
cardtype = "Cannon"
connections = [86, 16]

[[countries]]
id = 18
name = "101"
continent = 7
x = 342
y = 119
cardtype = "Cannon"
connections = [19, 89, 88, 32, 33]

[[countries]]
id = 19
name = "102"
continent = 7
x = 375
y = 100
cardtype = "Infantry"
connections = [18, 20, 90, 89, 33, 34]

[[countries]]
id = 20
name = "103"
continent = 7
x = 409
y = 91
cardtype = "Infantry"
connections = [21, 19, 90, 34, 35]

[[countries]]
id = 21
name = "104"
continent = 7
x = 446
y = 88
cardtype = "Infantry"
connections = [22, 20, 91, 35, 36, 90]

[[countries]]
id = 22
name = "105"
continent = 7
x = 481
y = 92
cardtype = "Cavalry"
connections = [23, 21, 91, 36, 37]

[[countries]]
id = 23
name = "106"
continent = 7
x = 517
y = 101
cardtype = "Cavalry"
connections = [24, 22, 92, 37, 38]

[[countries]]
id = 24
name = "107"
continent = 7
x = 547
y = 120
cardtype = "Cavalry"
connections = [23, 93, 38, 39]

[[countries]]
id = 25
name = "111"
continent = 8
x = 549
y = 266
cardtype = "Cannon"
connections = [26, 40, 41, 96, 97]

[[countries]]
id = 26
name = "112"
continent = 8
x = 516
y = 285
cardtype = "Cannon"
connections = [27, 25, 41, 42, 97, 98]

[[countries]]
id = 27
name = "113"
continent = 8
x = 482
y = 294
cardtype = "Cannon"
connections = [98, 28, 26, 42, 43, 86]

[[countries]]
id = 28
name = "114"
continent = 8
x = 447
y = 298
cardtype = "Infantry"
connections = [86, 29, 27, 43, 44]

[[countries]]
id = 29
name = "115"
continent = 8
x = 411
y = 295
cardtype = "Infantry"
connections = [86, 30, 28, 44, 45, 99]

[[countries]]
id = 30
name = "116"
continent = 8
x = 377
y = 285
cardtype = "Infantry"
connections = [100, 31, 29, 45, 46]

[[countries]]
id = 31
name = "117"
continent = 8
x = 342
y = 267
cardtype = "Cavalry"
connections = [30, 46, 47, 101]

[[countries]]
id = 32
name = "201"
continent = 9
x = 307
y = 132
cardtype = "Cavalry"
connections = [79, 33, 88, 87, 18]

[[countries]]
id = 33
name = "202"
continent = 9
x = 341
y = 95
cardtype = "Cavalry"
connections = [32, 34, 89, 49, 18, 19]

[[countries]]
id = 34
name = "203"
continent = 9
x = 382
y = 80
cardtype = "Cannon"
connections = [33, 35, 90, 19, 20]

[[countries]]
id = 35
name = "204"
continent = 9
x = 423
y = 71
cardtype = "Cannon"
connections = [34, 36, 90, 20, 21]

[[countries]]
id = 36
name = "205"
continent = 9
x = 468
y = 71
cardtype = "Cannon"
connections = [35, 37, 91, 21, 22]

[[countries]]
id = 37
name = "206"
continent = 9
x = 510
y = 78
cardtype = "Infantry"
connections = [36, 38, 92, 22, 23, 91]

[[countries]]
id = 38
name = "207"
continent = 9
x = 552
y = 99
cardtype = "Infantry"
connections = [37, 39, 93, 23, 24, 92]

[[countries]]
id = 39
name = "208"
continent = 9
x = 583
y = 133
cardtype = "Infantry"
connections = [38, 94, 24, 93, 105]

[[countries]]
id = 40
name = "211"
continent = 10
x = 586
y = 252
cardtype = "Cavalry"
connections = [83, 41, 95, 25, 96]

[[countries]]
id = 41
name = "212"
continent = 10
x = 550
y = 287
cardtype = "Cavalry"
connections = [40, 42, 96, 25, 26, 97]

[[countries]]
id = 42
name = "213"
continent = 10
x = 509
y = 307
cardtype = "Cavalry"
connections = [41, 43, 97, 26, 27]

[[countries]]
id = 43
name = "214"
continent = 10
x = 467
y = 315
cardtype = "Cannon"
connections = [98, 42, 44, 27, 28]

[[countries]]
id = 44
name = "215"
continent = 10
x = 423
y = 315
cardtype = "Cannon"
connections = [99, 43, 45, 28, 29]

[[countries]]
id = 45
name = "216"
continent = 10
x = 383
y = 307
cardtype = "Cannon"
connections = [99, 44, 46, 29, 30, 100]

[[countries]]
id = 46
name = "217"
continent = 10
x = 342
y = 291
cardtype = "Infantry"
connections = [100, 45, 47, 30, 31, 101]

[[countries]]
id = 47
name = "218"
continent = 10
x = 307
y = 255
cardtype = "Infantry"
connections = [82, 101, 46, 31, 80, 102]

[[countries]]
id = 48
name = "301"
continent = 11
x = 291
y = 119
cardtype = "Infantry"
connections = [81, 49, 88, 87]

[[countries]]
id = 49
name = "302"
continent = 11
x = 325
y = 84
cardtype = "Cavalry"
connections = [48, 50, 89, 33, 88]

[[countries]]
id = 50
name = "303"
continent = 11
x = 374
y = 61
cardtype = "Cavalry"
connections = [49, 51, 90, 89]

[[countries]]
id = 51
name = "304"
continent = 11
x = 421
y = 49
cardtype = "Cavalry"
connections = [50, 90, 103]

[[countries]]
id = 52
name = "306"
continent = 11
x = 517
y = 60
cardtype = "Cannon"
connections = [53, 92, 91, 103]

[[countries]]
id = 53
name = "307"
continent = 11
x = 564
y = 85
cardtype = "Cannon"
connections = [52, 54, 93, 92]

[[countries]]
id = 54
name = "308"
continent = 11
x = 596
y = 119
cardtype = "Cannon"
connections = [84, 53, 94, 93]

[[countries]]
id = 55
name = "311"
continent = 12
x = 597
y = 270
cardtype = "Infantry"
connections = [85, 56, 95, 96]

[[countries]]
id = 56
name = "312"
continent = 12
x = 563
y = 302
cardtype = "Infantry"
connections = [55, 57, 96, 97]

[[countries]]
id = 57
name = "313"
continent = 12
x = 518
y = 322
cardtype = "Infantry"
connections = [56, 97, 98, 104]

[[countries]]
id = 58
name = "315"
continent = 12
x = 420
y = 336
cardtype = "Cavalry"
connections = [99, 59, 104]

[[countries]]
id = 59
name = "316"
continent = 12
x = 374
y = 326
cardtype = "Cavalry"
connections = [99, 58, 60, 100]

[[countries]]
id = 60
name = "317"
continent = 12
x = 328
y = 302
cardtype = "Cavalry"
connections = [100, 59, 61, 101]

[[countries]]
id = 61
name = "318"
continent = 12
x = 294
y = 269
cardtype = "Cannon"
connections = [82, 101, 60, 102]

[[countries]]
id = 62
name = "401"
continent = 13
x = 265
y = 136
cardtype = "Cannon"
connections = [63, 87]

[[countries]]
id = 63
name = "402"
continent = 13
x = 296
y = 88
cardtype = "Cannon"
connections = [62, 64, 88]

[[countries]]
id = 64
name = "403"
continent = 13
x = 339
y = 57
cardtype = "Infantry"
connections = [63, 65, 89]

[[countries]]
id = 65
name = "404"
continent = 13
x = 391
y = 39
cardtype = "Infantry"
connections = [64, 90]

[[countries]]
id = 66
name = "405"
continent = 14
x = 494
y = 38
cardtype = "Infantry"
connections = [67, 91]

[[countries]]
id = 67
name = "406"
continent = 14
x = 549
y = 59
cardtype = "Cavalry"
connections = [66, 68, 92]

[[countries]]
id = 68
name = "407"
continent = 14
x = 593
y = 89
cardtype = "Cavalry"
connections = [67, 69, 93]

[[countries]]
id = 69
name = "408"
continent = 14
x = 627
y = 137
cardtype = "Cavalry"
connections = [68, 94]

[[countries]]
id = 70
name = "411"
continent = 15
x = 626
y = 252
cardtype = "Cannon"
connections = [71, 95]

[[countries]]
id = 71
name = "412"
continent = 15
x = 593
y = 296
cardtype = "Cannon"
connections = [70, 72, 96]

[[countries]]
id = 72
name = "413"
continent = 15
x = 550
y = 327
cardtype = "Cannon"
connections = [71, 73, 97]

[[countries]]
id = 73
name = "414"
continent = 15
x = 498
y = 347
cardtype = "Infantry"
connections = [98, 72]

[[countries]]
id = 74
name = "415"
continent = 16
x = 392
y = 348
cardtype = "Infantry"
connections = [99, 75]

[[countries]]
id = 75
name = "416"
continent = 16
x = 340
y = 328
cardtype = "Infantry"
connections = [100, 74, 76]

[[countries]]
id = 76
name = "417"
continent = 16
x = 294
y = 296
cardtype = "Cavalry"
connections = [101, 75, 77]

[[countries]]
id = 77
name = "418"
continent = 16
x = 264
y = 254
cardtype = "Cavalry"
connections = [102, 76]

[[countries]]
id = 78
name = "Haupteingang"
continent = 17
x = 193
y = 187
cardtype = "Cavalry"
connections = [102, 87, 2, 7]

[[countries]]
id = 79
name = "200"
continent = 24
x = 293
y = 167
cardtype = "Cannon"
connections = [32, 80, 87]

[[countries]]
id = 80
name = "219"
continent = 24
x = 293
y = 218
cardtype = "Cannon"
connections = [79, 102, 47]

[[countries]]
id = 81
name = "300"
continent = 24
x = 269
y = 163
cardtype = "Cannon"
connections = [82, 48, 87]

[[countries]]
id = 82
name = "319"
continent = 24
x = 272
y = 221
cardtype = "Infantry"
connections = [81, 61, 47, 102]

[[countries]]
id = 83
name = "210"
continent = 18
x = 594
y = 216
cardtype = "Infantry"
connections = [40, 95, 105]

[[countries]]
id = 84
name = "309"
continent = 18
x = 620
y = 165
cardtype = "Infantry"
connections = [54, 85, 94]

[[countries]]
id = 85
name = "310"
continent = 18
x = 620
y = 220
cardtype = "Cavalry"
connections = [84, 55, 95]

[[countries]]
id = 86
name = "Nordeingang"
continent = 19
x = 445
y = 403
cardtype = "Cavalry"
connections = [29, 28, 99, 98, 17, 16, 27, 104, 7]

[[countries]]
id = 87
name = "A"
continent = 20
x = 246
y = 128
cardtype = "Cavalry"
connections = [78, 88, 62, 81, 32, 79, 102, 48]

[[countries]]
id = 88
name = "B"
continent = 20
x = 279
y = 78
cardtype = "Cannon"
connections = [89, 63, 48, 32, 18, 87, 49]

[[countries]]
id = 89
name = "C"
continent = 20
x = 329
y = 41
cardtype = "Cannon"
connections = [64, 90, 88, 49, 33, 19, 18, 50]

[[countries]]
id = 90
name = "D"
continent = 20
x = 390
y = 20
cardtype = "Cannon"
connections = [14, 91, 65, 51, 50, 34, 20, 35, 19, 89, 21]

[[countries]]
id = 91
name = "E"
continent = 21
x = 498
y = 20
cardtype = "Infantry"
connections = [15, 92, 90, 66, 36, 22, 21, 37, 52, 103]

[[countries]]
id = 92
name = "F"
continent = 21
x = 562
y = 43
cardtype = "Infantry"
connections = [93, 67, 52, 37, 23, 91, 38, 53]

[[countries]]
id = 93
name = "G"
continent = 21
x = 608
y = 76
cardtype = "Infantry"
connections = [94, 92, 53, 68, 38, 24, 54, 39]

[[countries]]
id = 94
name = "H"
continent = 21
x = 644
y = 127
cardtype = "Cavalry"
connections = [69, 84, 54, 39, 93, 95, 105, 1]

[[countries]]
id = 95
name = "J"
continent = 22
x = 642
y = 263
cardtype = "Cavalry"
connections = [96, 70, 55, 85, 83, 40, 94, 1]

[[countries]]
id = 96
name = "K"
continent = 22
x = 605
y = 310
cardtype = "Cannon"
connections = [71, 56, 41, 97, 95, 55, 25, 40]

[[countries]]
id = 97
name = "L"
continent = 21
x = 558
y = 344
cardtype = "Cannon"
connections = [98, 72, 57, 42, 96, 25, 26, 56, 41]

[[countries]]
id = 98
name = "M"
continent = 22
x = 501
y = 364
cardtype = "Cannon"
connections = [43, 27, 73, 97, 86, 99, 57, 26, 104]

[[countries]]
id = 99
name = "N"
continent = 23
x = 388
y = 364
cardtype = "Infantry"
connections = [100, 45, 59, 74, 58, 44, 86, 98, 29]

[[countries]]
id = 100
name = "O"
continent = 23
x = 332
y = 343
cardtype = "Infantry"
connections = [101, 60, 46, 30, 75, 99, 59, 45]

[[countries]]
id = 101
name = "P"
continent = 23
x = 282
y = 308
cardtype = "Infantry"
connections = [102, 61, 47, 100, 76, 60, 31, 46]

[[countries]]
id = 102
name = "Q"
continent = 23
x = 247
y = 259
cardtype = "Cavalry"
connections = [78, 80, 82, 101, 77, 87, 61, 47]

[[countries]]
id = 103
name = "305"
continent = 11
x = 468
y = 49
cardtype = "Cavalry"
connections = [91, 52, 51]

[[countries]]
id = 104
name = "314"
continent = 12
x = 468
y = 336
cardtype = "Cavalry"
connections = [86, 58, 57, 98]

[[countries]]
id = 105
name = "209"
continent = 18
x = 596
y = 168
cardtype = "Cannon"
connections = [39, 83, 94]
