[info]
name = "unknown"

[files]
pic = "aztec_pic.jpg"
map = "aztec_map.gif"
crd = "aztec.cards"

[[continents]]
id = 1
name = "CTBase"
bonus = 2
color = "#ffff99"

[[continents]]
id = 2
name = "CTHallway"
bonus = 1
color = "#33ccff"

[[continents]]
id = 3
name = "Bombspot-A"
bonus = 3
color = "#ffcc33"

[[continents]]
id = 4
name = "Courtyard"
bonus = 3
color = "magenta"

[[continents]]
id = 5
name = "Bridge"
bonus = 3
color = "green"

[[continents]]
id = 6
name = "Water"
bonus = 4
color = "#9900ff"

[[continents]]
id = 7
name = "DoubleDoors"
bonus = 3
color = "#9999ff"

[[continents]]
id = 8
name = "BombspotB"
bonus = 3
color = "#ff6666"

[[continents]]
id = 9
name = "Center"
bonus = 1
color = "#99ff99"

[[continents]]
id = 10
name = "THallway"
bonus = 2
color = "#ff9900"

[[continents]]
id = 11
name = "TBase"
bonus = 2
color = "red"

[[countries]]
id = 1
name = "CTBase-East"
continent = 1
x = 99
y = 299
connections = [2, 4]

[[countries]]
id = 2
name = "CTBase-Center"
continent = 1
x = 46
y = 284
connections = [1, 3]

[[countries]]
id = 3
name = "CTBase-North"
continent = 1
x = 42
y = 176
connections = [2, 6]

[[countries]]
id = 4
name = "CTHallway-West"
continent = 2
x = 158
y = 317
connections = [1, 5]

[[countries]]
id = 5
name = "CTHallway-East"
continent = 2
x = 227
y = 331
connections = [4, 23]

[[countries]]
id = 6
name = "BombspotA-West"
continent = 3
x = 69
y = 88
connections = [3, 7]

[[countries]]
id = 7
name = "BombspotA-Center"
continent = 3
x = 149
y = 99
connections = [6, 8, 12]

[[countries]]
id = 8
name = "BombspotA-South"
continent = 3
x = 152
y = 158
connections = [7, 9]

[[countries]]
id = 9
name = "Courtyard-West"
continent = 4
x = 156
y = 222
connections = [8, 10]

[[countries]]
id = 10
name = "Courtyard-Center"
continent = 4
x = 215
y = 229
connections = [9, 11, 12, 26]

[[countries]]
id = 11
name = "Courtyard-East"
continent = 4
x = 310
y = 234
connections = [10, 22]

[[countries]]
id = 12
name = "Bridgehouse-West"
continent = 5
x = 212
y = 114
connections = [7, 10, 13]

[[countries]]
id = 13
name = "Bridge"
continent = 5
x = 303
y = 116
connections = [12, 14]

[[countries]]
id = 14
name = "Bridgehouse-East"
continent = 5
x = 385
y = 116
connections = [13, 21]

[[countries]]
id = 15
name = "Water-North"
continent = 6
x = 556
y = 51
connections = [16]

[[countries]]
id = 16
name = "Water-East"
continent = 6
x = 535
y = 112
connections = [15, 17, 30]

[[countries]]
id = 17
name = "Water-Center"
continent = 6
x = 449
y = 114
connections = [16, 18, 21]

[[countries]]
id = 18
name = "Water-West"
continent = 6
x = 343
y = 76
connections = [17, 19]

[[countries]]
id = 19
name = "Water-South"
continent = 6
x = 302
y = 179
connections = [18, 26]

[[countries]]
id = 20
name = "DoubleDoors-East"
continent = 7
x = 462
y = 174
connections = [21, 33]

[[countries]]
id = 21
name = "DoubleDoors-Center"
continent = 7
x = 383
y = 173
connections = [14, 17, 20, 22]

[[countries]]
id = 22
name = "DoubleDoors-South"
continent = 7
x = 382
y = 231
connections = [11, 21, 25]

[[countries]]
id = 23
name = "BombspotB-West"
continent = 8
x = 297
y = 358
connections = [5, 24, 27]

[[countries]]
id = 24
name = "BombspotB-Center"
continent = 8
x = 383
y = 341
connections = [23, 25, 27]

[[countries]]
id = 25
name = "BombspotC-North"
continent = 8
x = 394
y = 271
connections = [24, 22]

[[countries]]
id = 26
name = "Waterfront"
continent = 9
x = 295
y = 292
connections = [10, 19, 27]

[[countries]]
id = 27
name = "Stairs"
continent = 9
x = 347
y = 292
connections = [23, 24, 26]

[[countries]]
id = 28
name = "THallway-East"
continent = 10
x = 629
y = 103
connections = [29, 31]

[[countries]]
id = 29
name = "THallway-North"
continent = 10
x = 615
y = 47
connections = [28, 30]

[[countries]]
id = 30
name = "THallway-West"
continent = 10
x = 598
y = 111
connections = [16, 29]

[[countries]]
id = 31
name = "TBase-North"
continent = 11
x = 627
y = 170
connections = [28, 32]

[[countries]]
id = 32
name = "TBase-Center"
continent = 11
x = 629
y = 234
connections = [31, 33]

[[countries]]
id = 33
name = "TBase-West"
continent = 11
x = 547
y = 234
connections = [20, 32]
