[info]
name = "unknown"
nb_wildcards = 2

[[continents]]
id = 1
name = "Vojvodina"
bonus = 5
color = "yellow"

[[continents]]
id = 2
name = "Bosna_i_Hercegovina"
bonus = 2
color = "red"

[[continents]]
id = 3
name = "Juzna_Srbija"
bonus = 5
color = "blue"

[[continents]]
id = 4
name = "Crna_Gora"
bonus = 3
color = "orange"

[[continents]]
id = 5
name = "Sumadija"
bonus = 7
color = "green"

[[continents]]
id = 6
name = "Krajina"
bonus = 2
color = "magenta"

[[countries]]
id = 1
name = "Subotica"
continent = 1
x = 380
y = 110
cardtype = "Infantry"
connections = [2, 3, 4]

[[countries]]
id = 2
name = "Zrenjanin"
continent = 1
x = 425
y = 128
cardtype = "Cannon"
connections = [1, 3, 20]

[[countries]]
id = 3
name = "Sremska_Mitrovica"
continent = 1
x = 397
y = 146
cardtype = "Infantry"
connections = [1, 2, 4, 20, 26]

[[countries]]
id = 4
name = "Osijek"
continent = 1
x = 346
y = 124
cardtype = "Infantry"
connections = [1, 3, 5, 6, 26]

[[countries]]
id = 5
name = "Bijelovar"
continent = 1
x = 308
y = 124
cardtype = "Cavalry"
connections = [4, 6, 7, 26, 27]

[[countries]]
id = 6
name = "Posavina"
continent = 2
x = 320
y = 154
cardtype = "Cavalry"
connections = [5, 7, 8, 26]

[[countries]]
id = 7
name = "Banja_Luka"
continent = 2
x = 274
y = 170
cardtype = "Cavalry"
connections = [5, 6, 8, 9, 27, 28]

[[countries]]
id = 8
name = "Sarajevo"
continent = 2
x = 325
y = 196
cardtype = "Cannon"
connections = [6, 7, 9, 25, 26]

[[countries]]
id = 9
name = "Mostar"
continent = 2
x = 320
y = 254
cardtype = "Cannon"
connections = [7, 8, 16, 18, 25, 28, 29]

[[countries]]
id = 10
name = "Nis"
continent = 3
x = 484
y = 263
cardtype = "Cannon"
connections = [11, 13, 15, 22, 23, 24]

[[countries]]
id = 11
name = "Kosovska_Mitrovica"
continent = 3
x = 440
y = 269
cardtype = "Cavalry"
connections = [10, 12, 13, 24]

[[countries]]
id = 12
name = "Pec"
continent = 3
x = 425
y = 291
cardtype = "Cannon"
connections = [11, 13, 17, 19, 24]

[[countries]]
id = 13
name = "Pristina"
continent = 3
x = 455
y = 299
cardtype = "Infantry"
connections = [10, 11, 12, 14, 15]

[[countries]]
id = 14
name = "Bitolj"
continent = 3
x = 463
y = 356
cardtype = "Infantry"
connections = [13, 15]

[[countries]]
id = 15
name = "Skoplje"
continent = 3
x = 500
y = 333
cardtype = "Cannon"
connections = [10, 13, 14]

[[countries]]
id = 16
name = "Niksic"
continent = 4
x = 359
y = 263
cardtype = "Cannon"
connections = [9, 17, 18, 24, 25]

[[countries]]
id = 17
name = "Podgorica"
continent = 4
x = 382
y = 279
cardtype = "Cavalry"
connections = [12, 16, 18, 19, 24]

[[countries]]
id = 18
name = "Budva"
continent = 4
x = 353
y = 303
cardtype = "Cavalry"
connections = [16, 17, 19, 29]

[[countries]]
id = 19
name = "Skadar"
continent = 4
x = 404
y = 308
cardtype = "Infantry"
connections = [12, 13, 17, 18]

[[countries]]
id = 20
name = "Beograd"
continent = 5
x = 421
y = 167
cardtype = "Cavalry"
connections = [2, 3, 21, 22]

[[countries]]
id = 21
name = "Uzice"
continent = 5
x = 395
y = 201
cardtype = "Infantry"
connections = [3, 4, 20, 22, 24, 25, 26]

[[countries]]
id = 22
name = "Kragujevac"
continent = 5
x = 437
y = 200
cardtype = "Infantry"
connections = [2, 10, 20, 21, 23, 24]

[[countries]]
id = 23
name = "Negotin"
continent = 5
x = 488
y = 197
cardtype = "Cavalry"
connections = [2, 10, 22]

[[countries]]
id = 24
name = "Raska"
continent = 5
x = 410
y = 243
cardtype = "Cannon"
connections = [10, 11, 12, 16, 17, 21, 22, 25]

[[countries]]
id = 25
name = "Visegrad"
continent = 5
x = 362
y = 212
cardtype = "Cannon"
connections = [8, 9, 16, 21, 24, 26]

[[countries]]
id = 26
name = "Bijeljina"
continent = 5
x = 352
y = 164
cardtype = "Infantry"
connections = [4, 5, 6, 8, 25, 27]

[[countries]]
id = 27
name = "Knin"
continent = 6
x = 216
y = 151
cardtype = "Cannon"
connections = [5, 7, 28]

[[countries]]
id = 28
name = "Split"
continent = 6
x = 277
y = 240
cardtype = "Cavalry"
connections = [7, 9, 27]

[[countries]]
id = 29
name = "Dubrovnik"
continent = 6
x = 315
y = 278
cardtype = "Cavalry"
connections = [9, 18]
