[info]
name = "unknown"

[files]
pic = "ohio_pic.png"
map = "ohio_map.gif"
crd = "ohio.cards"

[[continents]]
id = 1
name = "Toledo_Region"
bonus = 7
color = "green"

[[continents]]
id = 2
name = "Cincinnati_Region"
bonus = 5
color = "blue"

[[continents]]
id = 3
name = "Columbus_Region"
bonus = 7
color = "red"

[[continents]]
id = 4
name = "Cleveland_Region"
bonus = 7
color = "yellow"

[[continents]]
id = 5
name = "Marietta_Region"
bonus = 9
color = "purple"

[[countries]]
id = 1
name = "Williams"
continent = 1
x = 166
y = 54
connections = [2, 8, 7]

[[countries]]
id = 2
name = "Fulton"
continent = 1
x = 207
y = 49
connections = [1, 3, 7]

[[countries]]
id = 3
name = "Lucas"
continent = 1
x = 276
y = 35
connections = [2, 4, 6, 7]

[[countries]]
id = 4
name = "Ottawa"
continent = 1
x = 295
y = 57
connections = [3, 5, 6, 52]

[[countries]]
id = 5
name = "Sandusky"
continent = 1
x = 296
y = 78
connections = [4, 52, 6, 12, 51]

[[countries]]
id = 6
name = "Wood"
continent = 1
x = 252
y = 81
connections = [3, 4, 5, 7, 11, 12]

[[countries]]
id = 7
name = "Henry"
continent = 1
x = 216
y = 81
connections = [1, 2, 3, 6, 10, 8]

[[countries]]
id = 8
name = "Defiance"
continent = 1
x = 177
y = 80
connections = [1, 10, 7, 9]

[[countries]]
id = 9
name = "Paulding"
continent = 1
x = 169
y = 105
connections = [10, 8, 18]

[[countries]]
id = 10
name = "Putnam"
continent = 1
x = 210
y = 116
connections = [11, 7, 8, 9, 18, 16]

[[countries]]
id = 11
name = "Hancock"
continent = 1
x = 251
y = 120
connections = [6, 10, 12, 14, 15, 16]

[[countries]]
id = 12
name = "Seneca"
continent = 1
x = 298
y = 105
connections = [5, 6, 11, 51, 13, 14]

[[countries]]
id = 13
name = "Crawford"
continent = 1
x = 316
y = 137
connections = [12, 14, 47, 48, 50, 51]

[[countries]]
id = 14
name = "Wyandot"
continent = 1
x = 281
y = 138
connections = [11, 12, 13, 47, 15]

[[countries]]
id = 15
name = "Hardin"
continent = 1
x = 250
y = 158
connections = [11, 14, 47, 45, 44, 17, 16]

[[countries]]
id = 16
name = "Allen"
continent = 1
x = 213
y = 147
connections = [10, 11, 15, 17, 18]

[[countries]]
id = 17
name = "Auglaize"
continent = 1
x = 197
y = 169
connections = [15, 16, 18, 21, 44, 19, 20]

[[countries]]
id = 18
name = "Van_Wert"
continent = 1
x = 167
y = 137
connections = [10, 9, 16, 19, 17]

[[countries]]
id = 19
name = "Mercer"
continent = 1
x = 165
y = 174
connections = [18, 17, 20]

[[countries]]
id = 20
name = "Darke"
continent = 2
x = 164
y = 220
connections = [17, 19, 21, 22, 23, 24]

[[countries]]
id = 21
name = "Shelby"
continent = 2
x = 202
y = 198
connections = [17, 20, 22, 43, 44]

[[countries]]
id = 22
name = "Miami"
continent = 2
x = 200
y = 230
connections = [20, 21, 23, 42, 43]

[[countries]]
id = 23
name = "Montgomery"
continent = 2
x = 194
y = 264
connections = [20, 22, 33, 42, 24, 25, 26]

[[countries]]
id = 24
name = "Preble"
continent = 2
x = 163
y = 265
connections = [20, 23, 25]

[[countries]]
id = 25
name = "Butler"
continent = 2
x = 168
y = 300
connections = [23, 24, 27, 26]

[[countries]]
id = 26
name = "Warren"
continent = 2
x = 205
y = 303
connections = [23, 25, 33, 32, 28, 27]

[[countries]]
id = 27
name = "Hamilton"
continent = 2
x = 159
y = 342
connections = [25, 26, 28]

[[countries]]
id = 28
name = "Clermont"
continent = 2
x = 205
y = 343
connections = [26, 27, 29, 32]

[[countries]]
id = 29
name = "Brown"
continent = 2
x = 232
y = 363
connections = [28, 30, 31, 32]

[[countries]]
id = 30
name = "Adams"
continent = 2
x = 267
y = 369
connections = [29, 87, 88, 31]

[[countries]]
id = 31
name = "Highland"
continent = 2
x = 256
y = 331
connections = [29, 30, 32, 88, 35, 34]

[[countries]]
id = 32
name = "Clinton"
continent = 2
x = 238
y = 304
connections = [26, 28, 29, 31, 33, 34]

[[countries]]
id = 33
name = "Greene"
continent = 2
x = 231
y = 272
connections = [23, 26, 32, 34, 41, 42]

[[countries]]
id = 34
name = "Fayette"
continent = 3
x = 269
y = 285
connections = [31, 32, 33, 41, 37, 35]

[[countries]]
id = 35
name = "Ross"
continent = 3
x = 304
y = 313
connections = [31, 34, 88, 36, 83, 85, 37]

[[countries]]
id = 36
name = "Hocking"
continent = 3
x = 355
y = 295
connections = [35, 83, 81, 80, 38, 37]

[[countries]]
id = 37
name = "Pickaway"
continent = 3
x = 305
y = 276
connections = [34, 35, 36, 40, 41, 38]

[[countries]]
id = 38
name = "Fairfield"
continent = 3
x = 344
y = 265
connections = [36, 37, 80, 40, 39]

[[countries]]
id = 39
name = "Licking"
continent = 3
x = 356
y = 226
connections = [38, 49, 72, 73, 80, 40, 46]

[[countries]]
id = 40
name = "Franklin"
continent = 3
x = 316
y = 249
connections = [37, 38, 39, 46, 41, 45]

[[countries]]
id = 41
name = "Madison"
continent = 3
x = 273
y = 252
connections = [33, 34, 37, 40, 42, 43, 45]

[[countries]]
id = 42
name = "Clark"
continent = 3
x = 238
y = 245
connections = [22, 23, 33, 41, 43]

[[countries]]
id = 43
name = "Champaign"
continent = 3
x = 241
y = 221
connections = [21, 22, 41, 42, 44, 45]

[[countries]]
id = 44
name = "Logan"
continent = 3
x = 243
y = 191
connections = [15, 17, 21, 43, 45]

[[countries]]
id = 45
name = "Union"
continent = 3
x = 274
y = 200
connections = [15, 40, 41, 43, 44, 47, 46]

[[countries]]
id = 46
name = "Delaware"
continent = 3
x = 308
y = 206
connections = [39, 40, 45, 49, 48, 47]

[[countries]]
id = 47
name = "Marion"
continent = 3
x = 295
y = 166
connections = [13, 14, 15, 45, 46, 48]

[[countries]]
id = 48
name = "Morrow"
continent = 3
x = 329
y = 179
connections = [13, 46, 47, 49, 50]

[[countries]]
id = 49
name = "Knox"
continent = 3
x = 362
y = 188
connections = [39, 46, 48, 72, 55, 54, 50]

[[countries]]
id = 50
name = "Richland"
continent = 4
x = 349
y = 146
connections = [13, 48, 49, 54, 51]

[[countries]]
id = 51
name = "Huron"
continent = 4
x = 344
y = 103
connections = [12, 5, 13, 50, 54, 53, 52]

[[countries]]
id = 52
name = "Erie"
continent = 4
x = 335
y = 76
connections = [4, 5, 51, 53]

[[countries]]
id = 53
name = "Lorain"
continent = 4
x = 383
y = 85
connections = [51, 52, 54, 57, 58]

[[countries]]
id = 54
name = "Ashland"
continent = 4
x = 372
y = 135
connections = [49, 50, 51, 53, 55, 56, 57]

[[countries]]
id = 55
name = "Holmes"
continent = 4
x = 402
y = 170
connections = [49, 54, 72, 71, 65, 56]

[[countries]]
id = 56
name = "Wayne"
continent = 4
x = 406
y = 141
connections = [54, 55, 57, 64, 65]

[[countries]]
id = 57
name = "Medina"
continent = 4
x = 407
y = 106
connections = [53, 54, 56, 64, 58]

[[countries]]
id = 58
name = "Cuyahoga"
continent = 4
x = 440
y = 57
connections = [53, 57, 59, 60, 64]

[[countries]]
id = 59
name = "Lake"
continent = 4
x = 465
y = 30
connections = [58, 60, 61]

[[countries]]
id = 60
name = "Geauga"
continent = 4
x = 471
y = 65
connections = [58, 59, 63, 62, 61]

[[countries]]
id = 61
name = "Ashtabula"
continent = 4
x = 507
y = 39
connections = [59, 60, 62]

[[countries]]
id = 62
name = "Trumbull"
continent = 4
x = 509
y = 83
connections = [60, 61, 66, 63]

[[countries]]
id = 63
name = "Portage"
continent = 4
x = 470
y = 99
connections = [60, 62, 66, 65, 64]

[[countries]]
id = 64
name = "Summit"
continent = 4
x = 439
y = 104
connections = [56, 57, 58, 63, 65]

[[countries]]
id = 65
name = "Stark"
continent = 4
x = 452
y = 143
connections = [55, 56, 63, 64, 71, 69, 67, 66]

[[countries]]
id = 66
name = "Mahoning"
continent = 4
x = 507
y = 118
connections = [62, 63, 65, 67]

[[countries]]
id = 67
name = "Columbiana"
continent = 4
x = 509
y = 149
connections = [65, 66, 68, 69]

[[countries]]
id = 68
name = "Jefferson"
continent = 5
x = 510
y = 190
connections = [67, 70, 69, 75]

[[countries]]
id = 69
name = "Carroll"
continent = 5
x = 480
y = 169
connections = [65, 67, 68, 70, 71]

[[countries]]
id = 70
name = "Harrison"
continent = 5
x = 480
y = 202
connections = [68, 69, 75, 74, 71]

[[countries]]
id = 71
name = "Tuscarawas"
continent = 5
x = 446
y = 184
connections = [55, 65, 69, 70, 74, 72]

[[countries]]
id = 72
name = "Coshocton"
continent = 5
x = 404
y = 200
connections = [39, 49, 55, 71, 73, 74]

[[countries]]
id = 73
name = "Muskingum"
continent = 5
x = 403
y = 240
connections = [39, 72, 80, 79, 77, 74]

[[countries]]
id = 74
name = "Guernsey"
continent = 5
x = 444
y = 229
connections = [70, 71, 72, 73, 77, 75]

[[countries]]
id = 75
name = "Belmont"
continent = 5
x = 488
y = 235
connections = [68, 70, 74, 76, 77]

[[countries]]
id = 76
name = "Monroe"
continent = 5
x = 482
y = 269
connections = [75, 78, 77]

[[countries]]
id = 77
name = "Noble"
continent = 5
x = 444
y = 264
connections = [73, 74, 75, 76, 78, 79]

[[countries]]
id = 78
name = "Washington"
continent = 5
x = 428
y = 308
connections = [76, 77, 79, 81]

[[countries]]
id = 79
name = "Morgan"
continent = 5
x = 412
y = 280
connections = [73, 77, 78, 81, 80]

[[countries]]
id = 80
name = "Perry"
continent = 5
x = 379
y = 270
connections = [36, 38, 39, 73, 79, 81]

[[countries]]
id = 81
name = "Athens"
continent = 5
x = 394
y = 313
connections = [36, 79, 78, 80, 82, 83]

[[countries]]
id = 82
name = "Meigs"
continent = 5
x = 395
y = 340
connections = [81, 84, 83]

[[countries]]
id = 83
name = "Vinton"
continent = 5
x = 358
y = 320
connections = [35, 36, 81, 82, 84, 85]

[[countries]]
id = 84
name = "Gallia"
continent = 5
x = 368
y = 375
connections = [82, 83, 86, 85]

[[countries]]
id = 85
name = "Jackson"
continent = 5
x = 344
y = 349
connections = [35, 83, 84, 86, 87, 88]

[[countries]]
id = 86
name = "Lawrence"
continent = 5
x = 352
y = 399
connections = [84, 87, 85]

[[countries]]
id = 87
name = "Scioto"
continent = 5
x = 311
y = 369
connections = [30, 86, 85, 88]

[[countries]]
id = 88
name = "Pike"
continent = 5
x = 304
y = 343
connections = [30, 31, 35, 85, 87]
