[info]
name = "unknown"

[files]
pic = "chutes.jpg"
map = "chutes.gif"
crd = "chutes.cards"

[[continents]]
id = 1
name = "AB"
bonus = 3
color = "yellow"

[[continents]]
id = 2
name = "CDE"
bonus = 5
color = "red"

[[continents]]
id = 3
name = "FGH"
bonus = 5
color = "blue"

[[continents]]
id = 4
name = "IJ"
bonus = 3
color = "orange"

[[countries]]
id = 1
name = "One"
continent = 1
x = 160
y = 400
connections = [2, 38]

[[countries]]
id = 2
name = "Two"
continent = 1
x = 200
y = 400
connections = [3]

[[countries]]
id = 3
name = "Three"
continent = 1
x = 240
y = 400
connections = [4]

[[countries]]
id = 4
name = "Four"
continent = 1
x = 280
y = 400
connections = [5, 14]

[[countries]]
id = 5
name = "Five"
continent = 1
x = 320
y = 400
connections = [6]

[[countries]]
id = 6
name = "Six"
continent = 1
x = 360
y = 400
connections = [7]

[[countries]]
id = 7
name = "Seven"
continent = 1
x = 400
y = 400
connections = [8]

[[countries]]
id = 8
name = "Eight"
continent = 1
x = 440
y = 400
connections = [9]

[[countries]]
id = 9
name = "Nine"
continent = 1
x = 480
y = 400
connections = [10, 31]

[[countries]]
id = 10
name = "Ten"
continent = 1
x = 520
y = 400
connections = [11]

[[countries]]
id = 11
name = "Eleven"
continent = 1
x = 520
y = 357
connections = [12]

[[countries]]
id = 12
name = "Twelve"
continent = 1
x = 480
y = 357
connections = [13]

[[countries]]
id = 13
name = "Thirteen"
continent = 1
x = 440
y = 357
connections = [14]

[[countries]]
id = 14
name = "Fourteen"
continent = 1
x = 400
y = 357
connections = [15]

[[countries]]
id = 15
name = "Fifteen"
continent = 1
x = 360
y = 357
connections = [16]

[[countries]]
id = 16
name = "Sixteen"
continent = 1
x = 320
y = 357
connections = [6, 17]

[[countries]]
id = 17
name = "Seventeen"
continent = 1
x = 280
y = 357
connections = [18]

[[countries]]
id = 18
name = "Eighteen"
continent = 1
x = 240
y = 357
connections = [19]

[[countries]]
id = 19
name = "Nineteen"
continent = 1
x = 200
y = 357
connections = [20]

[[countries]]
id = 20
name = "Twenty"
continent = 1
x = 160
y = 357
connections = [21]

[[countries]]
id = 21
name = "Twenty-one"
continent = 2
x = 160
y = 316
connections = [22, 42]

[[countries]]
id = 22
name = "Twenty-two"
continent = 2
x = 200
y = 316
connections = [23]

[[countries]]
id = 23
name = "Twenty-three"
continent = 2
x = 240
y = 316
connections = [24]

[[countries]]
id = 24
name = "Twenty-four"
continent = 2
x = 280
y = 316
connections = [25]

[[countries]]
id = 25
name = "Twenty-five"
continent = 2
x = 320
y = 316
connections = [26]

[[countries]]
id = 26
name = "Twenty-six"
continent = 2
x = 360
y = 316
connections = [27]

[[countries]]
id = 27
name = "Twenty-seven"
continent = 2
x = 400
y = 316
connections = [28]

[[countries]]
id = 28
name = "Twenty-eight"
continent = 2
x = 440
y = 316
connections = [29, 84]

[[countries]]
id = 29
name = "Twenty-nine"
continent = 2
x = 480
y = 316
connections = [30]

[[countries]]
id = 30
name = "Thirty"
continent = 2
x = 520
y = 316
connections = [31]

[[countries]]
id = 31
name = "Thirty-one"
continent = 2
x = 520
y = 274
connections = [32]

[[countries]]
id = 32
name = "Thirty-two"
continent = 2
x = 480
y = 274
connections = [33]

[[countries]]
id = 33
name = "Thirty-three"
continent = 2
x = 440
y = 274
connections = [34]

[[countries]]
id = 34
name = "Thirty-four"
continent = 2
x = 400
y = 274
connections = [35]

[[countries]]
id = 35
name = "Thirty-five"
continent = 2
x = 360
y = 274
connections = [36]

[[countries]]
id = 36
name = "Thirty-six"
continent = 2
x = 320
y = 274
connections = [37, 44]

[[countries]]
id = 37
name = "Thirty-seven"
continent = 2
x = 280
y = 274
connections = [38]

[[countries]]
id = 38
name = "Thirty-eight"
continent = 2
x = 240
y = 274
connections = [39]

[[countries]]
id = 39
name = "Thirty-nine"
continent = 2
x = 200
y = 274
connections = [40]

[[countries]]
id = 40
name = "Fourty"
continent = 2
x = 160
y = 274
connections = [41]

[[countries]]
id = 41
name = "Fourty-one"
continent = 2
x = 160
y = 234
connections = [42]

[[countries]]
id = 42
name = "Fourty-two"
continent = 2
x = 200
y = 234
connections = [43]

[[countries]]
id = 43
name = "Fourty-three"
continent = 2
x = 240
y = 234
connections = [44]

[[countries]]
id = 44
name = "Fourty-four"
continent = 2
x = 280
y = 234
connections = [45]

[[countries]]
id = 45
name = "Fourty-five"
continent = 2
x = 320
y = 234
connections = [46]

[[countries]]
id = 46
name = "Fourty-six"
continent = 2
x = 360
y = 234
connections = [47]

[[countries]]
id = 47
name = "Fourty-seven"
continent = 2
x = 400
y = 234
connections = [26, 48]

[[countries]]
id = 48
name = "Fourty-eight"
continent = 2
x = 440
y = 234
connections = [49]

[[countries]]
id = 49
name = "Fourty-nine"
continent = 2
x = 480
y = 234
connections = [11, 50]

[[countries]]
id = 50
name = "Fifty"
continent = 2
x = 520
y = 234
connections = [51]

[[countries]]
id = 51
name = "Fifty-one"
continent = 3
x = 520
y = 190
connections = [52, 67]

[[countries]]
id = 52
name = "Fifty-two"
continent = 3
x = 480
y = 190
connections = [53]

[[countries]]
id = 53
name = "Fifty-three"
continent = 3
x = 440
y = 190
connections = [54]

[[countries]]
id = 54
name = "Fifty-four"
continent = 3
x = 400
y = 190
connections = [55]

[[countries]]
id = 55
name = "Fifty-five"
continent = 3
x = 360
y = 190
connections = [56]

[[countries]]
id = 56
name = "Fifty-six"
continent = 3
x = 320
y = 190
connections = [53, 57]

[[countries]]
id = 57
name = "Fifty-seven"
continent = 3
x = 280
y = 190
connections = [58]

[[countries]]
id = 58
name = "Fifty-eight"
continent = 3
x = 240
y = 190
connections = [59]

[[countries]]
id = 59
name = "Fifty-nine"
continent = 3
x = 200
y = 190
connections = [60]

[[countries]]
id = 60
name = "Sixty"
continent = 3
x = 160
y = 190
connections = [61]

[[countries]]
id = 61
name = "Sixty-one"
continent = 3
x = 160
y = 150
connections = [62]

[[countries]]
id = 62
name = "Sixty-two"
continent = 3
x = 200
y = 150
connections = [19, 63]

[[countries]]
id = 63
name = "Sixty-three"
continent = 3
x = 240
y = 150
connections = [64]

[[countries]]
id = 64
name = "Sixty-four"
continent = 3
x = 280
y = 150
connections = [60, 65]

[[countries]]
id = 65
name = "Sixty-five"
continent = 3
x = 320
y = 150
connections = [66]

[[countries]]
id = 66
name = "Sixty-six"
continent = 3
x = 360
y = 150
connections = [67]

[[countries]]
id = 67
name = "Sixty-seven"
continent = 3
x = 400
y = 150
connections = [68]

[[countries]]
id = 68
name = "Sixty-eight"
continent = 3
x = 440
y = 150
connections = [69]

[[countries]]
id = 69
name = "Sixty-nine"
continent = 3
x = 480
y = 150
connections = [70]

[[countries]]
id = 70
name = "Seventy"
continent = 3
x = 520
y = 150
connections = [71]

[[countries]]
id = 71
name = "Seventy-one"
continent = 3
x = 520
y = 108
connections = [72, 91]

[[countries]]
id = 72
name = "Seventy-two"
continent = 3
x = 480
y = 108
connections = [73]

[[countries]]
id = 73
name = "Seventy-three"
continent = 3
x = 440
y = 108
connections = [74]

[[countries]]
id = 74
name = "Seventy-four"
continent = 3
x = 400
y = 108
connections = [75]

[[countries]]
id = 75
name = "Seventy-five"
continent = 3
x = 360
y = 108
connections = [76]

[[countries]]
id = 76
name = "Seventy-six"
continent = 3
x = 320
y = 108
connections = [77]

[[countries]]
id = 77
name = "Seventy-seven"
continent = 3
x = 280
y = 108
connections = [78]

[[countries]]
id = 78
name = "Seventy-eight"
continent = 3
x = 240
y = 108
connections = [79]

[[countries]]
id = 79
name = "Seventy-nine"
continent = 3
x = 200
y = 108
connections = [80]

[[countries]]
id = 80
name = "Eighty"
continent = 3
x = 160
y = 108
connections = [100, 81]

[[countries]]
id = 81
name = "Eighty-one"
continent = 4
x = 160
y = 65
connections = [82]

[[countries]]
id = 82
name = "Eighty-two"
continent = 4
x = 200
y = 65
connections = [83]

[[countries]]
id = 83
name = "Eighty-three"
continent = 4
x = 240
y = 65
connections = [84]

[[countries]]
id = 84
name = "Eighty-four"
continent = 4
x = 280
y = 65
connections = [85]

[[countries]]
id = 85
name = "Eighty-five"
continent = 4
x = 320
y = 65
connections = [86]

[[countries]]
id = 86
name = "Eighty-six"
continent = 4
x = 360
y = 65
connections = [87]

[[countries]]
id = 87
name = "Eighty-seven"
continent = 4
x = 400
y = 65
connections = [24, 88]

[[countries]]
id = 88
name = "Eighty-eigth"
continent = 4
x = 440
y = 65
connections = [89]

[[countries]]
id = 89
name = "Eighty-nine"
continent = 4
x = 480
y = 65
connections = [90]

[[countries]]
id = 90
name = "Ninety"
continent = 4
x = 520
y = 65
connections = [91]

[[countries]]
id = 91
name = "Ninety-one"
continent = 4
x = 520
y = 20
connections = [92]

[[countries]]
id = 92
name = "Ninety-two"
continent = 4
x = 480
y = 20
connections = [93]

[[countries]]
id = 93
name = "Ninety-three"
continent = 4
x = 440
y = 20
connections = [73, 94]

[[countries]]
id = 94
name = "Ninety-four"
continent = 4
x = 400
y = 20
connections = [95]

[[countries]]
id = 95
name = "Ninety-five"
continent = 4
x = 360
y = 20
connections = [75, 96]

[[countries]]
id = 96
name = "Ninety-six"
continent = 4
x = 320
y = 20
connections = [97]

[[countries]]
id = 97
name = "Ninety-seven"
continent = 4
x = 280
y = 20
connections = [98]

[[countries]]
id = 98
name = "Ninety-eight"
continent = 4
x = 240
y = 20
connections = [78, 99]

[[countries]]
id = 99
name = "Ninety-nine"
continent = 4
x = 200
y = 20
connections = [100]

[[countries]]
id = 100
name = "One-hundred"
continent = 4
x = 160
y = 20
connections = [1]
