[info]
name = "unknown"
nb_wildcards = 2

[[continents]]
id = 1
name = "Simpsons"
bonus = 7
color = "#c4ff80"

[[continents]]
id = 2
name = "Flanders"
bonus = 2
color = "#d4ff80"

[[continents]]
id = 3
name = "Springfield"
bonus = 5
color = "#80ff95"

[[continents]]
id = 4
name = "Escuela_Primaria_de_Springfield"
bonus = 5
color = "#c4ff80"

[[continents]]
id = 5
name = "TV_de_Springfield"
bonus = 3
color = "#a380ff"

[[continents]]
id = 6
name = "La_taberna_de_Moe"
bonus = 2
color = "#ff80d9"

[[countries]]
id = 1
name = "Homero_Simpson"
continent = 1
x = 553
y = 122
cardtype = "Cavalry"
connections = [2, 5, 11, 7, 4, 3, 10, 8]

[[countries]]
id = 2
name = "Marge_Simpson"
continent = 1
x = 496
y = 50
cardtype = "Infantry"
connections = [19, 5, 1, 8]

[[countries]]
id = 3
name = "Bart_Simpson"
continent = 1
x = 588
y = 193
cardtype = "Cannon"
connections = [7, 1, 8, 10, 9, 12, 4]

[[countries]]
id = 4
name = "Lisa_Simpson"
continent = 1
x = 653
y = 189
cardtype = "Cavalry"
connections = [7, 1, 3, 12, 9]

[[countries]]
id = 5
name = "Maggie_Simpson"
continent = 1
x = 577
y = 60
cardtype = "Infantry"
connections = [2, 11, 7, 1, 8]

[[countries]]
id = 6
name = "Abraham_Simpson"
continent = 1
x = 529
y = 253
cardtype = "Cannon"
connections = [21, 10, 37, 9]

[[countries]]
id = 7
name = "Mona_Simpson"
continent = 1
x = 653
y = 119
cardtype = "Cavalry"
connections = [5, 11, 1, 4, 3]

[[countries]]
id = 8
name = "Jacky_Bouvier"
continent = 1
x = 497
y = 103
cardtype = "Infantry"
connections = [19, 21, 2, 5, 1, 10, 3]

[[countries]]
id = 9
name = "Patty_Bouvier"
continent = 1
x = 569
y = 256
cardtype = "Cannon"
connections = [10, 3, 4, 6, 12]

[[countries]]
id = 10
name = "Selma_Bouvier"
continent = 1
x = 534
y = 183
cardtype = "Cavalry"
connections = [21, 1, 8, 3, 9, 6]

[[countries]]
id = 11
name = "Ayudante_de_Santa"
continent = 1
x = 619
y = 51
cardtype = "Infantry"
connections = [31, 5, 7, 1]

[[countries]]
id = 12
name = "Bola_de_Nieve_II"
continent = 1
x = 626
y = 251
cardtype = "Cannon"
connections = [3, 4, 9, 13]

[[countries]]
id = 13
name = "Ned_Flanders"
continent = 2
x = 599
y = 303
cardtype = "Cavalry"
connections = [12, 15, 16]

[[countries]]
id = 14
name = "Maude_Flanders"
continent = 2
x = 554
y = 410
cardtype = "Infantry"
connections = [15, 16]

[[countries]]
id = 15
name = "Rod_Flanders"
continent = 2
x = 595
y = 350
cardtype = "Cannon"
connections = [13, 16, 14]

[[countries]]
id = 16
name = "Todd_Flanders"
continent = 2
x = 531
y = 322
cardtype = "Cavalry"
connections = [13, 15, 14]

[[countries]]
id = 17
name = "Montgomery_Burns"
continent = 3
x = 315
y = 66
cardtype = "Infantry"
connections = [20, 18, 23, 22]

[[countries]]
id = 18
name = "Castulo_Smithers"
continent = 3
x = 349
y = 85
cardtype = "Cannon"
connections = [17, 22, 23, 19, 21]

[[countries]]
id = 19
name = "Alcalde_Diamante"
continent = 3
x = 452
y = 82
cardtype = "Cavalry"
connections = [22, 18, 2, 8, 21]

[[countries]]
id = 20
name = "Dr._Julius_Hilbbert"
continent = 3
x = 213
y = 155
cardtype = "Infantry"
connections = [27, 23, 17, 33]

[[countries]]
id = 21
name = "Profesor_Frink"
continent = 3
x = 455
y = 150
cardtype = "Cannon"
connections = [22, 18, 19, 37, 10, 6, 8]

[[countries]]
id = 22
name = "Jefe_Gorgori"
continent = 3
x = 347
y = 163
cardtype = "Cavalry"
connections = [17, 23, 35, 37, 21, 19, 18]

[[countries]]
id = 23
name = "Apu_Nahasapeemapetilon"
continent = 3
x = 276
y = 161
cardtype = "Infantry"
connections = [20, 17, 22, 33, 35, 18]

[[countries]]
id = 24
name = "Milhouse_Van_Houten"
continent = 4
x = 121
y = 126
cardtype = "Cannon"
connections = [29, 25, 26, 30, 27]

[[countries]]
id = 25
name = "Rafa_Gorgory"
continent = 4
x = 56
y = 121
cardtype = "Cavalry"
connections = [29, 24, 31, 30]

[[countries]]
id = 26
name = "Nelson_Rufino"
continent = 4
x = 152
y = 89
cardtype = "Infantry"
connections = [24, 27]

[[countries]]
id = 27
name = "Jimbo_Jones"
continent = 4
x = 191
y = 40
cardtype = "Cannon"
connections = [30, 24, 20, 26]

[[countries]]
id = 28
name = "Edna_Krabappel"
continent = 4
x = 26
y = 251
cardtype = "Cavalry"
connections = [39, 32, 29]

[[countries]]
id = 29
name = "Jardinero_Willie"
continent = 4
x = 22
y = 175
cardtype = "Infantry"
connections = [28, 32, 24, 25]

[[countries]]
id = 30
name = "Otto"
continent = 4
x = 128
y = 20
cardtype = "Cannon"
connections = [25, 24, 31, 27]

[[countries]]
id = 31
name = "Doris"
continent = 4
x = 62
y = 56
cardtype = "Cavalry"
connections = [25, 30, 11]

[[countries]]
id = 32
name = "Seymour_Skinner"
continent = 4
x = 123
y = 172
cardtype = "Infantry"
connections = [28, 29]

[[countries]]
id = 33
name = "Krusty_el_payaso"
continent = 5
x = 289
y = 269
cardtype = "Cannon"
connections = [42, 20, 23, 38, 35]

[[countries]]
id = 34
name = "Mel_Patiño"
continent = 5
x = 353
y = 398
cardtype = "Cavalry"
connections = [38, 36]

[[countries]]
id = 35
name = "Kent_Brockman"
continent = 5
x = 316
y = 251
cardtype = "Infantry"
connections = [23, 22, 37, 38, 33, 36]

[[countries]]
id = 36
name = "Troy_McClure"
continent = 5
x = 415
y = 325
cardtype = "Cannon"
connections = [37, 38, 34, 35]

[[countries]]
id = 37
name = "El_hombre_abejorro"
continent = 5
x = 415
y = 258
cardtype = "Cavalry"
connections = [22, 21, 6, 35, 36]

[[countries]]
id = 38
name = "Bob_Patiño"
continent = 5
x = 348
y = 340
cardtype = "Infantry"
connections = [36, 35, 34, 33]

[[countries]]
id = 39
name = "Moe_Szyslak"
continent = 6
x = 108
y = 292
cardtype = "Cannon"
connections = [42, 40, 28]

[[countries]]
id = 40
name = "Barney_Gomes"
continent = 6
x = 28
y = 367
cardtype = "Cavalry"
connections = [42, 39, 41]

[[countries]]
id = 41
name = "Lenny_Leonard"
continent = 6
x = 106
y = 400
cardtype = "Infantry"
connections = [42, 40]

[[countries]]
id = 42
name = "Carl_Carlson"
continent = 6
x = 154
y = 342
cardtype = "Cannon"
connections = [41, 40, 39, 33]
