[info]
name = "unknown"

[files]
pic = "usa8regions_pic.png"
map = "usa8regions_map.gif"
crd = "usa8regions.cards"

[[continents]]
id = 1
name = "Pacific"
bonus = 3
color = "green"

[[continents]]
id = 2
name = "Mountain"
bonus = 3
color = "red"

[[continents]]
id = 3
name = "Southwest"
bonus = 2
color = "yellow"

[[continents]]
id = 4
name = "Plains"
bonus = 4
color = "purple"

[[continents]]
id = 5
name = "Great_Lakes"
bonus = 3
color = "blue"

[[continents]]
id = 6
name = "South"
bonus = 6
color = "teal"

[[continents]]
id = 7
name = "Mid-Atlantic"
bonus = 3
color = "cyan"

[[continents]]
id = 8
name = "New_England"
bonus = 3
color = "orange"

[[countries]]
id = 1
name = "Alaska"
continent = 1
x = 116
y = 349
connections = [3]

[[countries]]
id = 2
name = "Hawaii"
continent = 1
x = 55
y = 292
connections = [5]

[[countries]]
id = 3
name = "Washington"
continent = 1
x = 101
y = 48
connections = [1, 4, 7]

[[countries]]
id = 4
name = "Oregon"
continent = 1
x = 87
y = 96
connections = [3, 5, 6, 7]

[[countries]]
id = 5
name = "California"
continent = 1
x = 66
y = 204
connections = [2, 4, 6, 12]

[[countries]]
id = 6
name = "Nevada"
continent = 2
x = 114
y = 174
connections = [4, 7, 10, 12, 5]

[[countries]]
id = 7
name = "Idaho"
continent = 2
x = 153
y = 123
connections = [3, 4, 6, 8, 9, 10]

[[countries]]
id = 8
name = "Montana"
continent = 2
x = 208
y = 74
connections = [7, 9, 18, 19]

[[countries]]
id = 9
name = "Wyoming"
continent = 2
x = 226
y = 139
connections = [7, 8, 10, 11, 17, 18]

[[countries]]
id = 10
name = "Utah"
continent = 2
x = 173
y = 191
connections = [6, 7, 9, 11, 12]

[[countries]]
id = 11
name = "Colorado"
continent = 2
x = 242
y = 204
connections = [9, 10, 13, 15, 16, 17]

[[countries]]
id = 12
name = "Arizona"
continent = 3
x = 158
y = 270
connections = [6, 5, 10, 13]

[[countries]]
id = 13
name = "New_Mexico"
continent = 3
x = 229
y = 276
connections = [11, 12, 14, 15]

[[countries]]
id = 14
name = "Texas"
continent = 3
x = 317
y = 332
connections = [13, 15, 30, 31]

[[countries]]
id = 15
name = "Oklahoma"
continent = 3
x = 342
y = 265
connections = [11, 13, 14, 16, 22, 30]

[[countries]]
id = 16
name = "Kansas"
continent = 4
x = 329
y = 217
connections = [11, 15, 17, 22]

[[countries]]
id = 17
name = "Nebraska"
continent = 4
x = 316
y = 170
connections = [9, 11, 16, 18, 21, 22]

[[countries]]
id = 18
name = "South_Dakota"
continent = 4
x = 311
y = 125
connections = [8, 9, 17, 19, 20, 21]

[[countries]]
id = 19
name = "North_Dakota"
continent = 4
x = 312
y = 80
connections = [8, 18, 20]

[[countries]]
id = 20
name = "Minnesota"
continent = 4
x = 373
y = 104
connections = [18, 19, 21, 24]

[[countries]]
id = 21
name = "Iowa"
continent = 4
x = 384
y = 164
connections = [17, 18, 20, 22, 23, 24]

[[countries]]
id = 22
name = "Missouri"
continent = 4
x = 399
y = 219
connections = [15, 16, 17, 21, 23, 28, 29, 30]

[[countries]]
id = 23
name = "Illinois"
continent = 5
x = 436
y = 190
connections = [21, 22, 24, 26, 28]

[[countries]]
id = 24
name = "Wisconsin"
continent = 5
x = 426
y = 123
connections = [20, 21, 23, 25]

[[countries]]
id = 25
name = "Michigan"
continent = 5
x = 485
y = 141
connections = [24, 26, 27]

[[countries]]
id = 26
name = "Indiana"
continent = 5
x = 473
y = 189
connections = [23, 25, 27, 28]

[[countries]]
id = 27
name = "Ohio"
continent = 5
x = 511
y = 181
connections = [25, 26, 28, 39, 42]

[[countries]]
id = 28
name = "Kentucky"
continent = 6
x = 495
y = 224
connections = [22, 23, 26, 27, 29, 38, 39]

[[countries]]
id = 29
name = "Tennessee"
continent = 6
x = 476
y = 254
connections = [22, 28, 30, 32, 33, 35, 37, 38]

[[countries]]
id = 30
name = "Arkansas"
continent = 6
x = 401
y = 274
connections = [14, 15, 22, 29, 32, 31]

[[countries]]
id = 31
name = "Louisiana"
continent = 6
x = 402
y = 333
connections = [14, 30, 32]

[[countries]]
id = 32
name = "Mississippi"
continent = 6
x = 439
y = 304
connections = [29, 30, 31, 33]

[[countries]]
id = 33
name = "Alabama"
continent = 6
x = 475
y = 301
connections = [29, 32, 35, 34]

[[countries]]
id = 34
name = "Florida"
continent = 6
x = 556
y = 368
connections = [33, 35]

[[countries]]
id = 35
name = "Georgia"
continent = 6
x = 521
y = 301
connections = [29, 33, 34, 36, 37]

[[countries]]
id = 36
name = "South_Carolina"
continent = 6
x = 552
y = 275
connections = [35, 37]

[[countries]]
id = 37
name = "North_Carolina"
continent = 6
x = 572
y = 246
connections = [29, 35, 36, 38]

[[countries]]
id = 38
name = "Virginia"
continent = 6
x = 569
y = 212
connections = [28, 29, 37, 39, 40]

[[countries]]
id = 39
name = "West_Virginia"
continent = 7
x = 537
y = 204
connections = [27, 28, 38, 42, 40]

[[countries]]
id = 40
name = "Maryland"
continent = 7
x = 587
y = 189
connections = [38, 39, 41, 42]

[[countries]]
id = 41
name = "Delaware"
continent = 7
x = 630
y = 188
connections = [40, 43, 42]

[[countries]]
id = 42
name = "Pennsylvania"
continent = 7
x = 566
y = 162
connections = [27, 39, 40, 41, 44, 43]

[[countries]]
id = 43
name = "New_Jersey"
continent = 7
x = 618
y = 168
connections = [41, 42, 44]

[[countries]]
id = 44
name = "New_York"
continent = 7
x = 589
y = 123
connections = [42, 43, 45, 47, 48]

[[countries]]
id = 45
name = "Connecticut"
continent = 8
x = 628
y = 148
connections = [44, 46, 47]

[[countries]]
id = 46
name = "Rhode_Island"
continent = 8
x = 652
y = 150
connections = [45, 47]

[[countries]]
id = 47
name = "Massachusetts"
continent = 8
x = 654
y = 127
connections = [44, 45, 46, 49, 48]

[[countries]]
id = 48
name = "Vermont"
continent = 8
x = 611
y = 80
connections = [44, 47, 49]

[[countries]]
id = 49
name = "New_Hampshire"
continent = 8
x = 637
y = 108
connections = [47, 48, 50]

[[countries]]
id = 50
name = "Maine"
continent = 8
x = 646
y = 70
connections = [49]
