[info]
name = "unknown"

[files]
pic = "benelux_pic.jpg"
map = "benelux_map.gif"
crd = "benelux.cards"

[[continents]]
id = 1
name = "Holland"
bonus = 4
color = "#ff3333"

[[continents]]
id = 2
name = "Oost_nederland"
bonus = 5
color = "green"

[[continents]]
id = 3
name = "Zuid_nederland"
bonus = 3
color = "#3399ff"

[[continents]]
id = 4
name = "Vlaanderen"
bonus = 4
color = "#ffff99"

[[continents]]
id = 5
name = "Walonie"
bonus = 4
color = "#cc9900"

[[continents]]
id = 6
name = "luxemburg"
bonus = 2
color = "#999999"

[[countries]]
id = 1
name = "Noord_holland"
continent = 1
x = 450
y = 164
connections = [5, 4, 3, 2]

[[countries]]
id = 2
name = "Zuid_Holland"
continent = 1
x = 382
y = 131
connections = [1, 3, 11, 12]

[[countries]]
id = 3
name = "Utrecht"
continent = 1
x = 421
y = 214
connections = [1, 2, 4, 9, 11]

[[countries]]
id = 4
name = "Flevoland"
continent = 1
x = 476
y = 209
connections = [1, 3, 5, 8, 9]

[[countries]]
id = 5
name = "Friesland"
continent = 2
x = 584
y = 205
connections = [1, 4, 6, 7, 8]

[[countries]]
id = 6
name = "Groningen"
continent = 2
x = 627
y = 284
connections = [5, 7]

[[countries]]
id = 7
name = "Drente"
continent = 2
x = 559
y = 292
connections = [5, 6, 8]

[[countries]]
id = 8
name = "Overijsel"
continent = 2
x = 504
y = 266
connections = [4, 5, 7, 9]

[[countries]]
id = 9
name = "Gelderland"
continent = 2
x = 429
y = 313
connections = [3, 4, 8, 11]

[[countries]]
id = 10
name = "NL_Limburg"
continent = 3
x = 236
y = 306
connections = [11, 14, 20]

[[countries]]
id = 11
name = "Noord_Braband"
continent = 3
x = 348
y = 229
connections = [2, 3, 9, 10, 14, 13, 12]

[[countries]]
id = 12
name = "Zeeland"
continent = 3
x = 288
y = 88
connections = [2, 11, 16, 15, 13]

[[countries]]
id = 13
name = "Antwerpen"
continent = 4
x = 265
y = 166
connections = [11, 12, 15, 17, 14]

[[countries]]
id = 14
name = "B._limburg"
continent = 4
x = 237
y = 271
connections = [10, 11, 13, 20, 17]

[[countries]]
id = 15
name = "Oost-Vlaanderen"
continent = 4
x = 209
y = 118
connections = [12, 13, 16, 19, 17]

[[countries]]
id = 16
name = "West-vlaandren"
continent = 4
x = 172
y = 36
connections = [12, 15, 19]

[[countries]]
id = 17
name = "Vlaams-Braband"
continent = 4
x = 193
y = 177
connections = [13, 14, 15, 20, 18, 19]

[[countries]]
id = 18
name = "Brabant_wallon"
continent = 5
x = 172
y = 206
connections = [17, 19, 22, 20]

[[countries]]
id = 19
name = "Hainaut"
continent = 5
x = 117
y = 144
connections = [15, 16, 17, 18, 22]

[[countries]]
id = 20
name = "Liège"
continent = 5
x = 190
y = 315
connections = [10, 14, 17, 18, 22, 21, 23]

[[countries]]
id = 21
name = "Luxembourg"
continent = 5
x = 73
y = 295
connections = [20, 22, 23, 24]

[[countries]]
id = 22
name = "Namur"
continent = 5
x = 108
y = 242
connections = [18, 19, 20, 21]

[[countries]]
id = 23
name = "Ösling"
continent = 6
x = 108
y = 352
connections = [20, 21, 24]

[[countries]]
id = 24
name = "Gutland"
continent = 6
x = 33
y = 380
connections = [21, 23]
