[info]
name = "unknown"
nb_wildcards = 2

[[continents]]
id = 1
name = "EASTERN_KINGDOMS"
bonus = 5
color = "red"

[[continents]]
id = 2
name = "KALIMDOR"
bonus = 5
color = "yellow"

[[continents]]
id = 3
name = "NORTHREND"
bonus = 5
color = "blue"

[[countries]]
id = 1
name = "Alterac_Mountains"
continent = 1
x = 514
y = 176
cardtype = "Cavalry"
connections = [19, 16, 20, 23]

[[countries]]
id = 2
name = "Arathi_Highlands"
continent = 1
x = 539
y = 205
cardtype = "Infantry"
connections = [23, 22]

[[countries]]
id = 3
name = "Badlands"
continent = 1
x = 549
y = 287
cardtype = "Cannon"
connections = [13, 15]

[[countries]]
id = 4
name = "Blasted_Lands"
continent = 1
x = 548
y = 357
cardtype = "Cavalry"
connections = [18]

[[countries]]
id = 5
name = "Burning_Steps"
continent = 1
x = 526
y = 303
cardtype = "Infantry"
connections = [15, 14]

[[countries]]
id = 6
name = "Dun_Morogh"
continent = 1
x = 502
y = 261
cardtype = "Cavalry"
connections = [13, 15, 9]

[[countries]]
id = 7
name = "Duskwood"
continent = 1
x = 510
y = 343
cardtype = "Infantry"
connections = [9, 21, 17, 18]

[[countries]]
id = 8
name = "Eastern_Plaguelands"
continent = 1
x = 565
y = 149
cardtype = "Cannon"
connections = [11, 20, 12]

[[countries]]
id = 9
name = "Elwynn_Forest"
continent = 1
x = 502
y = 319
cardtype = "Cavalry"
connections = [14, 7, 21, 6]

[[countries]]
id = 10
name = "Eversong_Woods"
continent = 1
x = 569
y = 90
cardtype = "Infantry"
connections = [11, 19]

[[countries]]
id = 11
name = "Ghostlands"
continent = 1
x = 570
y = 115
cardtype = "Cannon"
connections = [10, 8]

[[countries]]
id = 12
name = "The_Hinterlands"
continent = 1
x = 555
y = 181
cardtype = "Cavalry"
connections = [8, 23]

[[countries]]
id = 13
name = "Loch_Modan"
continent = 1
x = 555
y = 267
cardtype = "Infantry"
connections = [22, 6, 3]

[[countries]]
id = 14
name = "Redridge_Mountains"
continent = 1
x = 540
y = 322
cardtype = "Cannon"
connections = [5, 9]

[[countries]]
id = 15
name = "Searing_Gorge"
continent = 1
x = 516
y = 286
cardtype = "Cavalry"
connections = [3, 6, 5]

[[countries]]
id = 16
name = "Silverpine_Forest"
continent = 1
x = 485
y = 182
cardtype = "Infantry"
connections = [19, 24, 23, 1]

[[countries]]
id = 17
name = "Stranglethorn_Vale"
continent = 1
x = 513
y = 371
cardtype = "Cannon"
connections = [7, 46, 32, 19, 28]

[[countries]]
id = 18
name = "Swamp_of_Sorrows"
continent = 1
x = 557
y = 336
cardtype = "Cavalry"
connections = [4, 7]

[[countries]]
id = 19
name = "Tirisfal_Glades"
continent = 1
x = 492
y = 149
cardtype = "Infantry"
connections = [52, 16, 1, 20, 32, 10, 17]

[[countries]]
id = 20
name = "Western_Plaguelands"
continent = 1
x = 529
y = 152
cardtype = "Cannon"
connections = [19, 1, 8]

[[countries]]
id = 21
name = "Westfall"
continent = 1
x = 481
y = 343
cardtype = "Cavalry"
connections = [9, 7]

[[countries]]
id = 22
name = "Wetlands"
continent = 1
x = 532
y = 236
cardtype = "Infantry"
connections = [2, 13, 57, 33, 30]

[[countries]]
id = 23
name = "Hilsbrad_Foothils"
continent = 1
x = 507
y = 195
cardtype = "Cannon"
connections = [16, 12, 2, 1]

[[countries]]
id = 24
name = "Gilneas"
continent = 1
x = 475
y = 218
cardtype = "Cavalry"
connections = [16]

[[countries]]
id = 25
name = "Ashenvale"
continent = 2
x = 155
y = 219
cardtype = "Infantry"
connections = [30, 34, 26, 28]

[[countries]]
id = 26
name = "Azshara"
continent = 2
x = 222
y = 206
cardtype = "Cannon"
connections = [25]

[[countries]]
id = 27
name = "Azuremyst_Isle"
continent = 2
x = 59
y = 170
cardtype = "Cavalry"
connections = [30, 29]

[[countries]]
id = 28
name = "The_Barrens"
continent = 2
x = 177
y = 261
cardtype = "Infantry"
connections = [25, 40, 33, 32, 38, 43, 46, 17]

[[countries]]
id = 29
name = "Bloodmyst_Isle"
continent = 2
x = 48
y = 137
cardtype = "Cannon"
connections = [27]

[[countries]]
id = 30
name = "Darkshore"
continent = 2
x = 148
y = 151
cardtype = "Cavalry"
connections = [42, 27, 25, 47, 22]

[[countries]]
id = 31
name = "Desolace"
continent = 2
x = 116
y = 277
cardtype = "Infantry"
connections = [40, 35]

[[countries]]
id = 32
name = "Durotar"
continent = 2
x = 213
y = 246
cardtype = "Cannon"
connections = [17, 19, 28]

[[countries]]
id = 33
name = "Dustwallow_Marsh"
continent = 2
x = 194
y = 308
cardtype = "Cavalry"
connections = [28, 22]

[[countries]]
id = 34
name = "Felwood"
continent = 2
x = 160
y = 164
cardtype = "Infantry"
connections = [25, 37, 45]

[[countries]]
id = 35
name = "Feralas"
continent = 2
x = 122
y = 320
cardtype = "Cannon"
connections = [31, 43]

[[countries]]
id = 36
name = "Hyjal"
continent = 2
x = 180
y = 181
cardtype = "Cavalry"
connections = [45]

[[countries]]
id = 37
name = "Moonglade"
continent = 2
x = 186
y = 136
cardtype = "Infantry"
connections = [34, 45]

[[countries]]
id = 38
name = "Mulgore"
continent = 2
x = 152
y = 287
cardtype = "Cannon"
connections = [28]

[[countries]]
id = 39
name = "Silithus"
continent = 2
x = 133
y = 361
cardtype = "Cavalry"
connections = [44]

[[countries]]
id = 40
name = "Stonetalon_Mountains"
continent = 2
x = 132
y = 236
cardtype = "Infantry"
connections = [28, 31]

[[countries]]
id = 41
name = "Tanaris"
continent = 2
x = 198
y = 383
cardtype = "Cannon"
connections = [43, 44]

[[countries]]
id = 42
name = "Teldrassil"
continent = 2
x = 124
y = 106
cardtype = "Cavalry"
connections = [30]

[[countries]]
id = 43
name = "Thousand_Needles"
continent = 2
x = 180
y = 338
cardtype = "Infantry"
connections = [28, 35, 41]

[[countries]]
id = 44
name = "Un'Goro_Crater"
continent = 2
x = 162
y = 370
cardtype = "Cannon"
connections = [41, 39]

[[countries]]
id = 45
name = "Winterspring"
continent = 2
x = 212
y = 152
cardtype = "Cavalry"
connections = [34, 36, 37]

[[countries]]
id = 46
name = "Zandalar"
continent = 1
x = 369
y = 343
cardtype = "Infantry"
connections = [17, 28]

[[countries]]
id = 47
name = "Borean_Tundra"
continent = 3
x = 304
y = 65
cardtype = "Cannon"
connections = [48, 54, 50, 30]

[[countries]]
id = 48
name = "Coldarra"
continent = 3
x = 275
y = 64
cardtype = "Cavalry"
connections = [47]

[[countries]]
id = 49
name = "Crystalsong_Forest"
continent = 3
x = 364
y = 30
cardtype = "Infantry"
connections = [53, 50, 55, 56]

[[countries]]
id = 50
name = "Dragonblight"
continent = 3
x = 355
y = 58
cardtype = "Cannon"
connections = [47, 53, 49, 56, 51]

[[countries]]
id = 51
name = "Grizzly_Hills"
continent = 3
x = 405
y = 59
cardtype = "Cavalry"
connections = [50, 56, 52]

[[countries]]
id = 52
name = "Howling_Fjord"
continent = 3
x = 429
y = 82
cardtype = "Infantry"
connections = [51, 19]

[[countries]]
id = 53
name = "IceCrown_Glacier"
continent = 3
x = 336
y = 21
cardtype = "Cannon"
connections = [54, 50, 49]

[[countries]]
id = 54
name = "Sholazar_Basin"
continent = 3
x = 305
y = 34
cardtype = "Cavalry"
connections = [47, 53]

[[countries]]
id = 55
name = "The_Storm_Peaks"
continent = 3
x = 385
y = 14
cardtype = "Infantry"
connections = [49, 56]

[[countries]]
id = 56
name = "Zul'Drak"
continent = 3
x = 398
y = 39
cardtype = "Cannon"
connections = [50, 49, 51, 55]

[[countries]]
id = 57
name = "Grim_Batol"
continent = 1
x = 576
y = 249
cardtype = "Cavalry"
connections = [22]
