[info]
name = "Axis and Allies Map"
nb_wildcards = 2

[[continents]]
id = 1
name = "America"
bonus = 5
color = "green"

[[continents]]
id = 2
name = "Germany"
bonus = 3
color = "blue"

[[continents]]
id = 3
name = "United-Kingdom"
bonus = 7
color = "#A52A2A"

[[continents]]
id = 4
name = "Russia"
bonus = 3
color = "red"

[[continents]]
id = 5
name = "Japan"
bonus = 4
color = "yellow"

[[continents]]
id = 6
name = "Neutrals"
bonus = 9
color = "#D2B48C"

[[countries]]
id = 1
name = "Eastern-Canada"
continent = 3
x = 58
y = 114
cardtype = "Infantry"
connections = [2, 9, 66]

[[countries]]
id = 2
name = "Eastern-USA"
continent = 1
x = 24
y = 163
cardtype = "Cannon"
connections = [1, 3, 67]

[[countries]]
id = 3
name = "West-Indies"
continent = 1
x = 47
y = 208
cardtype = "Infantry"
connections = [2]

[[countries]]
id = 4
name = "Panama"
continent = 1
x = 12
y = 219
cardtype = "Infantry"
connections = [5, 68]

[[countries]]
id = 5
name = "Venezuela"
continent = 6
x = 35
y = 242
cardtype = "Cavalry"
connections = [4, 6, 8]

[[countries]]
id = 6
name = "Peru"
continent = 6
x = 27
y = 280
cardtype = "Cavalry"
connections = [7, 5, 8]

[[countries]]
id = 7
name = "Argentina"
continent = 6
x = 44
y = 339
cardtype = "Cavalry"
connections = [6, 8]

[[countries]]
id = 8
name = "Brazil"
continent = 1
x = 78
y = 276
cardtype = "Cannon"
connections = [5, 6, 7]

[[countries]]
id = 9
name = "Eire"
continent = 3
x = 139
y = 75
cardtype = "Cannon"
connections = [1, 10]

[[countries]]
id = 10
name = "United-Kingdom"
continent = 3
x = 159
y = 88
cardtype = "Cannon"
connections = [9, 15]

[[countries]]
id = 11
name = "Finland-Norway"
continent = 2
x = 227
y = 51
cardtype = "Cavalry"
connections = [12, 22]

[[countries]]
id = 12
name = "Sweden"
continent = 6
x = 202
y = 74
cardtype = "Cannon"
connections = [11]

[[countries]]
id = 13
name = "Gibraltar"
continent = 3
x = 148
y = 164
cardtype = "Infantry"
connections = [14]

[[countries]]
id = 14
name = "Spain"
continent = 6
x = 149
y = 140
cardtype = "Infantry"
connections = [13, 15]

[[countries]]
id = 15
name = "Western-Europe"
continent = 2
x = 174
y = 118
cardtype = "Cannon"
connections = [10, 14, 16, 17, 18]

[[countries]]
id = 16
name = "Germany"
continent = 2
x = 200
y = 102
cardtype = "Cannon"
connections = [15, 17, 18, 19]

[[countries]]
id = 17
name = "Switzerland"
continent = 6
x = 184
y = 124
cardtype = "Cavalry"
connections = [15, 16, 18]

[[countries]]
id = 18
name = "Southern-Europe"
continent = 2
x = 205
y = 133
cardtype = "Cavalry"
connections = [15, 16, 17, 19]

[[countries]]
id = 19
name = "Eastern-Europe"
continent = 2
x = 234
y = 101
cardtype = "Infantry"
connections = [16, 18, 20, 22]

[[countries]]
id = 20
name = "Ukraine"
continent = 2
x = 258
y = 96
cardtype = "Cavalry"
connections = [19, 21, 22]

[[countries]]
id = 21
name = "Caucasus"
continent = 4
x = 281
y = 86
cardtype = "Infantry"
connections = [20, 22, 23, 42, 45]

[[countries]]
id = 22
name = "Karelia"
continent = 4
x = 267
y = 49
cardtype = "Infantry"
connections = [11, 19, 20, 21, 23]

[[countries]]
id = 23
name = "Russia"
continent = 4
x = 320
y = 78
cardtype = "Cavalry"
connections = [21, 22, 24, 25, 26]

[[countries]]
id = 24
name = "Evenki-Natl-Okrug"
continent = 4
x = 382
y = 55
cardtype = "Cannon"
connections = [23, 25, 27]

[[countries]]
id = 25
name = "Novosibirsk"
continent = 4
x = 362
y = 112
cardtype = "Cannon"
connections = [23, 24, 26, 27, 48, 49]

[[countries]]
id = 26
name = "Kazakh"
continent = 4
x = 323
y = 137
cardtype = "Infantry"
connections = [23, 25, 45, 46, 48]

[[countries]]
id = 27
name = "Yakut"
continent = 4
x = 432
y = 54
cardtype = "Cannon"
connections = [24, 25, 28, 49, 51]

[[countries]]
id = 28
name = "Soviet-Far-East"
continent = 4
x = 494
y = 44
cardtype = "Cavalry"
connections = [27, 51, 65]

[[countries]]
id = 29
name = "Algeria"
continent = 2
x = 169
y = 185
cardtype = "Cavalry"
connections = [31, 32, 33]

[[countries]]
id = 30
name = "Rio-De-Oro"
continent = 6
x = 130
y = 222
cardtype = "Infantry"
connections = [31]

[[countries]]
id = 31
name = "West-Africa"
continent = 3
x = 150
y = 231
cardtype = "Cannon"
connections = [29, 30, 33]

[[countries]]
id = 32
name = "Libya"
continent = 2
x = 204
y = 210
cardtype = "Infantry"
connections = [29, 33, 34]

[[countries]]
id = 33
name = "Equatoral-Africa"
continent = 3
x = 195
y = 238
cardtype = "Cannon"
connections = [29, 31, 32, 34, 35]

[[countries]]
id = 34
name = "Egypt-Sudan"
continent = 3
x = 242
y = 217
cardtype = "Cavalry"
connections = [32, 33, 35, 36, 37, 43]

[[countries]]
id = 35
name = "Congo"
continent = 3
x = 218
y = 282
cardtype = "Infantry"
connections = [33, 34, 36, 38]

[[countries]]
id = 36
name = "Kenya-Rhodesia"
continent = 3
x = 248
y = 296
cardtype = "Cannon"
connections = [34, 35, 37, 38, 39, 40]

[[countries]]
id = 37
name = "East-Africa"
continent = 3
x = 280
y = 254
cardtype = "Infantry"
connections = [34, 36]

[[countries]]
id = 38
name = "Angola"
continent = 6
x = 217
y = 318
cardtype = "Cavalry"
connections = [35, 36, 39]

[[countries]]
id = 39
name = "South-Africa"
continent = 3
x = 235
y = 347
cardtype = "Cavalry"
connections = [36, 38, 40, 41]

[[countries]]
id = 40
name = "Mozambique"
continent = 6
x = 258
y = 335
cardtype = "Cavalry"
connections = [36, 39]

[[countries]]
id = 41
name = "Madagascar"
continent = 3
x = 280
y = 355
cardtype = "Cannon"
connections = [39]

[[countries]]
id = 42
name = "Turkey"
continent = 6
x = 261
y = 153
cardtype = "Infantry"
connections = [21, 43, 45]

[[countries]]
id = 43
name = "Syria"
continent = 3
x = 264
y = 182
cardtype = "Infantry"
connections = [34, 42, 44, 45]

[[countries]]
id = 44
name = "Saudi-Arabia"
continent = 3
x = 293
y = 201
cardtype = "Infantry"
connections = [43, 45]

[[countries]]
id = 45
name = "Persia"
continent = 3
x = 297
y = 162
cardtype = "Infantry"
connections = [21, 26, 42, 43, 44, 46, 47]

[[countries]]
id = 46
name = "Afghan"
continent = 6
x = 326
y = 165
cardtype = "Infantry"
connections = [26, 45, 47, 48]

[[countries]]
id = 47
name = "India"
continent = 3
x = 355
y = 196
cardtype = "Infantry"
connections = [45, 46, 48, 53]

[[countries]]
id = 48
name = "Sinkiang"
continent = 1
x = 384
y = 146
cardtype = "Infantry"
connections = [25, 26, 46, 47, 49, 50, 53]

[[countries]]
id = 49
name = "Mongolia"
continent = 6
x = 411
y = 114
cardtype = "Cavalry"
connections = [25, 27, 48, 50, 51]

[[countries]]
id = 50
name = "China"
continent = 1
x = 414
y = 150
cardtype = "Cavalry"
connections = [48, 49, 51, 52, 53]

[[countries]]
id = 51
name = "Manchuria"
continent = 5
x = 460
y = 121
cardtype = "Cavalry"
connections = [27, 28, 49, 50, 52, 54]

[[countries]]
id = 52
name = "Kwangtung"
continent = 5
x = 440
y = 178
cardtype = "Cavalry"
connections = [50, 51, 53]

[[countries]]
id = 53
name = "Indochina"
continent = 5
x = 404
y = 207
cardtype = "Cavalry"
connections = [47, 48, 50, 52, 55, 59, 60]

[[countries]]
id = 54
name = "Japan"
continent = 5
x = 493
y = 148
cardtype = "Cavalry"
connections = [51, 56, 58]

[[countries]]
id = 55
name = "Philipines"
continent = 5
x = 456
y = 226
cardtype = "Cannon"
connections = [53, 57]

[[countries]]
id = 56
name = "Okinawa"
continent = 5
x = 488
y = 195
cardtype = "Cannon"
connections = [54]

[[countries]]
id = 57
name = "Carolines"
continent = 5
x = 506
y = 236
cardtype = "Cannon"
connections = [55]

[[countries]]
id = 58
name = "Wake"
continent = 5
x = 528
y = 197
cardtype = "Cannon"
connections = [54]

[[countries]]
id = 59
name = "East-Indies"
continent = 5
x = 403
y = 276
cardtype = "Cannon"
connections = [53, 63]

[[countries]]
id = 60
name = "Borneo"
continent = 5
x = 437
y = 258
cardtype = "Cannon"
connections = [53, 61]

[[countries]]
id = 61
name = "New-Guinea"
continent = 5
x = 462
y = 281
cardtype = ""
connections = [60, 62]

[[countries]]
id = 62
name = "Solomans"
continent = 5
x = 532
y = 285
cardtype = ""
connections = [61]

[[countries]]
id = 63
name = "Australia"
continent = 3
x = 455
y = 337
cardtype = ""
connections = [59, 64]

[[countries]]
id = 64
name = "New-Zealand"
continent = 3
x = 540
y = 364
cardtype = ""
connections = [63]

[[countries]]
id = 65
name = "Alaska"
continent = 1
x = 567
y = 64
cardtype = ""
connections = [28, 66]

[[countries]]
id = 66
name = "Western-Canada"
continent = 3
x = 642
y = 82
cardtype = ""
connections = [1, 65, 67]

[[countries]]
id = 67
name = "Western-USA"
continent = 1
x = 646
y = 144
cardtype = ""
connections = [2, 66, 68, 69]

[[countries]]
id = 68
name = "Mexico"
continent = 1
x = 654
y = 194
cardtype = ""
connections = [4, 67, 70]

[[countries]]
id = 69
name = "Midway"
continent = 1
x = 566
y = 150
cardtype = ""
connections = [67]

[[countries]]
id = 70
name = "Hawaii"
continent = 1
x = 589
y = 212
cardtype = ""
connections = [68]
