[info]
name = "unknown"

[files]
pic = "Calw_pic.png"
map = "Calw_map.gif"
crd = "Calw.cards"

[[continents]]
id = 1
name = "Region_Calw"
bonus = 5
color = "#ff8180"

[[continents]]
id = 2
name = "Region_Nagold"
bonus = 3
color = "#e780ff"

[[continents]]
id = 3
name = "Region_Bad_Wildbad"
bonus = 2
color = "#ffaf80"

[[countries]]
id = 1
name = "Unterreichenbach"
continent = 1
x = 392
y = 20
connections = [23, 2]

[[countries]]
id = 2
name = "Bad_Liebenzell"
continent = 1
x = 422
y = 87
connections = [1, 23, 4, 5, 3, 6]

[[countries]]
id = 3
name = "Simmozheim"
continent = 1
x = 484
y = 115
connections = [2, 6, 7]

[[countries]]
id = 4
name = "Oberreichenbach"
continent = 1
x = 331
y = 135
connections = [2, 11, 23, 24, 9, 5]

[[countries]]
id = 5
name = "Calw"
continent = 1
x = 423
y = 158
connections = [2, 6, 9, 10, 12, 8, 4]

[[countries]]
id = 6
name = "Althengstett"
continent = 1
x = 472
y = 149
connections = [2, 3, 7, 5, 8]

[[countries]]
id = 7
name = "Ostelsheim"
continent = 1
x = 510
y = 137
connections = [3, 6, 8]

[[countries]]
id = 8
name = "Gechingen"
continent = 1
x = 495
y = 181
connections = [7, 6, 5, 12]

[[countries]]
id = 9
name = "Bad_Teinach"
continent = 1
x = 357
y = 162
connections = [4, 11, 10, 5]

[[countries]]
id = 10
name = "Neubulach"
continent = 1
x = 379
y = 219
connections = [9, 5, 12, 11, 14]

[[countries]]
id = 11
name = "Neuweiler"
continent = 1
x = 306
y = 222
connections = [4, 9, 10, 24, 13, 14]

[[countries]]
id = 12
name = "Wildberg"
continent = 2
x = 427
y = 263
connections = [5, 8, 10, 14, 18, 15]

[[countries]]
id = 13
name = "Simmersfeld"
continent = 2
x = 249
y = 261
connections = [11, 24, 25, 14]

[[countries]]
id = 14
name = "Altensteig"
continent = 2
x = 322
y = 302
connections = [10, 11, 13, 17, 16, 19, 15, 12]

[[countries]]
id = 15
name = "Ebhausen"
continent = 2
x = 377
y = 277
connections = [14, 16, 18, 12]

[[countries]]
id = 16
name = "Rohrdorf"
continent = 2
x = 381
y = 325
connections = [14, 19, 18, 15]

[[countries]]
id = 17
name = "Egenhausen"
continent = 2
x = 330
y = 335
connections = [14, 19]

[[countries]]
id = 18
name = "Nagold"
continent = 2
x = 412
y = 356
connections = [19, 16, 12, 15]

[[countries]]
id = 19
name = "Haiterbach"
continent = 2
x = 348
y = 380
connections = [14, 18, 17, 16]

[[countries]]
id = 20
name = "Bad_Herrenalb"
continent = 3
x = 189
y = 58
connections = [21]

[[countries]]
id = 21
name = "Dobel"
continent = 3
x = 237
y = 53
connections = [20, 24]

[[countries]]
id = 22
name = "Höfen_an_der_Enz"
continent = 3
x = 300
y = 46
connections = [23, 24]

[[countries]]
id = 23
name = "Schömberg"
continent = 3
x = 350
y = 71
connections = [1, 2, 4, 22, 24]

[[countries]]
id = 24
name = "Bad_Wildbad"
continent = 3
x = 280
y = 101
connections = [4, 11, 23, 22, 21, 25, 13]

[[countries]]
id = 25
name = "Enzklösterle"
continent = 3
x = 207
y = 211
connections = [24, 13]
