[info]
name = "unknown"
nb_wildcards = 6

[[continents]]
id = 1
name = "Valle_di_Aosta"
bonus = 1
color = "#33ffff"

[[continents]]
id = 2
name = "Piemonte"
bonus = 4
color = "#3333ff"

[[continents]]
id = 3
name = "Lombardia"
bonus = 6
color = "#cc00cc"

[[continents]]
id = 4
name = "Trentino"
bonus = 1
color = "yellow"

[[continents]]
id = 5
name = "Veneto"
bonus = 4
color = "green"

[[continents]]
id = 6
name = "Friuli"
bonus = 2
color = "red"

[[continents]]
id = 7
name = "Liguria"
bonus = 2
color = "#0099ff"

[[continents]]
id = 8
name = "Emilia"
bonus = 5
color = "#ff3333"

[[countries]]
id = 1
name = "Aosta"
continent = 1
x = 70
y = 198
cardtype = "Cavalry"
connections = [2, 3, 5, 6]

[[countries]]
id = 2
name = "Verbano_Cusio_Ossola"
continent = 2
x = 151
y = 160
cardtype = ""
connections = [1, 5, 4, 11]

[[countries]]
id = 3
name = "Biella"
continent = 2
x = 127
y = 215
cardtype = ""
connections = [1, 6, 5]

[[countries]]
id = 4
name = "Novara"
continent = 2
x = 167
y = 221
cardtype = "Infantry"
connections = [5, 18, 17, 11, 2]

[[countries]]
id = 5
name = "Vercelli"
continent = 2
x = 144
y = 244
cardtype = "Cannon"
connections = [1, 6, 8, 18, 4, 2, 3]

[[countries]]
id = 6
name = "Torino"
continent = 2
x = 73
y = 264
cardtype = "Cavalry"
connections = [1, 3, 5, 8, 7, 9]

[[countries]]
id = 7
name = "Asti"
continent = 2
x = 134
y = 292
cardtype = "Infantry"
connections = [6, 9, 8]

[[countries]]
id = 8
name = "Alessandria"
continent = 2
x = 182
y = 303
cardtype = ""
connections = [6, 9, 7, 5, 36, 37, 39, 18]

[[countries]]
id = 9
name = "Cuneo"
continent = 2
x = 84
y = 340
cardtype = "Cannon"
connections = [6, 35, 36, 7, 8]

[[countries]]
id = 10
name = "Sondrio"
continent = 3
x = 274
y = 146
cardtype = "Cavalry"
connections = [12, 13, 14, 15, 23, 22]

[[countries]]
id = 11
name = "Varese"
continent = 3
x = 183
y = 188
cardtype = ""
connections = [4, 2, 17, 16, 12]

[[countries]]
id = 12
name = "Como"
continent = 3
x = 214
y = 173
cardtype = "Infantry"
connections = [11, 16, 13, 10]

[[countries]]
id = 13
name = "Lecco"
continent = 3
x = 237
y = 177
cardtype = ""
connections = [16, 12, 10, 14]

[[countries]]
id = 14
name = "Bergamo"
continent = 3
x = 268
y = 191
cardtype = "Cannon"
connections = [17, 13, 20, 15, 10]

[[countries]]
id = 15
name = "Brescia"
continent = 3
x = 311
y = 213
cardtype = "Cavalry"
connections = [14, 10, 23, 27, 21, 20]

[[countries]]
id = 16
name = "Monza"
continent = 3
x = 220
y = 210
cardtype = ""
connections = [17, 11, 12, 13]

[[countries]]
id = 17
name = "Milano"
continent = 3
x = 210
y = 233
cardtype = "Infantry"
connections = [4, 18, 19, 14, 16, 11, 20]

[[countries]]
id = 18
name = "Pavia"
continent = 3
x = 212
y = 268
cardtype = "Cannon"
connections = [5, 8, 4, 39, 19, 17]

[[countries]]
id = 19
name = "Lodi"
continent = 3
x = 251
y = 255
cardtype = ""
connections = [18, 17, 39, 20]

[[countries]]
id = 20
name = "Cremona"
continent = 3
x = 302
y = 267
cardtype = ""
connections = [19, 17, 14, 15, 21, 39, 40]

[[countries]]
id = 21
name = "Mantova"
continent = 3
x = 349
y = 266
cardtype = "Cavalry"
connections = [15, 27, 20, 40, 41, 42, 44, 30]

[[countries]]
id = 22
name = "Bolzano"
continent = 4
x = 405
y = 92
cardtype = ""
connections = [10, 24, 23]

[[countries]]
id = 23
name = "Trento"
continent = 4
x = 367
y = 159
cardtype = "Infantry"
connections = [10, 15, 25, 27, 24, 22]

[[countries]]
id = 24
name = "Belluno"
continent = 5
x = 465
y = 132
cardtype = "Cannon"
connections = [26, 25, 23, 22, 31, 32]

[[countries]]
id = 25
name = "Vicenza"
continent = 5
x = 410
y = 203
cardtype = ""
connections = [28, 26, 23, 27, 24]

[[countries]]
id = 26
name = "Treviso"
continent = 5
x = 471
y = 191
cardtype = ""
connections = [28, 29, 31, 24, 25]

[[countries]]
id = 27
name = "Verona"
continent = 5
x = 373
y = 233
cardtype = "Cavalry"
connections = [15, 21, 30, 28, 25, 23]

[[countries]]
id = 28
name = "Padova"
continent = 5
x = 439
y = 245
cardtype = "Infantry"
connections = [30, 27, 25, 26, 29]

[[countries]]
id = 29
name = "Venezia"
continent = 5
x = 466
y = 230
cardtype = "Cannon"
connections = [30, 28, 26, 31, 32]

[[countries]]
id = 30
name = "Rovigo"
continent = 5
x = 476
y = 279
cardtype = "Cavalry"
connections = [21, 44, 27, 28, 29]

[[countries]]
id = 31
name = "Pordenone"
continent = 6
x = 510
y = 159
cardtype = "Infantry"
connections = [29, 26, 24, 32]

[[countries]]
id = 32
name = "Udine"
continent = 6
x = 553
y = 152
cardtype = "Cannon"
connections = [29, 24, 31, 33]

[[countries]]
id = 33
name = "Gorizia"
continent = 6
x = 582
y = 182
cardtype = ""
connections = [32, 34]

[[countries]]
id = 34
name = "Trieste"
continent = 6
x = 601
y = 206
cardtype = ""
connections = [33]

[[countries]]
id = 35
name = "Imperia"
continent = 7
x = 106
y = 396
cardtype = ""
connections = [9, 36]

[[countries]]
id = 36
name = "Savona"
continent = 7
x = 143
y = 362
cardtype = "Cavalry"
connections = [9, 8, 35, 37]

[[countries]]
id = 37
name = "Genova"
continent = 7
x = 217
y = 340
cardtype = "Infantry"
connections = [8, 36, 38, 39, 40]

[[countries]]
id = 38
name = "La_Spezia"
continent = 7
x = 264
y = 368
cardtype = "Cannon"
connections = [37, 40]

[[countries]]
id = 39
name = "Piacenza"
continent = 8
x = 255
y = 295
cardtype = "Cavalry"
connections = [8, 37, 18, 19, 20, 40]

[[countries]]
id = 40
name = "Parma"
continent = 8
x = 296
y = 316
cardtype = "Infantry"
connections = [38, 37, 21, 20, 39, 41]

[[countries]]
id = 41
name = "Reggio_Emilia"
continent = 8
x = 337
y = 324
cardtype = "Cannon"
connections = [21, 40, 42]

[[countries]]
id = 42
name = "Modena"
continent = 8
x = 362
y = 335
cardtype = ""
connections = [21, 41, 44, 43]

[[countries]]
id = 43
name = "Bologna"
continent = 8
x = 402
y = 341
cardtype = "Cavalry"
connections = [42, 44, 45]

[[countries]]
id = 44
name = "Ferrara"
continent = 8
x = 447
y = 303
cardtype = "Infantry"
connections = [21, 42, 30, 43, 45]

[[countries]]
id = 45
name = "Ravenna"
continent = 8
x = 461
y = 345
cardtype = "Cannon"
connections = [44, 46, 43]

[[countries]]
id = 46
name = "Forli-Cesena"
continent = 8
x = 458
y = 387
cardtype = ""
connections = [45, 47]

[[countries]]
id = 47
name = "Rimini"
continent = 8
x = 502
y = 395
cardtype = ""
connections = [46]
