[info]
name = "unknown"

[files]
pic = "austria-hungary_pic.png"
map = "austria-hungary_map.gif"
crd = "austria-hungary.cards"

[[continents]]
id = 1
name = "Austria"
bonus = 15
color = "#ffcc00"

[[continents]]
id = 2
name = "Hungary"
bonus = 3
color = "#0099cc"

[[continents]]
id = 3
name = "Bosnia_and_Herzegovina"
bonus = 1
color = "#00cc66"

[[countries]]
id = 1
name = "Bohemia_(Praha)"
continent = 1
x = 248
y = 47
connections = [10, 9, 2]

[[countries]]
id = 2
name = "Moravia_(Brno)"
continent = 1
x = 325
y = 92
connections = [1, 9, 3, 18]

[[countries]]
id = 3
name = "Silesia_(Opava)"
continent = 1
x = 385
y = 34
connections = [2, 7, 18]

[[countries]]
id = 4
name = "Dalmatia_(Spalato)"
continent = 1
x = 314
y = 350
connections = [5, 6]

[[countries]]
id = 5
name = "Croatia_and_Slavonia_(Agram)"
continent = 2
x = 299
y = 247
connections = [6, 4, 17, 12, 14, 19]

[[countries]]
id = 6
name = "Bosnia_and_Herzegovina_(Sarajevo)"
continent = 3
x = 389
y = 336
connections = [4, 5]

[[countries]]
id = 7
name = "Galicia_(Lemberg)"
continent = 1
x = 568
y = 47
connections = [3, 8, 18]

[[countries]]
id = 8
name = "Bucovina_(Czernowitz)"
continent = 1
x = 647
y = 118
connections = [7, 19]

[[countries]]
id = 9
name = "Lower_Austria_(Wien)"
continent = 1
x = 315
y = 131
connections = [2, 10, 1, 18]

[[countries]]
id = 10
name = "Upper_Austria_(Linz)"
continent = 1
x = 236
y = 128
connections = [9, 13, 14, 1]

[[countries]]
id = 11
name = "Carinthia_(Klagenfurt)"
continent = 1
x = 236
y = 203
connections = [14, 12, 17, 15, 13]

[[countries]]
id = 12
name = "Carniola_(Laibach)"
continent = 1
x = 249
y = 237
connections = [17, 5, 14, 11]

[[countries]]
id = 13
name = "Salzburg_(Salzburg)"
continent = 1
x = 199
y = 152
connections = [15, 11, 14, 10]

[[countries]]
id = 14
name = "Styria_(Graz)"
continent = 1
x = 279
y = 186
connections = [12, 5, 13, 10, 11, 18]

[[countries]]
id = 15
name = "Tyrol_(Innsbruck)"
continent = 1
x = 136
y = 176
connections = [16, 11, 13]

[[countries]]
id = 16
name = "Voralberg_(Bregenz)"
continent = 1
x = 112
y = 133
connections = [15]

[[countries]]
id = 17
name = "Küstenland_(Terst)"
continent = 1
x = 223
y = 265
connections = [5, 12, 11]

[[countries]]
id = 18
name = "West_Hungary_(West_Budapest)"
continent = 2
x = 395
y = 162
connections = [19, 7, 14, 9, 2, 3]

[[countries]]
id = 19
name = "East_Hungary_(East_Budapest)"
continent = 2
x = 415
y = 177
connections = [18, 8, 5]
