[info]
name = "unknown"

[files]
pic = "Hawaii_pic.png"
map = "Hawaii_map.gif"
crd = "Hawaii.cards"

[[continents]]
id = 1
name = "Hawaii"
bonus = 6
color = "red"

[[continents]]
id = 2
name = "Maui"
bonus = 5
color = "green"

[[continents]]
id = 3
name = "Oahu"
bonus = 3
color = "blue"

[[continents]]
id = 4
name = "Kauai"
bonus = 3
color = "yellow"

[[continents]]
id = 5
name = "Niihau"
bonus = 2
color = "magenta"

[[countries]]
id = 1
name = "Süd_Mauna_Loa"
continent = 1
x = 498
y = 341
connections = [70, 12, 11, 13, 3, 2]

[[countries]]
id = 2
name = "West_Mauna_Loa"
continent = 1
x = 494
y = 242
connections = [70, 18, 17, 4, 1, 3, 14, 15, 13, 5]

[[countries]]
id = 3
name = "Ost_Mauna_Loa"
continent = 1
x = 561
y = 262
connections = [70, 1, 2, 4, 8, 23, 9, 11]

[[countries]]
id = 4
name = "Mauna_Kea"
continent = 1
x = 530
y = 204
connections = [2, 3, 5, 6, 7, 8]

[[countries]]
id = 5
name = "Mauna_Kea_West_Fuß"
continent = 1
x = 508
y = 170
connections = [2, 4, 20, 17, 6]

[[countries]]
id = 6
name = "Mauna_Kea_Nord_Fuß"
continent = 1
x = 549
y = 164
connections = [4, 5, 20, 7]

[[countries]]
id = 7
name = "Mauna_Kea_Ost_Fuß"
continent = 1
x = 582
y = 195
connections = [4, 6, 8]

[[countries]]
id = 8
name = "Mauna_Kea_Süd_Fuß"
continent = 1
x = 582
y = 226
connections = [3, 4, 7]

[[countries]]
id = 9
name = "Opihikao"
continent = 1
x = 649
y = 274
connections = [3, 10, 23]

[[countries]]
id = 10
name = "Kalapana"
continent = 1
x = 643
y = 302
connections = [9, 23]

[[countries]]
id = 11
name = "Punaluu"
continent = 1
x = 554
y = 336
connections = [1, 3, 23, 12]

[[countries]]
id = 12
name = "Naalehu"
continent = 1
x = 482
y = 394
connections = [1, 11, 13]

[[countries]]
id = 13
name = "Kealia"
continent = 1
x = 451
y = 324
connections = [1, 2, 12, 14]

[[countries]]
id = 14
name = "Captain_Cook"
continent = 1
x = 445
y = 293
connections = [2, 13, 15]

[[countries]]
id = 15
name = "Kahaluu"
continent = 1
x = 435
y = 267
connections = [2, 14, 18, 16]

[[countries]]
id = 16
name = "Kailau"
continent = 1
x = 427
y = 209
connections = [15, 17, 19, 27]

[[countries]]
id = 17
name = "Puuanahulu"
continent = 1
x = 470
y = 192
connections = [2, 5, 16, 18, 20]

[[countries]]
id = 18
name = "Kalaoa"
continent = 1
x = 454
y = 240
connections = [2, 15, 17]

[[countries]]
id = 19
name = "Puako"
continent = 1
x = 464
y = 171
connections = [16, 21]

[[countries]]
id = 20
name = "Honokaa"
continent = 1
x = 504
y = 138
connections = [5, 6, 17, 21, 22]

[[countries]]
id = 21
name = "Kahua"
continent = 1
x = 459
y = 136
connections = [19, 20, 22, 26]

[[countries]]
id = 22
name = "Hawi"
continent = 1
x = 459
y = 98
connections = [21, 20, 25]

[[countries]]
id = 23
name = "Volcano"
continent = 1
x = 611
y = 291
connections = [3, 9, 10, 11]

[[countries]]
id = 24
name = "Haleakala_Crater"
continent = 2
x = 368
y = 128
connections = [32, 31, 30, 34, 25, 26, 27]

[[countries]]
id = 25
name = "Kaeleku"
continent = 2
x = 397
y = 104
connections = [24, 26, 34, 22]

[[countries]]
id = 26
name = "Haou"
continent = 2
x = 415
y = 126
connections = [24, 25, 27, 21]

[[countries]]
id = 27
name = "Kaupo"
continent = 2
x = 395
y = 151
connections = [24, 26, 32, 16]

[[countries]]
id = 28
name = "Nord_Haiku"
continent = 2
x = 348
y = 83
connections = [29, 34]

[[countries]]
id = 29
name = "West_Haiku"
continent = 2
x = 337
y = 87
connections = [28, 34, 30]

[[countries]]
id = 30
name = "Kihei"
continent = 2
x = 333
y = 107
connections = [24, 29, 31, 33, 34]

[[countries]]
id = 31
name = "Makena"
continent = 2
x = 331
y = 131
connections = [24, 30, 32]

[[countries]]
id = 32
name = "Ulupalakua"
continent = 2
x = 336
y = 160
connections = [24, 27, 31, 46]

[[countries]]
id = 33
name = "Kahului"
continent = 2
x = 318
y = 96
connections = [30, 36, 37]

[[countries]]
id = 34
name = "Wailau"
continent = 2
x = 364
y = 89
connections = [24, 25, 28, 29, 30]

[[countries]]
id = 35
name = "Kapalua"
continent = 2
x = 284
y = 67
connections = [36, 37, 41]

[[countries]]
id = 36
name = "Walhee"
continent = 2
x = 309
y = 65
connections = [33, 35, 37]

[[countries]]
id = 37
name = "Wailuku"
continent = 2
x = 297
y = 90
connections = [33, 35, 36, 43]

[[countries]]
id = 38
name = "Mauna_Loa(Stadt)"
continent = 2
x = 186
y = 43
connections = [39, 52, 40]

[[countries]]
id = 39
name = "Kalaupapa"
continent = 2
x = 191
y = 24
connections = [38, 40]

[[countries]]
id = 40
name = "Kamalo"
continent = 2
x = 223
y = 45
connections = [38, 39, 41, 42, 51]

[[countries]]
id = 41
name = "Halawa"
continent = 2
x = 262
y = 33
connections = [35, 40]

[[countries]]
id = 42
name = "Nord_Lanai"
continent = 2
x = 243
y = 109
connections = [40, 43, 44, 49]

[[countries]]
id = 43
name = "Ost_Lanai"
continent = 2
x = 269
y = 125
connections = [37, 42, 44, 45]

[[countries]]
id = 44
name = "Süd_Lanai"
continent = 2
x = 249
y = 141
connections = [42, 43]

[[countries]]
id = 45
name = "West_Kahoolawe"
continent = 2
x = 296
y = 169
connections = [43, 46]

[[countries]]
id = 46
name = "Ost_Kahoolawe"
continent = 2
x = 314
y = 162
connections = [32, 45]

[[countries]]
id = 47
name = "Honolulu"
continent = 3
x = 75
y = 180
connections = [48, 56, 50, 55, 54, 59]

[[countries]]
id = 48
name = "Waimanalo"
continent = 3
x = 130
y = 185
connections = [47, 49, 56, 58]

[[countries]]
id = 49
name = "Nord_Waimanalo"
continent = 3
x = 128
y = 162
connections = [48, 56, 50, 42]

[[countries]]
id = 50
name = "Ahuimanu"
continent = 3
x = 102
y = 136
connections = [47, 49, 51, 55, 56]

[[countries]]
id = 51
name = "Laie"
continent = 3
x = 80
y = 114
connections = [40, 50, 52, 53]

[[countries]]
id = 52
name = "Kawela_Bay"
continent = 3
x = 79
y = 93
connections = [38, 51]

[[countries]]
id = 53
name = "Makaha"
continent = 3
x = 33
y = 128
connections = [51, 54]

[[countries]]
id = 54
name = "Maili"
continent = 3
x = 47
y = 159
connections = [47, 53, 55]

[[countries]]
id = 55
name = "Waipio_Acres"
continent = 3
x = 69
y = 152
connections = [47, 50, 54]

[[countries]]
id = 56
name = "Waimalu"
continent = 3
x = 102
y = 170
connections = [47, 48, 49, 50]

[[countries]]
id = 57
name = "Kapaa"
continent = 4
x = 148
y = 299
connections = [60, 62, 61]

[[countries]]
id = 58
name = "Kilauea"
continent = 4
x = 133
y = 269
connections = [48, 60, 59]

[[countries]]
id = 59
name = "Hanalei"
continent = 4
x = 99
y = 281
connections = [58, 65, 60, 47, 64]

[[countries]]
id = 60
name = "MittelKauai"
continent = 4
x = 124
y = 292
connections = [57, 58, 59, 61]

[[countries]]
id = 61
name = "Omao"
continent = 4
x = 115
y = 320
connections = [57, 60, 64, 62, 63]

[[countries]]
id = 62
name = "Lihue"
continent = 4
x = 131
y = 340
connections = [57, 61, 63]

[[countries]]
id = 63
name = "Eleele"
continent = 4
x = 104
y = 345
connections = [61, 62, 64]

[[countries]]
id = 64
name = "Kaumakani"
continent = 4
x = 91
y = 324
connections = [59, 61, 63, 65]

[[countries]]
id = 65
name = "Kekaha"
continent = 4
x = 73
y = 299
connections = [59, 64, 67, 66]

[[countries]]
id = 66
name = "Mana"
continent = 4
x = 59
y = 316
connections = [65, 68]

[[countries]]
id = 67
name = "Nord_Niihau"
continent = 5
x = 50
y = 279
connections = [65, 68]

[[countries]]
id = 68
name = "Puuwai"
continent = 5
x = 35
y = 296
connections = [66, 67, 69]

[[countries]]
id = 69
name = "Süd_Niihau"
continent = 5
x = 24
y = 316
connections = [68]

[[countries]]
id = 70
name = "Maona_Loa"
continent = 1
x = 505
y = 288
connections = [2, 3, 1]
