[info]
name = "Risk Board Map"
nb_wildcards = 2

[[continents]]
id = 1
name = "North-America"
bonus = 5
color = "yellow"

[[continents]]
id = 2
name = "South-America"
bonus = 2
color = "red"

[[continents]]
id = 3
name = "Europe"
bonus = 5
color = "blue"

[[continents]]
id = 4
name = "Africa"
bonus = 3
color = "orange"

[[continents]]
id = 5
name = "Asia"
bonus = 7
color = "green"

[[continents]]
id = 6
name = "Australia"
bonus = 2
color = "magenta"

[[countries]]
id = 1
name = "Alaska"
continent = 1
x = 43
y = 67
cardtype = "Infantry"
connections = [2, 3, 38]

[[countries]]
id = 2
name = "North-West-Territory"
continent = 1
x = 106
y = 69
cardtype = "Cannon"
connections = [1, 3, 7, 6]

[[countries]]
id = 3
name = "Alberta"
continent = 1
x = 106
y = 105
cardtype = "Infantry"
connections = [1, 2, 7, 4]

[[countries]]
id = 4
name = "Western-United-States"
continent = 1
x = 109
y = 149
cardtype = "Infantry"
connections = [3, 7, 5, 9]

[[countries]]
id = 5
name = "Central-America"
continent = 1
x = 118
y = 205
cardtype = "Cavalry"
connections = [4, 9, 10]

[[countries]]
id = 6
name = "Greenland"
continent = 1
x = 258
y = 35
cardtype = "Cavalry"
connections = [2, 7, 8, 14]

[[countries]]
id = 7
name = "Ontario"
continent = 1
x = 152
y = 107
cardtype = "Cavalry"
connections = [2, 3, 4, 6, 8, 9]

[[countries]]
id = 8
name = "Quebec"
continent = 1
x = 206
y = 110
cardtype = "Cannon"
connections = [6, 7, 9]

[[countries]]
id = 9
name = "Eastern-United-States"
continent = 1
x = 160
y = 159
cardtype = "Cannon"
connections = [4, 5, 7, 8]

[[countries]]
id = 10
name = "Venezuela"
continent = 2
x = 164
y = 237
cardtype = "Cannon"
connections = [5, 11, 12]

[[countries]]
id = 11
name = "Peru"
continent = 2
x = 177
y = 301
cardtype = "Cavalry"
connections = [10, 12, 13]

[[countries]]
id = 12
name = "Brazil"
continent = 2
x = 216
y = 284
cardtype = "Cannon"
connections = [10, 11, 13, 21]

[[countries]]
id = 13
name = "Argentina"
continent = 2
x = 186
y = 347
cardtype = "Infantry"
connections = [11, 12]

[[countries]]
id = 14
name = "Iceland"
continent = 3
x = 286
y = 89
cardtype = "Infantry"
connections = [6, 17, 15]

[[countries]]
id = 15
name = "Scandinavia"
continent = 3
x = 346
y = 72
cardtype = "Cannon"
connections = [16, 18, 14, 17]

[[countries]]
id = 16
name = "Ukraine"
continent = 3
x = 400
y = 105
cardtype = "Cannon"
connections = [15, 28, 30, 31, 18, 20]

[[countries]]
id = 17
name = "Great-Britain"
continent = 3
x = 289
y = 118
cardtype = "Cavalry"
connections = [14, 18, 19, 15]

[[countries]]
id = 18
name = "Northern-Europe"
continent = 3
x = 336
y = 129
cardtype = "Cavalry"
connections = [15, 16, 17, 19, 20]

[[countries]]
id = 19
name = "Western-Europe"
continent = 3
x = 300
y = 163
cardtype = "Infantry"
connections = [17, 18, 20, 21]

[[countries]]
id = 20
name = "Southern-Europe"
continent = 3
x = 348
y = 165
cardtype = "Cavalry"
connections = [16, 18, 19, 21, 22, 31]

[[countries]]
id = 21
name = "North-Africa"
continent = 4
x = 313
y = 246
cardtype = "Infantry"
connections = [12, 19, 20, 22, 23, 24]

[[countries]]
id = 22
name = "Egypt"
continent = 4
x = 361
y = 216
cardtype = "Infantry"
connections = [20, 21, 24, 31]

[[countries]]
id = 23
name = "Congo"
continent = 4
x = 363
y = 304
cardtype = "Cavalry"
connections = [21, 24, 25]

[[countries]]
id = 24
name = "East-Africa"
continent = 4
x = 395
y = 274
cardtype = "Cannon"
connections = [21, 22, 23, 25, 26]

[[countries]]
id = 25
name = "South-Africa"
continent = 4
x = 369
y = 369
cardtype = "Cannon"
connections = [23, 24, 26]

[[countries]]
id = 26
name = "Madagascar"
continent = 4
x = 427
y = 366
cardtype = "Infantry"
connections = [24, 25]

[[countries]]
id = 27
name = "Siberia"
continent = 5
x = 500
y = 58
cardtype = "Cannon"
connections = [28, 29, 34, 35, 36]

[[countries]]
id = 28
name = "Ural"
continent = 5
x = 470
y = 97
cardtype = "Cavalry"
connections = [16, 27, 29, 30]

[[countries]]
id = 29
name = "China"
continent = 5
x = 550
y = 182
cardtype = "Cavalry"
connections = [27, 28, 30, 32, 33, 36]

[[countries]]
id = 30
name = "Afghanistan"
continent = 5
x = 457
y = 150
cardtype = "Infantry"
connections = [16, 28, 29, 31, 32]

[[countries]]
id = 31
name = "Middle-East"
continent = 5
x = 410
y = 194
cardtype = "Cannon"
connections = [16, 22, 30, 32, 20]

[[countries]]
id = 32
name = "India"
continent = 5
x = 496
y = 222
cardtype = "Infantry"
connections = [29, 30, 31, 33]

[[countries]]
id = 33
name = "Siam"
continent = 5
x = 556
y = 242
cardtype = "Cannon"
connections = [29, 32, 39]

[[countries]]
id = 34
name = "Yakutsk"
continent = 5
x = 565
y = 62
cardtype = "Cavalry"
connections = [27, 35, 38]

[[countries]]
id = 35
name = "Irkutsk"
continent = 5
x = 554
y = 107
cardtype = "Infantry"
connections = [27, 34, 36, 38]

[[countries]]
id = 36
name = "Mongolia"
continent = 5
x = 563
y = 143
cardtype = "Cannon"
connections = [29, 35, 37, 38, 27]

[[countries]]
id = 37
name = "Japan"
continent = 5
x = 632
y = 139
cardtype = "Infantry"
connections = [36, 38]

[[countries]]
id = 38
name = "Kamchatka"
continent = 5
x = 629
y = 62
cardtype = "Cavalry"
connections = [1, 34, 35, 36, 37]

[[countries]]
id = 39
name = "Indonesia"
continent = 6
x = 585
y = 297
cardtype = "Cavalry"
connections = [33, 41, 40]

[[countries]]
id = 40
name = "New-Guinea"
continent = 6
x = 651
y = 294
cardtype = "Cavalry"
connections = [39, 41, 42]

[[countries]]
id = 41
name = "Western-Australia"
continent = 6
x = 595
y = 375
cardtype = "Cannon"
connections = [39, 40, 42]

[[countries]]
id = 42
name = "Eastern-Australia"
continent = 6
x = 637
y = 353
cardtype = "Infantry"
connections = [40, 41]
