[info]
name = "Risk GodStorm"

[files]
pic = "godstorm_pic.jpg"
map = "godstorm_map.gif"
crd = "godstorm.cards"
prv = "godstorm.jpg"

[[continents]]
id = 1
name = "Germania"
bonus = 5
color = "green"

[[continents]]
id = 2
name = "Atlantis"
bonus = 3
color = "magenta"

[[continents]]
id = 3
name = "Asia_Minor"
bonus = 3
color = "cyan"

[[continents]]
id = 4
name = "Africa"
bonus = 5
color = "yellow"

[[continents]]
id = 5
name = "Europa"
bonus = 7
color = "red"

[[continents]]
id = 6
name = "Hyrkania"
bonus = 2
color = "orange"

[[countries]]
id = 1
name = "Dacia"
continent = 5
x = 355
y = 175
connections = [40, 2, 3]

[[countries]]
id = 2
name = "Thracia"
continent = 5
x = 403
y = 196
connections = [1, 3, 9]

[[countries]]
id = 3
name = "Dalmatia"
continent = 5
x = 316
y = 214
connections = [1, 4, 2, 9, 6]

[[countries]]
id = 4
name = "Liguria"
continent = 5
x = 265
y = 229
connections = [3, 20, 5]

[[countries]]
id = 5
name = "Roma"
continent = 5
x = 294
y = 287
connections = [4, 7, 6]

[[countries]]
id = 6
name = "Apulia"
continent = 5
x = 327
y = 300
connections = [5, 8, 9, 3]

[[countries]]
id = 7
name = "Corsica"
continent = 5
x = 259
y = 310
connections = [5]

[[countries]]
id = 8
name = "Sicilia"
continent = 5
x = 343
y = 347
connections = [23, 6]

[[countries]]
id = 9
name = "Graecia"
continent = 5
x = 401
y = 263
connections = [3, 6, 10, 11, 2]

[[countries]]
id = 10
name = "Minoa"
continent = 5
x = 445
y = 290
connections = [9, 27, 11]

[[countries]]
id = 11
name = "Ionia"
continent = 5
x = 476
y = 218
connections = [9, 12, 10]

[[countries]]
id = 12
name = "Anatolia"
continent = 5
x = 540
y = 177
connections = [11, 32]

[[countries]]
id = 13
name = "Hibernia"
continent = 1
x = 86
y = 169
connections = [15, 14, 35]

[[countries]]
id = 14
name = "Caledonia"
continent = 1
x = 142
y = 135
connections = [13, 16, 15]

[[countries]]
id = 15
name = "Anglia"
continent = 1
x = 142
y = 184
connections = [19, 20, 13, 14]

[[countries]]
id = 16
name = "Thule"
continent = 1
x = 210
y = 78
connections = [17, 19, 14]

[[countries]]
id = 17
name = "Varangia"
continent = 1
x = 314
y = 16
connections = [18, 16, 39]

[[countries]]
id = 18
name = "Galicia"
continent = 1
x = 330
y = 90
connections = [19, 17]

[[countries]]
id = 19
name = "Alemannia"
continent = 1
x = 231
y = 189
connections = [20, 18, 16, 15]

[[countries]]
id = 20
name = "Gaul"
continent = 1
x = 188
y = 258
connections = [21, 19, 15, 4]

[[countries]]
id = 21
name = "Iberia"
continent = 1
x = 148
y = 343
connections = [20, 38, 22]

[[countries]]
id = 22
name = "Atlas"
continent = 4
x = 173
y = 404
connections = [38, 21, 24, 23]

[[countries]]
id = 23
name = "Carthage"
continent = 4
x = 290
y = 361
connections = [22, 24, 25, 8]

[[countries]]
id = 24
name = "Gaitulia"
continent = 4
x = 257
y = 409
connections = [22, 23, 25, 26]

[[countries]]
id = 25
name = "Cyrenaica"
continent = 4
x = 386
y = 375
connections = [23, 24, 26, 27]

[[countries]]
id = 26
name = "Nubia"
continent = 4
x = 447
y = 410
connections = [25, 27, 24, 28]

[[countries]]
id = 27
name = "Egypt"
continent = 4
x = 517
y = 365
connections = [25, 26, 28, 32, 10]

[[countries]]
id = 28
name = "Kush"
continent = 4
x = 583
y = 398
connections = [27, 34, 26]

[[countries]]
id = 29
name = "Parthia"
continent = 3
x = 648
y = 154
connections = [31, 30, 42]

[[countries]]
id = 30
name = "Sumer"
continent = 3
x = 667
y = 234
connections = [33, 29, 31]

[[countries]]
id = 31
name = "Assyria"
continent = 3
x = 611
y = 231
connections = [33, 32, 29, 30]

[[countries]]
id = 32
name = "Phoenicia"
continent = 3
x = 545
y = 267
connections = [27, 34, 33, 31, 12]

[[countries]]
id = 33
name = "Babylon"
continent = 3
x = 614
y = 283
connections = [34, 32, 31, 30]

[[countries]]
id = 34
name = "Sheba"
continent = 3
x = 631
y = 359
connections = [28, 32, 33]

[[countries]]
id = 35
name = "Hesperide"
continent = 2
x = 37
y = 245
connections = [13, 36]

[[countries]]
id = 36
name = "Tritonis"
continent = 2
x = 35
y = 306
connections = [35, 37]

[[countries]]
id = 37
name = "Poseidonis"
continent = 2
x = 18
y = 371
connections = [36, 38]

[[countries]]
id = 38
name = "Oricalcos"
continent = 2
x = 55
y = 412
connections = [37, 22, 21]

[[countries]]
id = 39
name = "Rus"
continent = 6
x = 475
y = 39
connections = [42, 41, 40, 17]

[[countries]]
id = 40
name = "Scythia"
continent = 6
x = 422
y = 103
connections = [41, 39, 1]

[[countries]]
id = 41
name = "Cimmeria"
continent = 6
x = 512
y = 91
connections = [42, 39, 40]

[[countries]]
id = 42
name = "Sarmathia"
continent = 6
x = 621
y = 67
connections = [29, 39, 41]
