[info]
name = "unknown"

[files]
pic = "us_pic.jpg"
map = "us_map.gif"
crd = "us.cards"

[[continents]]
id = 1
name = "NORTH"
bonus = 5
color = "blue"

[[continents]]
id = 2
name = "SOUTH"
bonus = 8
color = "green"

[[continents]]
id = 3
name = "MIDWEST"
bonus = 6
color = "red"

[[continents]]
id = 4
name = "WEST"
bonus = 7
color = "purple"

[[countries]]
id = 1
name = "Washington"
continent = 4
x = 104
y = 30
connections = [2, 4]

[[countries]]
id = 2
name = "Oregon"
continent = 4
x = 92
y = 83
connections = [1, 4, 3, 5]

[[countries]]
id = 3
name = "California"
continent = 4
x = 66
y = 179
connections = [2, 5, 7, 6]

[[countries]]
id = 4
name = "Idaho"
continent = 4
x = 158
y = 100
connections = [1, 2, 5, 8, 9, 10]

[[countries]]
id = 5
name = "Nevada"
continent = 4
x = 117
y = 160
connections = [2, 3, 4, 7, 8]

[[countries]]
id = 6
name = "Alaska"
continent = 4
x = 91
y = 322
connections = [3, 13]

[[countries]]
id = 7
name = "Arizona"
continent = 4
x = 165
y = 248
connections = [3, 5, 8, 12]

[[countries]]
id = 8
name = "Utah"
continent = 4
x = 177
y = 177
connections = [4, 5, 7, 10, 11, 12]

[[countries]]
id = 9
name = "Montana"
continent = 4
x = 217
y = 58
connections = [4, 10, 18, 19]

[[countries]]
id = 10
name = "Wyoming"
continent = 4
x = 234
y = 123
connections = [4, 8, 9, 11, 17, 18]

[[countries]]
id = 11
name = "Colorado"
continent = 4
x = 246
y = 189
connections = [8, 10, 12, 15, 16, 17]

[[countries]]
id = 12
name = "New-Mexico"
continent = 4
x = 236
y = 257
connections = [7, 8, 11, 14, 15]

[[countries]]
id = 13
name = "Hawaii"
continent = 4
x = 288
y = 404
connections = [6]

[[countries]]
id = 14
name = "Texas"
continent = 2
x = 319
y = 310
connections = [12, 15, 23, 24]

[[countries]]
id = 15
name = "Oklahoma"
continent = 2
x = 350
y = 250
connections = [11, 12, 14, 16, 22, 23]

[[countries]]
id = 16
name = "Kansas"
continent = 3
x = 333
y = 202
connections = [11, 15, 17, 22]

[[countries]]
id = 17
name = "Nebraska"
continent = 3
x = 318
y = 153
connections = [10, 11, 16, 18, 21, 22]

[[countries]]
id = 18
name = "South-Dakota"
continent = 3
x = 315
y = 108
connections = [9, 10, 17, 19, 20, 21]

[[countries]]
id = 19
name = "North-Dakota"
continent = 3
x = 315
y = 60
connections = [9, 18, 20]

[[countries]]
id = 20
name = "Minnesota"
continent = 3
x = 382
y = 108
connections = [18, 19, 21, 29]

[[countries]]
id = 21
name = "Iowa"
continent = 3
x = 387
y = 144
connections = [17, 18, 20, 22, 28, 29]

[[countries]]
id = 22
name = "Missouri"
continent = 3
x = 405
y = 202
connections = [15, 16, 17, 21, 23, 26, 27, 28]

[[countries]]
id = 23
name = "Arkansas"
continent = 2
x = 408
y = 258
connections = [14, 15, 22, 24, 25, 26]

[[countries]]
id = 24
name = "Louisiana"
continent = 2
x = 410
y = 318
connections = [14, 23, 25]

[[countries]]
id = 25
name = "Mississippi"
continent = 2
x = 455
y = 288
connections = [23, 24, 26, 32]

[[countries]]
id = 26
name = "Tennessee"
continent = 2
x = 481
y = 237
connections = [22, 23, 25, 27, 32, 34, 36, 37]

[[countries]]
id = 27
name = "Kentucky"
continent = 2
x = 501
y = 205
connections = [22, 26, 28, 31, 37, 38, 39]

[[countries]]
id = 28
name = "Illinois"
continent = 3
x = 442
y = 172
connections = [21, 22, 27, 29, 31]

[[countries]]
id = 29
name = "Wisconsin"
continent = 3
x = 431
y = 104
connections = [20, 21, 28, 30]

[[countries]]
id = 30
name = "Michigan"
continent = 3
x = 489
y = 119
connections = [29, 31, 39]

[[countries]]
id = 31
name = "Indiana"
continent = 3
x = 479
y = 173
connections = [27, 28, 30, 39]

[[countries]]
id = 32
name = "Alabama"
continent = 2
x = 483
y = 284
connections = [25, 26, 33, 34]

[[countries]]
id = 33
name = "Florida"
continent = 2
x = 561
y = 350
connections = [32, 34]

[[countries]]
id = 34
name = "Georgia"
continent = 2
x = 526
y = 281
connections = [26, 32, 33, 35, 36]

[[countries]]
id = 35
name = "South-Carolina"
continent = 2
x = 557
y = 258
connections = [34, 36]

[[countries]]
id = 36
name = "North-Carolina"
continent = 2
x = 564
y = 228
connections = [26, 34, 35, 37]

[[countries]]
id = 37
name = "Virginia"
continent = 2
x = 577
y = 197
connections = [26, 27, 36, 38, 41]

[[countries]]
id = 38
name = "West-Virginia"
continent = 2
x = 545
y = 186
connections = [27, 37, 39, 40, 41]

[[countries]]
id = 39
name = "Ohio"
continent = 3
x = 518
y = 165
connections = [27, 31, 30, 38, 40]

[[countries]]
id = 40
name = "Pennsylvania"
continent = 1
x = 573
y = 145
connections = [38, 39, 41, 42, 43, 44]

[[countries]]
id = 41
name = "Maryland"
continent = 1
x = 568
y = 168
connections = [37, 38, 40, 42]

[[countries]]
id = 42
name = "Delaware"
continent = 1
x = 608
y = 166
connections = [40, 41, 43]

[[countries]]
id = 43
name = "New-Jersey"
continent = 1
x = 613
y = 149
connections = [40, 42, 44]

[[countries]]
id = 44
name = "New-York"
continent = 1
x = 597
y = 107
connections = [40, 43, 45, 47, 48]

[[countries]]
id = 45
name = "Connecticut"
continent = 1
x = 632
y = 122
connections = [44, 46, 47]

[[countries]]
id = 46
name = "Rhode-Island"
continent = 1
x = 646
y = 116
connections = [45, 47]

[[countries]]
id = 47
name = "Massachusetts"
continent = 1
x = 635
y = 105
connections = [44, 45, 46, 48, 49]

[[countries]]
id = 48
name = "Vermont"
continent = 1
x = 619
y = 83
connections = [44, 47, 49]

[[countries]]
id = 49
name = "New-Hampshire"
continent = 1
x = 634
y = 89
connections = [47, 48, 50]

[[countries]]
id = 50
name = "Maine"
continent = 1
x = 652
y = 50
connections = [49]
