[info]
name = "Tube Map"

[files]
pic = "tube_pic.png"
map = "tube_map.gif"
crd = "nomission.cards"
prv = "tube.jpg"

[[continents]]
id = 1
name = "London"
bonus = 10
color = "red"

[[countries]]
id = 1
name = "Aldgate"
continent = 1
x = 581
y = 175
connections = [56, 34]

[[countries]]
id = 2
name = "Aldgate-East"
continent = 1
x = 626
y = 165
connections = [56, 34]

[[countries]]
id = 3
name = "Angel"
continent = 1
x = 456
y = 55
connections = [41, 29]

[[countries]]
id = 4
name = "Baker-Street"
continent = 1
x = 228
y = 67
connections = [24, 38, 16, 9, 47]

[[countries]]
id = 5
name = "Bank-Monument"
continent = 1
x = 494
y = 192
connections = [56, 60, 35, 34, 39, 50, 11]

[[countries]]
id = 6
name = "Barbican"
continent = 1
x = 450
y = 95
connections = [39, 21]

[[countries]]
id = 7
name = "Bayswater"
continent = 1
x = 107
y = 108
connections = [43, 40]

[[countries]]
id = 8
name = "Blackfriars"
continent = 1
x = 407
y = 228
connections = [36, 54]

[[countries]]
id = 9
name = "Bond-Street"
continent = 1
x = 222
y = 147
connections = [42, 37, 25, 4]

[[countries]]
id = 10
name = "Borough"
continent = 1
x = 431
y = 347
connections = [17, 35]

[[countries]]
id = 11
name = "Cannon-Street"
continent = 1
x = 446
y = 203
connections = [5, 36]

[[countries]]
id = 12
name = "Chancery-Lane"
continent = 1
x = 413
y = 148
connections = [50, 27]

[[countries]]
id = 13
name = "Charing-Cross"
continent = 1
x = 338
y = 236
connections = [18, 33, 44]

[[countries]]
id = 14
name = "Covent-Garden"
continent = 1
x = 363
y = 161
connections = [27, 33]

[[countries]]
id = 15
name = "Earl's-Court"
continent = 1
x = 96
y = 260
connections = [22, 26]

[[countries]]
id = 16
name = "Edgware-Road"
continent = 1
x = 148
y = 67
connections = [43, 38, 4]

[[countries]]
id = 17
name = "Elephant-&-Castle"
continent = 1
x = 367
y = 414
connections = [31, 10]

[[countries]]
id = 18
name = "Embankment"
continent = 1
x = 342
y = 267
connections = [60, 13, 54, 61]

[[countries]]
id = 19
name = "Euston"
continent = 1
x = 365
y = 43
connections = [29, 59]

[[countries]]
id = 20
name = "Euston-Square"
continent = 1
x = 363
y = 63
connections = [29, 24]

[[countries]]
id = 21
name = "Farringdon"
continent = 1
x = 434
y = 80
connections = [6, 29]

[[countries]]
id = 22
name = "Gloucester-Road"
continent = 1
x = 136
y = 258
connections = [52, 15, 26]

[[countries]]
id = 23
name = "Goodge-Street"
continent = 1
x = 338
y = 112
connections = [59, 55]

[[countries]]
id = 24
name = "Great-Portland-Street"
continent = 1
x = 300
y = 61
connections = [20, 4]

[[countries]]
id = 25
name = "Green-Park"
continent = 1
x = 232
y = 196
connections = [44, 42, 9, 28, 58, 61]

[[countries]]
id = 26
name = "High-Street-Kensington"
continent = 1
x = 107
y = 189
connections = [40, 15, 22]

[[countries]]
id = 27
name = "Holborn"
continent = 1
x = 379
y = 147
connections = [55, 12, 14, 48]

[[countries]]
id = 28
name = "Hyde-Park-Corner"
continent = 1
x = 214
y = 205
connections = [30, 25]

[[countries]]
id = 29
name = "King's-Cross-St.Pancras"
continent = 1
x = 405
y = 48
connections = [19, 20, 48, 21, 3]

[[countries]]
id = 30
name = "Knightsbridge"
continent = 1
x = 195
y = 224
connections = [28, 52]

[[countries]]
id = 31
name = "Lambeth-North"
continent = 1
x = 346
y = 380
connections = [17, 60]

[[countries]]
id = 32
name = "Lancaster-Gate"
continent = 1
x = 174
y = 148
connections = [37, 46]

[[countries]]
id = 33
name = "Leicester-Square"
continent = 1
x = 338
y = 188
connections = [55, 13, 44, 14]

[[countries]]
id = 34
name = "Liverpool-Street"
continent = 1
x = 558
y = 114
connections = [1, 2, 39, 5]

[[countries]]
id = 35
name = "London-Bridge"
continent = 1
x = 492
y = 276
connections = [10, 53, 5]

[[countries]]
id = 36
name = "Mansion-House"
continent = 1
x = 418
y = 218
connections = [8, 11]

[[countries]]
id = 37
name = "Marble-Arch"
continent = 1
x = 195
y = 147
connections = [9, 32]

[[countries]]
id = 38
name = "Marylebone"
continent = 1
x = 188
y = 74
connections = [16, 4]

[[countries]]
id = 39
name = "Moorgate"
continent = 1
x = 492
y = 111
connections = [34, 5, 6, 41]

[[countries]]
id = 40
name = "Notting-Hill-Gate"
continent = 1
x = 110
y = 147
connections = [7, 26, 46]

[[countries]]
id = 41
name = "Old-Street"
continent = 1
x = 492
y = 70
connections = [3, 39]

[[countries]]
id = 42
name = "Oxford-Circus"
continent = 1
x = 270
y = 147
connections = [9, 55, 44, 47, 25, 59]

[[countries]]
id = 43
name = "Paddington"
continent = 1
x = 104
y = 69
connections = [16, 7]

[[countries]]
id = 44
name = "Piccadilly-Circus"
continent = 1
x = 298
y = 196
connections = [33, 25, 13, 42]

[[countries]]
id = 45
name = "Pimlico"
continent = 1
x = 234
y = 345
connections = [57, 58]

[[countries]]
id = 46
name = "Queensway"
continent = 1
x = 137
y = 147
connections = [40, 32]

[[countries]]
id = 47
name = "Regent's-Park"
continent = 1
x = 259
y = 97
connections = [4, 42]

[[countries]]
id = 48
name = "Russell-Square"
continent = 1
x = 386
y = 98
connections = [29, 27]

[[countries]]
id = 49
name = "St.James's-Park"
continent = 1
x = 255
y = 261
connections = [58, 61]

[[countries]]
id = 50
name = "St.Paul's"
continent = 1
x = 440
y = 162
connections = [5, 12]

[[countries]]
id = 51
name = "Sloane-Square"
continent = 1
x = 204
y = 262
connections = [58, 52]

[[countries]]
id = 52
name = "South-Kensington"
continent = 1
x = 158
y = 260
connections = [51, 30, 22]

[[countries]]
id = 53
name = "Southwark"
continent = 1
x = 395
y = 342
connections = [60, 35]

[[countries]]
id = 54
name = "Temple"
continent = 1
x = 388
y = 243
connections = [8, 18]

[[countries]]
id = 55
name = "Tottenham-Court-Road"
continent = 1
x = 338
y = 147
connections = [42, 27, 33, 23]

[[countries]]
id = 56
name = "Tower-Hill-Tower-Gateway"
continent = 1
x = 579
y = 211
connections = [5, 1, 2]

[[countries]]
id = 57
name = "Vauxhall"
continent = 1
x = 244
y = 414
connections = [45]

[[countries]]
id = 58
name = "Victoria"
continent = 1
x = 232
y = 263
connections = [25, 45, 51, 49]

[[countries]]
id = 59
name = "Warren-Street"
continent = 1
x = 338
y = 78
connections = [19, 23, 42]

[[countries]]
id = 60
name = "Waterloo"
continent = 1
x = 343
y = 312
connections = [61, 53, 18, 31, 5]

[[countries]]
id = 61
name = "Westminster"
continent = 1
x = 301
y = 263
connections = [49, 18, 60, 25]
