[info]
name = "unknown"

[files]
pic = "rub_pic.jpg"
map = "rub_map.gif"
crd = "rub.cards"

[[continents]]
id = 1
name = "Medizin"
bonus = 2
color = "red"

[[continents]]
id = 2
name = "Ingenieurwissenschaften"
bonus = 4
color = "blue"

[[continents]]
id = 3
name = "Gesellschaftswissenschaften"
bonus = 3
color = "yellow"

[[continents]]
id = 4
name = "Naturwissenschaften"
bonus = 5
color = "green"

[[continents]]
id = 5
name = "Verwaltung"
bonus = 7
color = "orange"

[[countries]]
id = 1
name = "HMA"
continent = 1
x = 188
y = 122
connections = [2]

[[countries]]
id = 2
name = "MA"
continent = 1
x = 221
y = 101
connections = [1, 14, 16, 28, 30]

[[countries]]
id = 3
name = "IAN"
continent = 2
x = 404
y = 36
connections = [4, 6, 29]

[[countries]]
id = 4
name = "IA"
continent = 2
x = 439
y = 122
connections = [3, 5, 7, 29, 31]

[[countries]]
id = 5
name = "HIA"
continent = 2
x = 475
y = 162
connections = [4, 20, 22]

[[countries]]
id = 6
name = "IBN"
continent = 2
x = 479
y = 32
connections = [3, 7, 9]

[[countries]]
id = 7
name = "IB"
continent = 2
x = 510
y = 122
connections = [4, 6, 8, 10]

[[countries]]
id = 8
name = "HIB"
continent = 2
x = 539
y = 157
connections = [7, 10, 22]

[[countries]]
id = 9
name = "ICN"
continent = 2
x = 549
y = 48
connections = [6, 10]

[[countries]]
id = 10
name = "IC"
continent = 2
x = 583
y = 122
connections = [7, 9, 11]

[[countries]]
id = 11
name = "HIC"
continent = 2
x = 612
y = 162
connections = [10, 24]

[[countries]]
id = 12
name = "GC"
continent = 3
x = 53
y = 276
connections = [13, 14]

[[countries]]
id = 13
name = "HGC"
continent = 3
x = 87
y = 230
connections = [12, 14]

[[countries]]
id = 14
name = "GB"
continent = 3
x = 120
y = 276
connections = [2, 12, 13, 15, 16]

[[countries]]
id = 15
name = "HGB"
continent = 3
x = 156
y = 230
connections = [14, 16]

[[countries]]
id = 16
name = "GA"
continent = 3
x = 190
y = 276
connections = [2, 14, 15, 17, 33]

[[countries]]
id = 17
name = "HGA"
continent = 3
x = 227
y = 230
connections = [16, 33]

[[countries]]
id = 18
name = "RZ"
continent = 4
x = 378
y = 266
connections = [19, 32, 33]

[[countries]]
id = 19
name = "NA"
continent = 4
x = 408
y = 303
connections = [18, 20, 24]

[[countries]]
id = 20
name = "HNA"
continent = 4
x = 442
y = 266
connections = [5, 19, 21]

[[countries]]
id = 21
name = "NB"
continent = 4
x = 475
y = 303
connections = [20, 22, 26]

[[countries]]
id = 22
name = "HNB"
continent = 4
x = 516
y = 266
connections = [5, 8, 21, 23]

[[countries]]
id = 23
name = "NC"
continent = 4
x = 550
y = 303
connections = [22, 24, 26]

[[countries]]
id = 24
name = "HNC"
continent = 4
x = 578
y = 266
connections = [11, 23, 25]

[[countries]]
id = 25
name = "ND"
continent = 4
x = 616
y = 303
connections = [24, 26]

[[countries]]
id = 26
name = "Isolab"
continent = 4
x = 530
y = 390
connections = [21, 23, 25]

[[countries]]
id = 27
name = "MZ"
continent = 5
x = 303
y = 40
connections = [28]

[[countries]]
id = 28
name = "Studentenhaus"
continent = 5
x = 288
y = 90
connections = [2, 27, 29]

[[countries]]
id = 29
name = "Verwaltung"
continent = 5
x = 351
y = 95
connections = [3, 4, 28, 30]

[[countries]]
id = 30
name = "Bibliothek"
continent = 5
x = 308
y = 146
connections = [2, 31, 33]

[[countries]]
id = 31
name = "FNO"
continent = 5
x = 387
y = 159
connections = [4, 5, 30, 32]

[[countries]]
id = 32
name = "HZO"
continent = 5
x = 385
y = 215
connections = [18, 31]

[[countries]]
id = 33
name = "Audimax"
continent = 5
x = 316
y = 273
connections = [16, 17, 18, 34]

[[countries]]
id = 34
name = "Mensa"
continent = 5
x = 313
y = 341
connections = [19, 33]
