[startup]
map = "risk"

[startup.players]
count = 4

# Player 0 is the human
player0.name = ""

player0.color = '#333333'
player1.color = '#FF2052'
player2.color = '#01A368'
player3.color = '#0066FF'
player4.color = '#DCB63B'
player5.color = '#9E5B40'
