[info]
name = "unknown"
nb_wildcards = 0

[[continents]]
id = 1
name = "Bapnimal"
bonus = 6
color = "white"

[[continents]]
id = 2
name = "Kravirk"
bonus = 3
color = "white"

[[continents]]
id = 3
name = "Västra_Länderna"
bonus = 5
color = "white"

[[continents]]
id = 4
name = "Livenda"
bonus = 7
color = "white"

[[continents]]
id = 5
name = "Boeminas"
bonus = 3
color = "white"

[[continents]]
id = 6
name = "Ödlefolket"
bonus = 4
color = "white"

[[continents]]
id = 7
name = "Liva"
bonus = 6
color = "white"

[[countries]]
id = 1
name = "Västra_Heden"
continent = 1
x = 63
y = 30
cardtype = "Cavalry"
connections = [2, 4, 15]

[[countries]]
id = 2
name = "Västra_Bergsheden"
continent = 1
x = 186
y = 11
cardtype = "Infantry"
connections = [3, 5, 7, 4, 1]

[[countries]]
id = 3
name = "Östra_Bergsheden"
continent = 1
x = 374
y = 6
cardtype = "Cannon"
connections = [8, 9, 10, 2, 11]

[[countries]]
id = 4
name = "Mael"
continent = 1
x = 152
y = 58
cardtype = "Cavalry"
connections = [5, 7, 6, 2, 1]

[[countries]]
id = 5
name = "Rien"
continent = 1
x = 208
y = 44
cardtype = "Infantry"
connections = [7, 4, 2]

[[countries]]
id = 6
name = "Gränsområdet"
continent = 1
x = 132
y = 106
cardtype = "Cannon"
connections = [7, 4, 17, 15]

[[countries]]
id = 7
name = "Baptista"
continent = 1
x = 244
y = 64
cardtype = "Cavalry"
connections = [8, 6, 5, 4, 2, 26]

[[countries]]
id = 8
name = "Tericor"
continent = 1
x = 323
y = 43
cardtype = "Infantry"
connections = [9, 7, 3, 28, 27]

[[countries]]
id = 9
name = "Melka"
continent = 1
x = 412
y = 46
cardtype = "Cannon"
connections = [10, 8, 3, 28]

[[countries]]
id = 10
name = "Oskan"
continent = 1
x = 478
y = 50
cardtype = "Cavalry"
connections = [9, 3, 11, 28]

[[countries]]
id = 11
name = "Norra_Kravirk"
continent = 2
x = 576
y = 25
cardtype = "Infantry"
connections = [10, 3, 12]

[[countries]]
id = 12
name = "Kravirk"
continent = 2
x = 618
y = 98
cardtype = "Cannon"
connections = [11, 13, 33, 28]

[[countries]]
id = 13
name = "Västra_Kravirk"
continent = 2
x = 616
y = 165
cardtype = "Cavalry"
connections = [12, 14, 33]

[[countries]]
id = 14
name = "Praschva"
continent = 2
x = 626
y = 232
cardtype = "Infantry"
connections = [13, 33, 38, 46]

[[countries]]
id = 15
name = "Nirdo"
continent = 3
x = 61
y = 87
cardtype = "Cannon"
connections = [1, 6, 16]

[[countries]]
id = 16
name = "Sittka"
continent = 3
x = 63
y = 176
cardtype = "Cavalry"
connections = [17, 19, 18, 15]

[[countries]]
id = 17
name = "Östsittka"
continent = 3
x = 129
y = 185
cardtype = "Infantry"
connections = [19, 18, 6, 16, 25]

[[countries]]
id = 18
name = "Bittka"
continent = 3
x = 63
y = 282
cardtype = "Cannon"
connections = [19, 17, 20, 16]

[[countries]]
id = 19
name = "Dinare"
continent = 3
x = 151
y = 291
cardtype = "Cavalry"
connections = [21, 22, 18, 17, 20, 16, 25]

[[countries]]
id = 20
name = "Vo_Bitt"
continent = 3
x = 66
y = 368
cardtype = "Infantry"
connections = [19, 18]

[[countries]]
id = 21
name = "Kvattro"
continent = 3
x = 230
y = 253
cardtype = "Cannon"
connections = [23, 22, 19, 29, 25]

[[countries]]
id = 22
name = "Ön"
continent = 3
x = 265
y = 315
cardtype = "Cavalry"
connections = [23, 21, 19]

[[countries]]
id = 23
name = "Antak"
continent = 3
x = 320
y = 274
cardtype = "Infantry"
connections = [24, 22, 21, 29, 41]

[[countries]]
id = 24
name = "Västliva"
continent = 7
x = 362
y = 281
cardtype = "Cannon"
connections = [23, 34, 36]

[[countries]]
id = 25
name = "Gir"
continent = 4
x = 208
y = 198
cardtype = "Cavalry"
connections = [17, 21, 19, 29, 26]

[[countries]]
id = 26
name = "Tarvig"
continent = 4
x = 234
y = 129
cardtype = "Infantry"
connections = [29, 27, 7, 25]

[[countries]]
id = 27
name = "Drakrike"
continent = 4
x = 316
y = 103
cardtype = "Cannon"
connections = [30, 8, 28, 29, 26]

[[countries]]
id = 28
name = "Fredrikstad"
continent = 4
x = 446
y = 100
cardtype = "Cavalry"
connections = [30, 31, 32, 33, 10, 9, 8, 27, 12]

[[countries]]
id = 29
name = "Taril"
continent = 4
x = 332
y = 194
cardtype = "Infantry"
connections = [30, 31, 32, 23, 21, 27, 26, 25]

[[countries]]
id = 30
name = "Lealaya"
continent = 4
x = 370
y = 121
cardtype = "Cannon"
connections = [31, 29, 28, 27]

[[countries]]
id = 31
name = "Gendalar"
continent = 4
x = 413
y = 151
cardtype = "Cavalry"
connections = [32, 30, 29, 28]

[[countries]]
id = 32
name = "Livenda"
continent = 4
x = 434
y = 191
cardtype = "Infantry"
connections = [34, 33, 31, 29, 28, 35]

[[countries]]
id = 33
name = "Skeedvir"
continent = 4
x = 547
y = 167
cardtype = "Cannon"
connections = [32, 13, 14, 12, 28, 38, 35]

[[countries]]
id = 34
name = "Liva"
continent = 7
x = 365
y = 261
cardtype = "Cavalry"
connections = [24, 32, 36]

[[countries]]
id = 35
name = "Zamboda"
continent = 5
x = 476
y = 203
cardtype = "Infantry"
connections = [32, 38, 33, 37]

[[countries]]
id = 36
name = "Östliva"
continent = 7
x = 378
y = 273
cardtype = "Cannon"
connections = [24, 34, 37]

[[countries]]
id = 37
name = "Dvidra"
continent = 5
x = 493
y = 234
cardtype = "Cavalry"
connections = [38, 39, 36, 35, 45, 42, 46]

[[countries]]
id = 38
name = "Prakrav"
continent = 5
x = 572
y = 234
cardtype = "Infantry"
connections = [33, 14, 37, 35, 46]

[[countries]]
id = 39
name = "Korridoren"
continent = 5
x = 496
y = 287
cardtype = "Cannon"
connections = [40, 37]

[[countries]]
id = 40
name = "Drin"
continent = 5
x = 503
y = 337
cardtype = "Cavalry"
connections = [39, 47]

[[countries]]
id = 41
name = "Västra_Schvaasi"
continent = 6
x = 377
y = 346
cardtype = "Infantry"
connections = [42, 43, 23]

[[countries]]
id = 42
name = "Schvaasi"
continent = 6
x = 446
y = 307
cardtype = "Cannon"
connections = [43, 41, 37, 47]

[[countries]]
id = 43
name = "Quissh"
continent = 6
x = 453
y = 393
cardtype = "Cavalry"
connections = [44, 42, 41, 47]

[[countries]]
id = 44
name = "Östra_Quissh"
continent = 6
x = 567
y = 392
cardtype = "Infantry"
connections = [45, 43, 47]

[[countries]]
id = 45
name = "Norra_Schvaasi"
continent = 6
x = 549
y = 305
cardtype = "Cannon"
connections = [46, 37, 44, 47]

[[countries]]
id = 46
name = "Östra_Schvaasi"
continent = 6
x = 619
y = 294
cardtype = "Cavalry"
connections = [45, 38, 14, 37]

[[countries]]
id = 47
name = "Drins_Port"
continent = 6
x = 505
y = 367
cardtype = "Infantry"
connections = [44, 43, 42, 40, 45]
